package com.buttclapdev.twogamerl.model;

import com.buttclapdev.twogamerl.model.GameProject.*;
import java.util.*;
import java.util.regex.*;

/** Project-wide dependency inspection and safe asset replacement used by RC authoring tools. */
public final class ResourceIntegrity {
    private ResourceIntegrity(){}
    public static List<String>assetUses(GameProject p,String key){ArrayList<String>u=new ArrayList<>();if(p==null||key==null)return u;for(Asset a:p.getAssets().values())if(key.equals(a.sourceAssetKey))u.add("Región "+a.key);for(TileDef t:p.getTiles().values()){if(key.equals(t.assetKey))u.add("Tile "+t.name);for(TileVariant v:t.variants)if(key.equals(v.assetKey))u.add("Variante de tile "+t.name);if(t.autotileAssets.containsValue(key))u.add("Autotile "+t.name);}for(AnimationClip c:p.getAnimationClips().values())for(AnimationFrame f:c.frames)if(key.equals(f.assetKey))u.add("Animación "+c.name);for(Level l:p.getLevels().values()){if(key.equals(l.backgroundAssetKey))u.add("Fondo de escena "+l.name);for(EntityDef e:l.entities)if(key.equals(e.assetKey))u.add("Entidad "+e.name);}for(PrefabDef f:p.getPrefabs().values())if(f.template!=null&&key.equals(f.template.assetKey))u.add("Prefab "+f.name);for(MenuScreen m:p.getMenus().values()){if(key.equals(m.backgroundAssetKey)||key.equals(m.titleAssetKey))u.add("Menú "+m.title);for(MenuButton b:m.buttons)if(key.equals(b.assetKey)||key.equals(b.hoverAssetKey))u.add("Botón "+b.text);}for(TextStyle s:p.getTextStyles().values())if(key.equals(s.skinAssetKey))u.add("TextStyle "+s.name);for(ParticlePreset s:p.getParticlePresets().values())if(key.equals(s.assetKey))u.add("Partículas "+s.name);for(UISkinAsset s:p.getUiSkins().values())if(List.of(s.normalAssetKey,s.hoverAssetKey,s.pressedAssetKey,s.disabledAssetKey).contains(key))u.add("UISkin "+s.name);return u.stream().distinct().toList();}
    public static int replaceAsset(GameProject p,String oldKey,String newKey){if(p==null||oldKey==null||oldKey.equals(newKey))return 0;int[]n={0};for(Asset a:p.getAssets().values())if(oldKey.equals(a.sourceAssetKey)){a.sourceAssetKey=newKey;n[0]++;}for(TileDef t:p.getTiles().values()){if(oldKey.equals(t.assetKey)){t.assetKey=newKey;n[0]++;}for(TileVariant v:t.variants)if(oldKey.equals(v.assetKey)){v.assetKey=newKey;n[0]++;}t.autotileAssets.replaceAll((m,v)->{if(oldKey.equals(v)){n[0]++;return newKey;}return v;});}for(AnimationClip c:p.getAnimationClips().values())for(AnimationFrame f:c.frames)if(oldKey.equals(f.assetKey)){f.assetKey=newKey;n[0]++;}for(Level l:p.getLevels().values()){if(oldKey.equals(l.backgroundAssetKey)){l.backgroundAssetKey=newKey;n[0]++;}l.script=replaceToken(l.script,oldKey,newKey);for(TileLayer z:l.tileLayers)z.script=replaceToken(z.script,oldKey,newKey);for(EntityDef e:l.entities){if(oldKey.equals(e.assetKey)){e.assetKey=newKey;n[0]++;}e.script=replaceToken(e.script,oldKey,newKey);for(ComponentDef c:e.components)c.properties.replaceAll((k,v)->oldKey.equals(v)?newKey:v);}}for(PrefabDef f:p.getPrefabs().values())if(f.template!=null){if(oldKey.equals(f.template.assetKey)){f.template.assetKey=newKey;n[0]++;}f.template.script=replaceToken(f.template.script,oldKey,newKey);for(ComponentDef c:f.template.components)c.properties.replaceAll((k,v)->oldKey.equals(v)?newKey:v);}for(MenuScreen m:p.getMenus().values()){if(oldKey.equals(m.backgroundAssetKey)){m.backgroundAssetKey=newKey;n[0]++;}if(oldKey.equals(m.titleAssetKey)){m.titleAssetKey=newKey;n[0]++;}for(MenuButton b:m.buttons){if(oldKey.equals(b.assetKey)){b.assetKey=newKey;n[0]++;}if(oldKey.equals(b.hoverAssetKey)){b.hoverAssetKey=newKey;n[0]++;}}}for(TextStyle s:p.getTextStyles().values())if(oldKey.equals(s.skinAssetKey)){s.skinAssetKey=newKey;n[0]++;}for(ParticlePreset s:p.getParticlePresets().values())if(oldKey.equals(s.assetKey)){s.assetKey=newKey;n[0]++;}for(UISkinAsset s:p.getUiSkins().values()){if(oldKey.equals(s.normalAssetKey)){s.normalAssetKey=newKey;n[0]++;}if(oldKey.equals(s.hoverAssetKey)){s.hoverAssetKey=newKey;n[0]++;}if(oldKey.equals(s.pressedAssetKey)){s.pressedAssetKey=newKey;n[0]++;}if(oldKey.equals(s.disabledAssetKey)){s.disabledAssetKey=newKey;n[0]++;}}return n[0];}
    public static List<String>brokenAssetReferences(GameProject p){ArrayList<String>b=new ArrayList<>();Set<String>keys=p.getAssets().keySet();for(TileDef t:p.getTiles().values()){check(b,keys,t.assetKey,"Tile "+t.name);for(TileVariant v:t.variants)check(b,keys,v.assetKey,"Variante "+t.name);for(String a:t.autotileAssets.values())check(b,keys,a,"Autotile "+t.name);}for(AnimationClip c:p.getAnimationClips().values())for(AnimationFrame f:c.frames)check(b,keys,f.assetKey,"Clip "+c.name);for(UISkinAsset s:p.getUiSkins().values())for(String a:List.of(s.normalAssetKey,s.hoverAssetKey,s.pressedAssetKey,s.disabledAssetKey))check(b,keys,a,"UISkin "+s.name);for(ParticlePreset s:p.getParticlePresets().values())check(b,keys,s.assetKey,"Partículas "+s.name);return b;}
    private static void check(List<String>o,Set<String>keys,String ref,String where){if(ref!=null&&!ref.isBlank()&&!keys.contains(ref))o.add(where+" → falta "+ref);}private static String replaceToken(String s,String oldKey,String newKey){if(s==null||s.isEmpty())return s;return s.replaceAll("(?<![A-Za-z0-9_.-])"+Pattern.quote(oldKey)+"(?![A-Za-z0-9_.-])",Matcher.quoteReplacement(newKey));}
}
