package com.buttclapdev.twogamerl.studio;

import com.buttclapdev.twogamerl.model.GameProject.Asset;
import com.buttclapdev.twogamerl.model.GameProject.FontAsset;
import com.buttclapdev.twogamerl.model.GameProject.TileDef;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.scene.Node;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.stage.FileChooser;

import java.io.ByteArrayInputStream;
import java.nio.file.Files;
import java.util.*;

final class GraphicsEditorPane extends SplitPane {
    private static final double PREVIEW_LIMIT=640;
    private final StudioApp app;private final ListView<Asset>assets=new ListView<>();private final ListView<FontAsset>fonts=new ListView<>();private final Canvas preview=new Canvas();private final ComboBox<String>previewZoom=new ComboBox<>();private final ListView<TileDef>tiles=new ListView<>();private final VBox tileInspector=new VBox(10);private final Button regionButton=new Button("Definir regiones de spritesheet");private Asset previewAsset;
    private List<Asset>assetClipboard=List.of();private List<TileDef>tileClipboard=List.of();private List<FontAsset>fontClipboard=List.of();

    GraphicsEditorPane(StudioApp app){this.app=app;getItems().addAll(left(),center(),right());setDividerPositions(.22,.7);EditorShortcuts.install(this,this::copyContext,this::pasteContext,this::deleteContext);refresh();}
    private Node left(){
        assets.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);fonts.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);
        VBox imageBox=new VBox(8,assets);VBox.setVgrow(assets,Priority.ALWAYS);Button importImage=new Button("Importar imagen"),importSheet=new Button("Importar spritesheet"),pixel=new Button("Pixel Lab");regionButton.setDisable(true);importSheet.getStyleClass().add("primary-button");importImage.setOnAction(e->importAssets());importSheet.setOnAction(e->importSpritesheet());pixel.setOnAction(e->new PixelArtEditor().show(app.owner(),a->{String key=uniqueAsset(a.key);app.project().getAssets().put(key,new Asset(key,key,a.data));app.changed();refreshAssets(key);}));regionButton.setOnAction(e->defineRegionsForSelected());for(Button b:List.of(importImage,importSheet,pixel,regionButton))b.setMaxWidth(Double.MAX_VALUE);imageBox.getChildren().addAll(importImage,importSheet,pixel,regionButton,hint("La hoja se almacena una sola vez; las divisiones son regiones virtuales y no PNG nuevos."));
        VBox fontBox=new VBox(8,fonts);VBox.setVgrow(fonts,Priority.ALWAYS);Button importFont=new Button("Importar fuente TTF/OTF");importFont.setMaxWidth(Double.MAX_VALUE);importFont.setOnAction(e->importFont());fontBox.getChildren().addAll(importFont,hint("Las fuentes se empaquetan con el proyecto y pueden usarse en menús."));
        TabPane tabs=new TabPane();tabs.setTabClosingPolicy(TabPane.TabClosingPolicy.UNAVAILABLE);Tab images=new Tab("Imágenes",imageBox),fontTab=new Tab("Fuentes",fontBox);tabs.getTabs().addAll(images,fontTab);VBox box=new VBox(8,title("RECURSOS"),tabs,hint("Ctrl+C / Ctrl+V duplica recursos. Supr elimina sin dejar referencias colgantes."));box.getStyleClass().add("side-panel");box.setPadding(new Insets(12));box.setPrefWidth(340);VBox.setVgrow(tabs,Priority.ALWAYS);
        assets.getSelectionModel().selectedItemProperty().addListener((o,a,b)->{showPreview(b);regionButton.setDisable(b==null||sourceFor(b)==null);});return box;
    }
    private Node center(){previewZoom.getItems().addAll("Auto pixel","1×","2×","4×","8×","16×");previewZoom.setValue("Auto pixel");previewZoom.setOnAction(e->redrawPreview());HBox toolbar=new HBox(8,new Label("Vista"),previewZoom);toolbar.setPadding(new Insets(8,12,0,12));StackPane shell=new StackPane(preview);shell.getStyleClass().add("canvas-shell");shell.setPadding(new Insets(28));ScrollPane scroll=new ScrollPane(shell);scroll.setFitToWidth(true);scroll.setFitToHeight(true);scroll.setPannable(true);scroll.getStyleClass().add("editor-scroll");VBox center=new VBox(8,toolbar,scroll);VBox.setVgrow(scroll,Priority.ALWAYS);return center;}
    private void showPreview(Asset asset){previewAsset=asset;redrawPreview();}
    private void redrawPreview(){Asset asset=previewAsset;GraphicsContext g=preview.getGraphicsContext2D();g.setImageSmoothing(false);g.clearRect(0,0,preview.getWidth(),preview.getHeight());if(asset==null||app.image(asset.key)==null){preview.setWidth(1);preview.setHeight(1);return;}int nativeW=app.assetWidth(asset.key),nativeH=app.assetHeight(asset.key);if(nativeW<=0||nativeH<=0){preview.setWidth(1);preview.setHeight(1);return;}int scale=selectedScale(nativeW,nativeH);double w=Math.max(1,Math.rint(nativeW*scale)),h=Math.max(1,Math.rint(nativeH*scale));preview.setWidth(w);preview.setHeight(h);g=preview.getGraphicsContext2D();g.setImageSmoothing(false);g.clearRect(0,0,w,h);app.drawAsset(g,asset.key,0,0,w,h);}
    private int selectedScale(int width,int height){String value=previewZoom.getValue();if(value!=null&&!value.startsWith("Auto")){try{return Integer.parseInt(value.replace("×",""));}catch(Exception ignored){}}int scale=1;while(scale<16&&width*scale*2<=PREVIEW_LIMIT&&height*scale*2<=PREVIEW_LIMIT)scale*=2;return scale;}
    private Node right(){tiles.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);VBox box=new VBox(8,title("TILES"),tiles,tileInspector);box.getStyleClass().add("side-panel");box.setPadding(new Insets(12));box.setPrefWidth(390);VBox.setVgrow(tiles,Priority.ALWAYS);tiles.getSelectionModel().selectedItemProperty().addListener((o,a,b)->rebuildInspector());Button add=new Button("＋ Tile");add.setOnAction(e->{int id=app.project().nextTileId();TileDef t=new TileDef(id,"Tile "+id,new java.awt.Color(80,88,104),true,"");app.project().getTiles().put(id,t);app.changed();refresh();tiles.getSelectionModel().select(t);});box.getChildren().addAll(add,hint("Selecciona varios tiles con Ctrl/Shift. Copiar/pegar duplica sus definiciones."));return box;}

    private void refresh(){Asset selectedAsset=assets.getSelectionModel().getSelectedItem();TileDef selectedTile=tiles.getSelectionModel().getSelectedItem();FontAsset selectedFont=fonts.getSelectionModel().getSelectedItem();assets.setItems(FXCollections.observableArrayList(app.project().getAssets().values()));tiles.setItems(FXCollections.observableArrayList(app.project().getTiles().values()));fonts.setItems(FXCollections.observableArrayList(app.project().getFonts().values()));if(selectedAsset!=null)assets.getSelectionModel().select(app.project().getAssets().get(selectedAsset.key));else if(!assets.getItems().isEmpty())assets.getSelectionModel().selectFirst();if(selectedTile!=null)tiles.getSelectionModel().select(app.project().getTiles().get(selectedTile.id));else if(!tiles.getItems().isEmpty())tiles.getSelectionModel().selectFirst();if(selectedFont!=null)fonts.getSelectionModel().select(app.project().getFonts().get(selectedFont.key));regionButton.setDisable(assets.getSelectionModel().getSelectedItem()==null);rebuildInspector();}
    private void refreshAssets(String selectKey){assets.setItems(FXCollections.observableArrayList(app.project().getAssets().values()));Asset asset=app.project().getAssets().get(selectKey);if(asset!=null)assets.getSelectionModel().select(asset);showPreview(asset);regionButton.setDisable(asset==null);rebuildInspector();}
    private void rebuildInspector(){tileInspector.getChildren().clear();TileDef t=tiles.getSelectionModel().getSelectedItem();if(t==null)return;TextField name=new TextField(t.name);CheckBox walk=new CheckBox("Transitable");walk.setSelected(t.walkable);ColorPicker color=new ColorPicker(Color.rgb(t.color.getRed(),t.color.getGreen(),t.color.getBlue(),t.color.getAlpha()/255.0));ComboBox<String>sprite=new ComboBox<>();sprite.getItems().add("(sin imagen)");sprite.getItems().addAll(app.project().getDrawableAssetKeys());sprite.setValue(t.assetKey.isBlank()?"(sin imagen)":t.assetKey);Runnable apply=()->{t.name=name.getText().isBlank()?"Tile "+t.id:name.getText();t.walkable=walk.isSelected();Color c=color.getValue();t.color=new java.awt.Color((float)c.getRed(),(float)c.getGreen(),(float)c.getBlue(),(float)c.getOpacity());t.assetKey="(sin imagen)".equals(sprite.getValue())?"":sprite.getValue();app.changed();tiles.refresh();};name.setOnAction(e->apply.run());name.focusedProperty().addListener((o,a,b)->{if(!b)apply.run();});walk.setOnAction(e->apply.run());color.setOnAction(e->apply.run());sprite.setOnAction(e->apply.run());GridPane form=form();row(form,0,"Nombre",name);row(form,1,"Sprite/región",sprite);form.add(walk,1,2);form.add(color,1,3);tileInspector.getChildren().addAll(form,hint("El tile referencia una imagen completa o una región virtual. El render usa nearest-neighbor."));}

    private void importAssets(){FileChooser fc=chooser("Importar gráficos");List<java.io.File>files=fc.showOpenMultipleDialog(app.owner());if(files==null)return;String last=null;for(java.io.File f:files){try{String key=uniqueAsset(f.getName());app.project().getAssets().put(key,new Asset(key,f.getName(),Files.readAllBytes(f.toPath())));last=key;}catch(Exception ex){app.error("No se pudo importar "+f.getName(),ex.getMessage());}}if(last!=null){app.changed();refreshAssets(last);app.status("Imagen importada completa. Para hojas usa 'Importar spritesheet'.");}}
    private void importSpritesheet(){FileChooser fc=chooser("Importar spritesheet");java.io.File file=fc.showOpenDialog(app.owner());if(file==null)return;try{byte[]data=Files.readAllBytes(file.toPath());String sourceKey=uniqueAsset(file.getName());Asset source=new Asset(sourceKey,file.getName(),data,true);if(source.image()==null){app.error("Spritesheet inválida","El archivo no pudo decodificarse como imagen.");return;}javafx.scene.image.Image image=new javafx.scene.image.Image(new ByteArrayInputStream(data),0,0,true,false);SpritesheetSliceDialog.show(app.owner(),source,image,regions->{if(regions==null||regions.isEmpty())return;app.project().getAssets().put(source.key,source);List<String>added=new ArrayList<>();for(Asset r:regions){String key=uniqueAsset(r.key);Asset region=new Asset(key,key,source.key,r.regionX,r.regionY,r.regionWidth,r.regionHeight);app.project().getAssets().put(key,region);added.add(key);}app.changed();refreshAssets(added.getFirst());app.status("Spritesheet registrada una vez con "+added.size()+" regiones virtuales.");});}catch(Exception ex){app.error("No se pudo importar la spritesheet",ex.getMessage());}}
    private void defineRegionsForSelected(){Asset selected=assets.getSelectionModel().getSelectedItem();Asset source=sourceFor(selected);if(source==null||source.image()==null)return;javafx.scene.image.Image image=app.image(source.key);if(image==null)return;SpritesheetSliceDialog.show(app.owner(),source,image,regions->{if(regions==null||regions.isEmpty())return;List<String>added=new ArrayList<>();if(selected==source&&source.data!=null&&!source.sourceOnly)source.sourceOnly=true;for(Asset r:regions){String key=uniqueAsset(r.key);Asset region=new Asset(key,key,source.key,r.regionX,r.regionY,r.regionWidth,r.regionHeight);app.project().getAssets().put(key,region);added.add(key);}app.changed();refreshAssets(added.getFirst());app.status("Añadidas "+added.size()+" regiones virtuales; la textura no se duplicó.");});}
    private void importFont(){FileChooser fc=new FileChooser();fc.setTitle("Importar fuente");fc.getExtensionFilters().add(new FileChooser.ExtensionFilter("Fuentes TrueType/OpenType","*.ttf","*.otf"));java.io.File f=fc.showOpenDialog(app.owner());if(f==null)return;try{byte[]data=Files.readAllBytes(f.toPath());if(Font.loadFont(new ByteArrayInputStream(data),16)==null){app.error("Fuente inválida","JavaFX no pudo cargarla.");return;}String key=uniqueFont(f.getName());app.project().getFonts().put(key,new FontAsset(key,f.getName(),data));app.changed();refresh();fonts.getSelectionModel().select(app.project().getFonts().get(key));}catch(Exception ex){app.error("No se pudo importar la fuente",ex.getMessage());}}

    private void copyContext(){if(fonts.isFocused()){fontClipboard=fonts.getSelectionModel().getSelectedItems().stream().map(FontAsset::copy).toList();app.status(fontClipboard.size()+" fuente(s) copiadas.");return;}if(tiles.isFocused()){tileClipboard=tiles.getSelectionModel().getSelectedItems().stream().map(TileDef::copy).toList();app.status(tileClipboard.size()+" tile(s) copiados.");return;}assetClipboard=assets.getSelectionModel().getSelectedItems().stream().map(Asset::copy).toList();app.status(assetClipboard.size()+" asset(s) copiados.");}
    private void pasteContext(){if(fonts.isFocused()&&!fontClipboard.isEmpty()){for(FontAsset f:fontClipboard){String key=uniqueFont(f.key);app.project().getFonts().put(key,new FontAsset(key,f.sourceName,f.data==null?null:f.data.clone()));}app.changed();refresh();return;}if(tiles.isFocused()&&!tileClipboard.isEmpty()){for(TileDef t:tileClipboard){int id=app.project().nextTileId();app.project().getTiles().put(id,new TileDef(id,t.name+" copia",t.color,t.walkable,t.assetKey));}app.changed();refresh();return;}if(assetClipboard.isEmpty())return;Map<String,String>mapping=new HashMap<>();for(Asset a:assetClipboard)if(!a.isRegion()){String key=uniqueAsset(a.key);mapping.put(a.key,key);app.project().getAssets().put(key,new Asset(key,a.sourceName,a.data==null?null:a.data.clone(),a.sourceOnly));}for(Asset a:assetClipboard)if(a.isRegion()){String source=mapping.getOrDefault(a.sourceAssetKey,a.sourceAssetKey);String key=uniqueAsset(a.key);app.project().getAssets().put(key,new Asset(key,a.sourceName,source,a.regionX,a.regionY,a.regionWidth,a.regionHeight));}app.changed();refresh();}
    private void deleteContext(){if(fonts.isFocused()){deleteFonts();return;}if(tiles.isFocused()){deleteTiles();return;}deleteAssets();}
    private void deleteFonts(){List<FontAsset>selected=List.copyOf(fonts.getSelectionModel().getSelectedItems());if(selected.isEmpty())return;Set<String>keys=new HashSet<>();selected.forEach(f->keys.add(f.key));for(var m:app.project().getMenus().values()){if(keys.contains(m.titleFontKey))m.titleFontKey="";for(var b:m.buttons)if(keys.contains(b.fontKey))b.fontKey="";}keys.forEach(app.project().getFonts()::remove);app.changed();refresh();}
    private void deleteTiles(){List<TileDef>selected=List.copyOf(tiles.getSelectionModel().getSelectedItems());if(selected.isEmpty())return;Set<Integer>ids=new HashSet<>();selected.forEach(t->ids.add(t.id));for(var level:app.project().getLevels().values())for(var layer:level.tileLayers){int[]cells=layer.cells();for(int i=0;i<cells.length;i++)if(ids.contains(cells[i]))cells[i]=-1;}ids.forEach(app.project().getTiles()::remove);app.changed();refresh();}
    private void deleteAssets(){List<Asset>selected=List.copyOf(assets.getSelectionModel().getSelectedItems());if(selected.isEmpty())return;Set<String>keys=new LinkedHashSet<>();selected.forEach(a->keys.add(a.key));for(Asset a:selected)if(!a.isRegion()){for(Asset r:app.project().getAssets().values())if(r.isRegion()&&r.sourceAssetKey.equals(a.key)&&!keys.contains(r.key)){app.status("No se eliminó '"+a.sourceName+"': aún tiene regiones virtuales asociadas.");return;}}for(String key:keys)clearAssetReferences(key);keys.forEach(app.project().getAssets()::remove);app.changed();refresh();}
    private void clearAssetReferences(String key){for(TileDef t:app.project().getTiles().values())if(t.assetKey.equals(key))t.assetKey="";for(var l:app.project().getLevels().values()){if(l.backgroundAssetKey.equals(key))l.backgroundAssetKey="";for(var e:l.entities)if(e.assetKey.equals(key))e.assetKey="";}for(var m:app.project().getMenus().values()){if(m.backgroundAssetKey.equals(key))m.backgroundAssetKey="";if(m.titleAssetKey.equals(key))m.titleAssetKey="";for(var b:m.buttons){if(b.assetKey.equals(key))b.assetKey="";if(b.hoverAssetKey.equals(key))b.hoverAssetKey="";}}}

    private Asset sourceFor(Asset asset){if(asset==null)return null;if(asset.isRegion())return app.project().getAssets().get(asset.sourceAssetKey);return asset.data==null?null:asset;}private FileChooser chooser(String title){FileChooser fc=new FileChooser();fc.setTitle(title);fc.getExtensionFilters().add(new FileChooser.ExtensionFilter("Imágenes","*.png","*.jpg","*.jpeg","*.gif"));return fc;}private String uniqueAsset(String base){String clean=base.replaceAll("[^A-Za-z0-9._-]","_");String key=clean;int n=2;while(app.project().getAssets().containsKey(key))key=n+++"_"+clean;return key;}private String uniqueFont(String base){String clean=base.replaceAll("[^A-Za-z0-9._-]","_");String key=clean;int n=2;while(app.project().getFonts().containsKey(key))key=n+++"_"+clean;return key;}
    private static Label hint(String text){Label l=new Label(text);l.getStyleClass().add("muted");l.setWrapText(true);return l;}private static Label title(String text){Label l=new Label(text);l.getStyleClass().add("panel-title");return l;}private static GridPane form(){GridPane g=new GridPane();g.setHgap(8);g.setVgap(7);ColumnConstraints a=new ColumnConstraints();a.setMinWidth(90);ColumnConstraints b=new ColumnConstraints();b.setHgrow(Priority.ALWAYS);g.getColumnConstraints().addAll(a,b);return g;}private static void row(GridPane g,int r,String label,Node n){g.add(new Label(label),0,r);g.add(n,1,r);if(n instanceof Region region)region.setMaxWidth(Double.MAX_VALUE);}
}
