package com.buttclapdev.twogamerl.studio;

import com.buttclapdev.twogamerl.model.GameProject.*;
import com.buttclapdev.twogamerl.runtime.MenuEffects;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.geometry.Rectangle2D;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.stage.FileChooser;
import javafx.util.StringConverter;

import java.io.ByteArrayInputStream;
import java.nio.file.Files;
import java.util.*;

final class MenuEditorPane extends SplitPane {
    private enum Selection { SCREEN,TITLE,BUTTON }
    private record TargetOption(String id,String label){@Override public String toString(){return label;}}
    private record TitleStyle(int x,int y,int width,int height,int fontSize,String fontKey,java.awt.Color color,String asset,MenuAnimation animation,double speed){}

    private final StudioApp app;private final ComboBox<MenuScreen>picker=new ComboBox<>();private final Pane canvas=new Pane();private final VBox inspector=new VBox(10);private Selection selection=Selection.SCREEN;private com.buttclapdev.twogamerl.model.GameProject.MenuButton selectedButton;private MenuScreen screenClipboard;private com.buttclapdev.twogamerl.model.GameProject.MenuButton buttonClipboard;private TitleStyle titleClipboard;

    MenuEditorPane(StudioApp app){this.app=app;getItems().addAll(left(),center(),right());setDividerPositions(.18,.75);EditorShortcuts.install(this,this::copySelection,this::pasteSelection,this::deleteSelection);refresh();}

    private Node left(){VBox box=new VBox(8,title("PANTALLAS"),picker);box.getStyleClass().add("side-panel");box.setPadding(new Insets(12));box.setPrefWidth(260);picker.setMaxWidth(Double.MAX_VALUE);picker.setOnAction(e->{selection=Selection.SCREEN;selectedButton=null;render();rebuildInspector();});Button add=new Button("＋ Pantalla"),remove=new Button("Eliminar pantalla"),addButton=new Button("＋ Botón"),font=new Button("Importar fuente…");remove.getStyleClass().add("danger-button");add.setOnAction(e->addMenu());remove.setOnAction(e->removeMenu());addButton.setOnAction(e->addButton());font.setOnAction(e->importFont());font.setMaxWidth(Double.MAX_VALUE);box.getChildren().addAll(new HBox(6,add,remove),new Separator(),title("ELEMENTOS"),addButton,new Separator(),title("FUENTES"),font,hint("TTF/OTF se guardan dentro del proyecto y pueden asignarse al título o a cada botón."),new Separator(),hint("Ctrl+C / Ctrl+V duplican pantalla, título o botón. Supr elimina la selección cuando corresponda."));return box;}
    private Node center(){canvas.getStyleClass().add("menu-canvas");canvas.setFocusTraversable(true);canvas.setOnMousePressed(e->{canvas.requestFocus();if(e.getTarget()==canvas){selection=Selection.SCREEN;selectedButton=null;rebuildInspector();render();}});StackPane shell=new StackPane(canvas);shell.setPadding(new Insets(35));shell.getStyleClass().add("canvas-shell");ScrollPane scroll=new ScrollPane(shell);scroll.setFitToWidth(true);scroll.setFitToHeight(true);scroll.setPannable(true);return scroll;}
    private Node right(){ScrollPane scroll=new ScrollPane(inspector);scroll.setFitToWidth(true);scroll.getStyleClass().add("editor-scroll");inspector.getStyleClass().add("side-panel");inspector.setPadding(new Insets(12));inspector.setPrefWidth(405);return scroll;}
    private void refresh(){MenuScreen before=picker.getValue();picker.setItems(FXCollections.observableArrayList(app.project().getMenus().values()));if(before!=null&&app.project().getMenus().containsKey(before.id))picker.setValue(app.project().getMenus().get(before.id));else if(!picker.getItems().isEmpty()){MenuScreen start=app.project().getMenus().get(app.project().getStartMenu());picker.setValue(start==null?picker.getItems().getFirst():start);}selection=Selection.SCREEN;selectedButton=null;render();rebuildInspector();}

    private void render(){MenuScreen m=picker.getValue();canvas.getChildren().clear();if(m==null)return;canvas.setPrefSize(m.canvasWidth,m.canvasHeight);canvas.setMinSize(m.canvasWidth,m.canvasHeight);canvas.setMaxSize(m.canvasWidth,m.canvasHeight);java.awt.Color bg=m.background;canvas.setStyle(String.format(Locale.ROOT,"-fx-background-color:rgb(%d,%d,%d);",bg.getRed(),bg.getGreen(),bg.getBlue()));if(!m.backgroundAssetKey.isBlank()){ImageView iv=assetImageView(m.backgroundAssetKey,m.canvasWidth,m.canvasHeight);if(iv!=null){iv.setMouseTransparent(true);canvas.getChildren().add(iv);}}Node titleNode=buildTitleNode(m);titleNode.setLayoutX(m.titleX);titleNode.setLayoutY(m.titleY);installTitleDrag(titleNode,m);canvas.getChildren().add(titleNode);for(com.buttclapdev.twogamerl.model.GameProject.MenuButton def:m.buttons){Node node=buildButtonNode(def);node.setLayoutX(def.x);node.setLayoutY(def.y);installButtonDrag(node,def,m);canvas.getChildren().add(node);}}
    private ImageView assetImageView(String key,double width,double height){Image image=app.image(key);Asset asset=app.project().getAssets().get(key);if(image==null||asset==null)return null;ImageView iv=new ImageView(image);iv.setSmooth(false);iv.setCache(false);iv.setPreserveRatio(false);iv.setFitWidth(Math.max(1,Math.rint(width)));iv.setFitHeight(Math.max(1,Math.rint(height)));if(asset.isRegion())iv.setViewport(new Rectangle2D(asset.regionX,asset.regionY,asset.regionWidth,asset.regionHeight));return iv;}
    private void configureImageView(ImageView iv,String key){Image image=app.image(key);Asset asset=app.project().getAssets().get(key);if(iv==null||image==null||asset==null)return;iv.setImage(image);iv.setSmooth(false);iv.setCache(false);iv.setViewport(asset.isRegion()?new Rectangle2D(asset.regionX,asset.regionY,asset.regionWidth,asset.regionHeight):null);}
    private Font projectFont(String key,double size){if(key==null||key.isBlank())return Font.font(Math.max(8,size));FontAsset a=app.project().getFonts().get(key);if(a==null||a.data==null)return Font.font(Math.max(8,size));try{Font f=Font.loadFont(new ByteArrayInputStream(a.data),Math.max(8,size));return f==null?Font.font(Math.max(8,size)):f;}catch(Exception e){return Font.font(Math.max(8,size));}}
    private Node buildTitleNode(MenuScreen m){StackPane content=new StackPane();content.setPrefSize(m.titleWidth,m.titleHeight);content.setMinSize(m.titleWidth,m.titleHeight);content.setMaxSize(m.titleWidth,m.titleHeight);if(!m.titleAssetKey.isBlank()){ImageView iv=assetImageView(m.titleAssetKey,m.titleWidth,m.titleHeight);if(iv!=null)content.getChildren().add(iv);}if(m.title!=null&&!m.title.isBlank()){Label label=new Label(m.title);label.setFont(projectFont(m.titleFontKey,m.titleFontSize));label.setTextFill(fx(m.titleColor));label.setWrapText(true);label.setAlignment(Pos.CENTER);label.setMaxSize(Double.MAX_VALUE,Double.MAX_VALUE);content.getChildren().add(label);}if(selection==Selection.TITLE)content.setStyle("-fx-border-color:#52d3ff;-fx-border-width:2;");return MenuEffects.decorate(content,m.titleAnimation,m.titleAnimationSpeed,MenuHoverEffect.NONE);}
    private Node buildButtonNode(com.buttclapdev.twogamerl.model.GameProject.MenuButton def){StackPane content=new StackPane();content.setPrefSize(def.width,def.height);content.setMinSize(def.width,def.height);content.setMaxSize(def.width,def.height);ImageView iv=def.assetKey.isBlank()?null:assetImageView(def.assetKey,def.width,def.height);if(iv!=null)content.getChildren().add(iv);else{java.awt.Color c=def.backgroundColor;content.setStyle(String.format(Locale.ROOT,"-fx-background-color:rgba(%d,%d,%d,%.3f);-fx-background-radius:7;-fx-border-color:#4b6a84;-fx-border-radius:7;",c.getRed(),c.getGreen(),c.getBlue(),c.getAlpha()/255.0));}Label label=new Label(def.text);label.setFont(projectFont(def.fontKey,def.fontSize));label.setTextFill(fx(def.textColor));label.setMouseTransparent(true);content.getChildren().add(label);if(iv!=null&&!def.hoverAssetKey.isBlank()){content.setOnMouseEntered(e->configureImageView(iv,def.hoverAssetKey));content.setOnMouseExited(e->configureImageView(iv,def.assetKey));}if(selection==Selection.BUTTON&&selectedButton==def)content.setStyle(content.getStyle()+";-fx-border-color:#52d3ff;-fx-border-width:2;");return MenuEffects.decorate(content,def.animation,def.animationSpeed,def.hoverEffect);}
    private void installTitleDrag(Node node,MenuScreen m){double[]drag=new double[2];node.setOnMousePressed(e->{selection=Selection.TITLE;selectedButton=null;drag[0]=e.getX();drag[1]=e.getY();rebuildInspector();render();e.consume();});node.setOnMouseDragged(e->{double bx=canvas.localToScene(0,0).getX(),by=canvas.localToScene(0,0).getY();m.titleX=clamp((int)Math.round(e.getSceneX()-bx-drag[0]),0,m.canvasWidth-m.titleWidth);m.titleY=clamp((int)Math.round(e.getSceneY()-by-drag[1]),0,m.canvasHeight-m.titleHeight);app.changed();render();e.consume();});}
    private void installButtonDrag(Node node,com.buttclapdev.twogamerl.model.GameProject.MenuButton def,MenuScreen m){double[]offset=new double[2];node.setOnMousePressed(e->{selection=Selection.BUTTON;selectedButton=def;offset[0]=e.getX();offset[1]=e.getY();rebuildInspector();render();e.consume();});node.setOnMouseDragged(e->{double bx=canvas.localToScene(0,0).getX(),by=canvas.localToScene(0,0).getY();def.x=clamp((int)Math.round(e.getSceneX()-bx-offset[0]),0,m.canvasWidth-def.width);def.y=clamp((int)Math.round(e.getSceneY()-by-offset[1]),0,m.canvasHeight-def.height);app.changed();render();e.consume();});}

    private void rebuildInspector(){inspector.getChildren().clear();MenuScreen m=picker.getValue();if(m==null){inspector.getChildren().add(new Label("No hay menú."));return;}switch(selection){case SCREEN->screenInspector(m);case TITLE->titleInspector(m);case BUTTON->buttonInspector(m,selectedButton);}}
    private void screenInspector(MenuScreen m){TextField screenName=new TextField(m.title);ColorPicker background=pickerColor(m.background);ComboBox<String>backgroundSprite=assetPicker(m.backgroundAssetKey);TextField width=new TextField(Integer.toString(m.canvasWidth)),height=new TextField(Integer.toString(m.canvasHeight));CheckBox initial=new CheckBox("Pantalla inicial");initial.setSelected(m.id.equals(app.project().getStartMenu()));Runnable apply=()->{m.title=screenName.getText();m.background=awt(background.getValue());m.backgroundAssetKey=assetValue(backgroundSprite);m.canvasWidth=clamp(parseInt(width,m.canvasWidth),320,1920);m.canvasHeight=clamp(parseInt(height,m.canvasHeight),240,1080);if(initial.isSelected())app.project().setStartMenu(m.id);app.changed();render();};bind(screenName,apply);bind(width,apply);bind(height,apply);background.setOnAction(e->apply.run());backgroundSprite.setOnAction(e->apply.run());initial.setOnAction(e->apply.run());GridPane form=form();row(form,0,"Nombre/título",screenName);row(form,1,"Fondo",background);row(form,2,"Sprite fondo",backgroundSprite);row(form,3,"Ancho",width);row(form,4,"Alto",height);inspector.getChildren().addAll(title("PANTALLA · "+m.id),form,initial,hint("Los destinos de botones se eligen por nombre; los IDs quedan internos."));}
    private void titleInspector(MenuScreen m){TextField text=new TextField(m.title),x=num(m.titleX),y=num(m.titleY),w=num(m.titleWidth),h=num(m.titleHeight),fontSize=num(m.titleFontSize),speed=new TextField(format(m.titleAnimationSpeed));ComboBox<String>font=fontPicker(m.titleFontKey);ColorPicker color=pickerColor(m.titleColor);ComboBox<String>sprite=assetPicker(m.titleAssetKey);ComboBox<MenuAnimation>animation=new ComboBox<>(FXCollections.observableArrayList(MenuAnimation.values()));animation.setValue(m.titleAnimation);Runnable apply=()->{m.title=text.getText();m.titleX=parseInt(x,m.titleX);m.titleY=parseInt(y,m.titleY);m.titleWidth=Math.max(1,parseInt(w,m.titleWidth));m.titleHeight=Math.max(1,parseInt(h,m.titleHeight));m.titleFontSize=Math.max(8,parseInt(fontSize,m.titleFontSize));m.titleFontKey=fontValue(font);m.titleColor=awt(color.getValue());m.titleAssetKey=assetValue(sprite);m.titleAnimation=animation.getValue();m.titleAnimationSpeed=Math.max(.2,parseDouble(speed,m.titleAnimationSpeed));app.changed();render();};for(TextField f:new TextField[]{text,x,y,w,h,fontSize,speed})bind(f,apply);font.setOnAction(e->apply.run());color.setOnAction(e->apply.run());sprite.setOnAction(e->apply.run());animation.setOnAction(e->apply.run());GridPane form=form();row(form,0,"Texto",text);row(form,1,"X",x);row(form,2,"Y",y);row(form,3,"Ancho",w);row(form,4,"Alto",h);row(form,5,"Fuente",font);row(form,6,"Tamaño",fontSize);row(form,7,"Color",color);row(form,8,"Sprite/logo",sprite);row(form,9,"Animación",animation);row(form,10,"Velocidad",speed);inspector.getChildren().addAll(title("TÍTULO"),form,hint("Las fuentes importadas viajan dentro del proyecto y del juego exportado."));}
    private void buttonInspector(MenuScreen m,com.buttclapdev.twogamerl.model.GameProject.MenuButton b){if(b==null){selection=Selection.SCREEN;screenInspector(m);return;}TextField text=new TextField(b.text),x=num(b.x),y=num(b.y),w=num(b.width),h=num(b.height),fontSize=num(b.fontSize),speed=new TextField(format(b.animationSpeed));ComboBox<String>font=fontPicker(b.fontKey);ComboBox<MenuAction>action=actionPicker(b.action);ComboBox<TargetOption>target=new ComboBox<>();target.setMaxWidth(Double.MAX_VALUE);ComboBox<String>sprite=assetPicker(b.assetKey),hoverSprite=assetPicker(b.hoverAssetKey);ColorPicker textColor=pickerColor(b.textColor),bgColor=pickerColor(b.backgroundColor);ComboBox<MenuAnimation>animation=new ComboBox<>(FXCollections.observableArrayList(MenuAnimation.values()));animation.setValue(b.animation);ComboBox<MenuHoverEffect>hover=new ComboBox<>(FXCollections.observableArrayList(MenuHoverEffect.values()));hover.setValue(b.hoverEffect);Runnable apply=()->{b.text=text.getText();b.x=parseInt(x,b.x);b.y=parseInt(y,b.y);b.width=Math.max(1,parseInt(w,b.width));b.height=Math.max(1,parseInt(h,b.height));b.fontSize=Math.max(8,parseInt(fontSize,b.fontSize));b.fontKey=fontValue(font);b.action=action.getValue();TargetOption selected=target.getValue();b.target=selected==null?"":selected.id();b.assetKey=assetValue(sprite);b.hoverAssetKey=assetValue(hoverSprite);b.textColor=awt(textColor.getValue());b.backgroundColor=awt(bgColor.getValue());b.animation=animation.getValue();b.hoverEffect=hover.getValue();b.animationSpeed=Math.max(.2,parseDouble(speed,b.animationSpeed));app.changed();render();};for(TextField f:new TextField[]{text,x,y,w,h,fontSize,speed})bind(f,apply);font.setOnAction(e->apply.run());action.setOnAction(e->{String old=b.target;b.action=action.getValue();populateTargets(target,b.action,old);apply.run();});target.setOnAction(e->apply.run());sprite.setOnAction(e->apply.run());hoverSprite.setOnAction(e->apply.run());textColor.setOnAction(e->apply.run());bgColor.setOnAction(e->apply.run());animation.setOnAction(e->apply.run());hover.setOnAction(e->apply.run());populateTargets(target,b.action,b.target);Button delete=new Button("Eliminar botón");delete.getStyleClass().add("danger-button");delete.setOnAction(e->deleteButton(m,b));GridPane form=form();row(form,0,"Texto",text);row(form,1,"X",x);row(form,2,"Y",y);row(form,3,"Ancho",w);row(form,4,"Alto",h);row(form,5,"Fuente",font);row(form,6,"Tamaño",fontSize);row(form,7,"Color texto",textColor);row(form,8,"Color base",bgColor);row(form,9,"Sprite",sprite);row(form,10,"Sprite hover",hoverSprite);row(form,11,"Acción",action);row(form,12,"Destino",target);row(form,13,"Animación",animation);row(form,14,"Hover",hover);row(form,15,"Velocidad",speed);inspector.getChildren().addAll(title("BOTÓN"),form,delete,hint("INICIAR JUEGO muestra las escenas creadas. ABRIR MENÚ muestra las pantallas creadas."));}

    private ComboBox<MenuAction>actionPicker(MenuAction value){ComboBox<MenuAction>box=new ComboBox<>(FXCollections.observableArrayList(MenuAction.values()));box.setValue(value);box.setMaxWidth(Double.MAX_VALUE);box.setConverter(new StringConverter<>(){@Override public String toString(MenuAction a){if(a==null)return"";return switch(a){case START_GAME->"INICIAR JUEGO / ESCENA";case OPEN_MENU->"ABRIR MENÚ";case EXIT->"SALIR";};}@Override public MenuAction fromString(String s){return value;}});return box;}
    private void populateTargets(ComboBox<TargetOption>box,MenuAction action,String current){box.getItems().clear();if(action==MenuAction.EXIT){box.setDisable(true);box.setValue(null);return;}box.setDisable(false);if(action==MenuAction.START_GAME){for(Level level:app.project().getLevels().values())box.getItems().add(new TargetOption(level.id,level.name));}else{for(MenuScreen menu:app.project().getMenus().values())box.getItems().add(new TargetOption(menu.id,menu.title));}TargetOption selected=box.getItems().stream().filter(o->o.id().equals(current)).findFirst().orElse(null);if(selected==null&&!box.getItems().isEmpty())selected=action==MenuAction.START_GAME?box.getItems().stream().filter(o->o.id().equals(app.project().getStartLevel())).findFirst().orElse(box.getItems().getFirst()):box.getItems().getFirst();box.setValue(selected);}

    private void addMenu(){TextInputDialog d=new TextInputDialog("Nueva pantalla");d.setHeaderText("Nombre de la pantalla");d.showAndWait().ifPresent(name->{if(name.isBlank())return;String id=slug(name,app.project().getMenus().keySet());MenuScreen m=new MenuScreen(id,name.trim());app.project().getMenus().put(id,m);app.changed();picker.getItems().add(m);picker.setValue(m);selection=Selection.SCREEN;rebuildInspector();});}
    private void removeMenu(){MenuScreen m=picker.getValue();if(m==null||app.project().getMenus().size()<=1)return;app.project().getMenus().remove(m.id);if(m.id.equals(app.project().getStartMenu()))app.project().setStartMenu(app.project().getMenus().keySet().iterator().next());for(MenuScreen screen:app.project().getMenus().values())for(com.buttclapdev.twogamerl.model.GameProject.MenuButton b:screen.buttons)if(b.action==MenuAction.OPEN_MENU&&b.target.equals(m.id))b.target="";app.changed();refresh();}
    private void addButton(){MenuScreen m=picker.getValue();if(m==null)return;com.buttclapdev.twogamerl.model.GameProject.MenuButton b=new com.buttclapdev.twogamerl.model.GameProject.MenuButton("Botón",Math.max(0,m.canvasWidth/2-100),Math.max(0,m.canvasHeight/2-24),200,48,MenuAction.START_GAME,app.project().getStartLevel());m.buttons.add(b);selectedButton=b;selection=Selection.BUTTON;app.changed();render();rebuildInspector();}
    private void deleteButton(MenuScreen m,com.buttclapdev.twogamerl.model.GameProject.MenuButton b){m.buttons.remove(b);selectedButton=null;selection=Selection.SCREEN;app.changed();render();rebuildInspector();}
    private void importFont(){FileChooser fc=new FileChooser();fc.setTitle("Importar fuente");fc.getExtensionFilters().add(new FileChooser.ExtensionFilter("Fuentes TrueType/OpenType","*.ttf","*.otf"));java.io.File f=fc.showOpenDialog(app.owner());if(f==null)return;try{byte[]data=Files.readAllBytes(f.toPath());Font check=Font.loadFont(new ByteArrayInputStream(data),16);if(check==null){app.error("Fuente inválida","JavaFX no pudo cargar la fuente seleccionada.");return;}String key=uniqueFontKey(f.getName());app.project().getFonts().put(key,new FontAsset(key,f.getName(),data));app.changed();app.status("Fuente importada: "+f.getName());rebuildInspector();render();}catch(Exception ex){app.error("No se pudo importar la fuente",ex.getMessage());}}

    private void copySelection(){MenuScreen m=picker.getValue();if(m==null)return;switch(selection){case SCREEN->{screenClipboard=m.copy();app.status("Pantalla copiada: "+m.title);}case BUTTON->{if(selectedButton!=null){buttonClipboard=selectedButton.copy();app.status("Botón copiado: "+selectedButton.text);}}case TITLE->{titleClipboard=new TitleStyle(m.titleX,m.titleY,m.titleWidth,m.titleHeight,m.titleFontSize,m.titleFontKey,m.titleColor,m.titleAssetKey,m.titleAnimation,m.titleAnimationSpeed);app.status("Estilo del título copiado.");}}}
    private void pasteSelection(){MenuScreen m=picker.getValue();if(m==null)return;switch(selection){case SCREEN->{if(screenClipboard==null)return;String id=slug(screenClipboard.title+" copia",app.project().getMenus().keySet());MenuScreen c=cloneMenu(screenClipboard,id,screenClipboard.title+" copia");app.project().getMenus().put(id,c);app.changed();refresh();picker.setValue(c);}case BUTTON->{if(buttonClipboard==null)return;var c=buttonClipboard.copy();c.x=Math.min(m.canvasWidth-c.width,c.x+16);c.y=Math.min(m.canvasHeight-c.height,c.y+16);m.buttons.add(c);selectedButton=c;selection=Selection.BUTTON;app.changed();render();rebuildInspector();}case TITLE->{if(titleClipboard==null)return;m.titleX=titleClipboard.x;m.titleY=titleClipboard.y;m.titleWidth=titleClipboard.width;m.titleHeight=titleClipboard.height;m.titleFontSize=titleClipboard.fontSize;m.titleFontKey=titleClipboard.fontKey;m.titleColor=titleClipboard.color;m.titleAssetKey=titleClipboard.asset;m.titleAnimation=titleClipboard.animation;m.titleAnimationSpeed=titleClipboard.speed;app.changed();render();rebuildInspector();}}}
    private void deleteSelection(){MenuScreen m=picker.getValue();if(m==null)return;switch(selection){case SCREEN->removeMenu();case BUTTON->{if(selectedButton!=null)deleteButton(m,selectedButton);}case TITLE->{m.title="";m.titleAssetKey="";app.changed();render();rebuildInspector();}}}
    private static MenuScreen cloneMenu(MenuScreen s,String id,String title){MenuScreen c=new MenuScreen(id,title);c.background=s.background;c.titleColor=s.titleColor;c.backgroundAssetKey=s.backgroundAssetKey;c.titleAssetKey=s.titleAssetKey;c.titleFontKey=s.titleFontKey;c.canvasWidth=s.canvasWidth;c.canvasHeight=s.canvasHeight;c.titleX=s.titleX;c.titleY=s.titleY;c.titleWidth=s.titleWidth;c.titleHeight=s.titleHeight;c.titleFontSize=s.titleFontSize;c.titleAnimation=s.titleAnimation;c.titleAnimationSpeed=s.titleAnimationSpeed;for(var b:s.buttons)c.buttons.add(b.copy());return c;}

    private ComboBox<String>assetPicker(String value){ComboBox<String>c=new ComboBox<>();c.getItems().add("(ninguno)");c.getItems().addAll(app.project().getDrawableAssetKeys());c.setValue(value==null||value.isBlank()?"(ninguno)":value);c.setMaxWidth(Double.MAX_VALUE);return c;}private static String assetValue(ComboBox<String>c){return c.getValue()==null||"(ninguno)".equals(c.getValue())?"":c.getValue();}
    private ComboBox<String>fontPicker(String value){ComboBox<String>c=new ComboBox<>();c.getItems().add("(Sistema)");c.getItems().addAll(app.project().getFonts().keySet());c.setValue(value==null||value.isBlank()?"(Sistema)":value);c.setMaxWidth(Double.MAX_VALUE);return c;}private static String fontValue(ComboBox<String>c){return c.getValue()==null||"(Sistema)".equals(c.getValue())?"":c.getValue();}
    private String uniqueFontKey(String base){String clean=base.replaceAll("[^A-Za-z0-9._-]","_");String key=clean;int n=2;while(app.project().getFonts().containsKey(key))key=n+++"_"+clean;return key;}
    private static ColorPicker pickerColor(java.awt.Color c){return new ColorPicker(Color.rgb(c.getRed(),c.getGreen(),c.getBlue(),c.getAlpha()/255.0));}private static java.awt.Color awt(Color c){return new java.awt.Color((float)c.getRed(),(float)c.getGreen(),(float)c.getBlue(),(float)c.getOpacity());}private static Color fx(java.awt.Color c){return Color.rgb(c.getRed(),c.getGreen(),c.getBlue(),c.getAlpha()/255.0);}private static void bind(TextField field,Runnable apply){field.setOnAction(e->apply.run());field.focusedProperty().addListener((o,a,b)->{if(!b)apply.run();});}
    private static TextField num(int n){return new TextField(Integer.toString(n));}private static int parseInt(TextField f,int def){try{return Integer.parseInt(f.getText().trim());}catch(Exception e){return def;}}private static double parseDouble(TextField f,double def){try{return Double.parseDouble(f.getText().trim());}catch(Exception e){return def;}}private static String format(double n){return String.format(Locale.ROOT,"%.2f",n);}private static int clamp(int n,int min,int max){return Math.max(min,Math.min(Math.max(min,max),n));}
    private static Label hint(String text){Label l=new Label(text);l.getStyleClass().add("muted");l.setWrapText(true);return l;}private static Label title(String text){Label l=new Label(text);l.getStyleClass().add("panel-title");return l;}private static GridPane form(){GridPane g=new GridPane();g.setHgap(8);g.setVgap(7);ColumnConstraints a=new ColumnConstraints();a.setMinWidth(100);ColumnConstraints b=new ColumnConstraints();b.setHgrow(Priority.ALWAYS);g.getColumnConstraints().addAll(a,b);return g;}private static void row(GridPane g,int r,String label,Node n){g.add(new Label(label),0,r);g.add(n,1,r);if(n instanceof Region region)region.setMaxWidth(Double.MAX_VALUE);}private static String slug(String name,Collection<String>used){String base=name.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-").replaceAll("(^-|-$)","");if(base.isBlank())base="menu";String id=base;int n=2;while(used.contains(id))id=base+"-"+n++;return id;}
}
