package com.buttclapdev.twogamerl.studio;

import com.buttclapdev.twogamerl.model.GameProject;
import com.buttclapdev.twogamerl.model.GameProject.*;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.VBox;
import javafx.stage.Modality;
import javafx.stage.Stage;

import java.util.*;

/** Global read-only resource browser for project-wide inspection and dependency discovery. */
final class ResourceBrowser222 {
    private record Entry(String type,String key,String name,Object value){@Override public String toString(){return name==null||name.equals(key)?key:key+" — "+name;}}
    private ResourceBrowser222(){}
    static void show(Stage owner,StudioApp app){Stage stage=new Stage();stage.initOwner(owner);stage.initModality(Modality.NONE);stage.setTitle("Navegador global de recursos");TextField search=new TextField();search.setPromptText("Buscar recurso, tipo, ID o nombre…");TreeView<Object>tree=new TreeView<>();tree.setShowRoot(false);TextArea details=new TextArea();details.setEditable(false);details.setWrapText(true);details.setPrefWidth(360);Runnable rebuild=()->build(tree,app.project(),Objects.toString(search.getText(),""));search.textProperty().addListener((o,a,b)->rebuild.run());tree.getSelectionModel().selectedItemProperty().addListener((o,a,b)->details.setText(b!=null&&b.getValue() instanceof Entry e?describe(app.project(),e):""));BorderPane root=new BorderPane();root.setTop(search);root.setCenter(tree);root.setRight(new VBox(details));BorderPane.setMargin(search,new Insets(10));BorderPane.setMargin(tree,new Insets(0,10,10,10));BorderPane.setMargin(details,new Insets(0,10,10,0));Scene scene=new Scene(root,940,650);var css=ResourceBrowser222.class.getResource("/com/buttclapdev/twogamerl/studio.css");if(css!=null)scene.getStylesheets().add(css.toExternalForm());stage.setScene(scene);ThemeManager.apply(scene);rebuild.run();stage.show();}

    private static void build(TreeView<Object>tree,GameProject p,String query){String q=query==null?"":query.trim().toLowerCase(Locale.ROOT);TreeItem<Object>root=new TreeItem<>("Recursos");root.setExpanded(true);LinkedHashMap<String,List<Entry>>groups=new LinkedHashMap<>();for(Asset x:p.getAssets().values())add(groups,"Assets",new Entry("Asset",x.key,x.sourceName,x));for(FontAsset x:p.getFonts().values())add(groups,"Fuentes",new Entry("FontAsset",x.key,x.sourceName,x));for(SoundAsset x:p.getSounds().values())add(groups,"Audio",new Entry("SoundAsset",x.key,x.name,x));for(PrefabDef x:p.getPrefabs().values())add(groups,"Prefabs",new Entry("Prefab",x.key,x.name,x));for(AnimationClip x:p.getAnimationClips().values())add(groups,"Animaciones",new Entry("AnimationClip",x.key,x.name,x));for(AnimatorController x:p.getAnimatorControllers().values())add(groups,"Animator Controllers",new Entry("AnimatorController",x.key,x.name,x));for(TextStyle x:p.getTextStyles().values())add(groups,"TextStyle",new Entry("TextStyle",x.key,x.name,x));for(ParticlePreset x:p.getParticlePresets().values())add(groups,"Partículas",new Entry("ParticlePreset",x.key,x.name,x));for(PaletteAsset x:p.getPalettes().values())add(groups,"Paletas",new Entry("Palette",x.key,x.name,x));for(InputAction x:p.getInputActions().values())add(groups,"Input Map",new Entry("InputAction",x.key,x.name,x));for(Level x:p.getLevels().values())add(groups,"Escenas",new Entry("Scene",x.id,x.name,x));for(MenuScreen x:p.getMenus().values())add(groups,"Menús",new Entry("Menu",x.id,x.title,x));for(var g:groups.entrySet()){TreeItem<Object>folder=new TreeItem<>(g.getKey());folder.setExpanded(true);for(Entry e:g.getValue())if(q.isBlank()||(e.type+" "+e.key+" "+Objects.toString(e.name,"")).toLowerCase(Locale.ROOT).contains(q))folder.getChildren().add(new TreeItem<>(e));if(!folder.getChildren().isEmpty())root.getChildren().add(folder);}tree.setRoot(root);}
    private static void add(Map<String,List<Entry>>groups,String group,Entry e){groups.computeIfAbsent(group,k->new ArrayList<>()).add(e);}
    private static String describe(GameProject p,Entry e){StringBuilder b=new StringBuilder();b.append(e.type).append("\nID: ").append(e.key).append("\nNombre: ").append(Objects.toString(e.name,"")).append("\n\n");Object v=e.value;if(v instanceof Asset a)b.append("Categoría: ").append(a.category).append("\nRegión: ").append(a.isRegion()).append("\nNine-slice: ").append(a.isNineSlice()).append("\nFuente: ").append(a.sourceAssetKey);else if(v instanceof SoundAsset s)b.append("Tipo: ").append(s.category).append("\nVolumen: ").append(s.volume).append("\nLoop: ").append(s.loop);else if(v instanceof ParticlePreset x)b.append("Sprite: ").append(x.assetKey).append("\nRate: ").append(x.rate).append("\nVida: ").append(x.lifetime).append("\nDirección: ").append(x.direction).append("°\nSpread: ").append(x.spread).append("°\nBurst: ").append(x.burst).append("\nLocal space: ").append(x.localSpace);else if(v instanceof PrefabDef x)b.append("Colocación: ").append(x.placement).append("\nPadre: ").append(x.parentPrefab).append("\nTile ID: ").append(x.tileId).append("\nComponentes: ").append(x.template==null?0:x.template.components.size());else if(v instanceof AnimationClip x)b.append("Frames: ").append(x.frames.size()).append("\nDuración: ").append(x.duration()).append(" s\nLoop: ").append(x.loop);else if(v instanceof InputAction x)b.append("Bindings: ").append(String.join(", ",x.bindings)).append("\nDead zone: ").append(x.deadZone);else if(v instanceof Level x)b.append("Tamaño: ").append(x.width).append("×").append(x.height).append("\nEntidades: ").append(x.entities.size()).append("\nCapas: ").append(x.tileLayers.size());b.append("\n\nUsos detectados:\n");List<String>uses=uses(p,e);if(uses.isEmpty())b.append("— Ningún uso directo detectado");else uses.forEach(x->b.append("— ").append(x).append('\n'));return b.toString();}
    private static List<String>uses(GameProject p,Entry e){ArrayList<String>u=new ArrayList<>();String key=e.key;for(Level l:p.getLevels().values()){if(key.equals(l.backgroundAssetKey))u.add("Fondo de escena "+l.name);if(key.equals(l.cameraTarget))u.add("Camera target de "+l.name);for(EntityDef x:l.entities){if(key.equals(x.assetKey))u.add("Entidad "+l.name+" / "+x.name);for(ComponentDef c:x.components)for(var prop:c.properties.entrySet())if(key.equals(prop.getValue()))u.add("Componente "+c.type+" de "+x.name+"."+prop.getKey());if(x.script!=null&&x.script.contains(key))u.add("Script de "+x.name);}}for(PrefabDef x:p.getPrefabs().values()){if(key.equals(x.parentPrefab))u.add("Padre de Prefab "+x.name);if(x.template!=null){if(key.equals(x.template.assetKey))u.add("Sprite de Prefab "+x.name);for(ComponentDef c:x.template.components)if(c.properties.containsValue(key))u.add("Componente "+c.type+" de Prefab "+x.name);}}for(AnimationClip x:p.getAnimationClips().values())if(x.frames.stream().anyMatch(f->key.equals(f.assetKey)))u.add("AnimationClip "+x.name);for(TextStyle x:p.getTextStyles().values())if(key.equals(x.skinAssetKey)||key.equals(x.fontKey))u.add("TextStyle "+x.name);for(ParticlePreset x:p.getParticlePresets().values())if(key.equals(x.assetKey))u.add("ParticlePreset "+x.key);return u.stream().distinct().toList();}
}
