package com.buttclapdev.twogamerl.studio;

import com.buttclapdev.twogamerl.model.GameProject;
import com.buttclapdev.twogamerl.model.AdvancedTileResolver;
import com.buttclapdev.twogamerl.model.GameProject.*;
import com.buttclapdev.twogamerl.script.ScriptProgram;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.*;
import javafx.scene.input.MouseButton;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;

import java.util.*;

final class SceneEditorPane extends SplitPane {
    private enum Tool { SELECT,DRAW,FILL,ERASE,EMPTY_ENTITY }
    private enum Target { SCENE,LAYER,ENTITY,BRUSH }
    private record HierarchyNode(String label,String group,EntityDef entity){@Override public String toString(){return label;}}
    private record RenderPass(int z,Runnable draw){}

    private final StudioApp app;
    private final ComboBox<Level>scenePicker=new ComboBox<>();private final ListView<TileLayer>tileLayers=new ListView<>();private final TreeView<HierarchyNode>hierarchy=new TreeView<>();private final ComboBox<PrefabDef>brushPicker=new ComboBox<>();private final ComboBox<Integer>zoomScale=new ComboBox<>(FXCollections.observableArrayList(1,2,3,4,6,8));private final Label gridInfo=new Label();private final Canvas canvas=new Canvas();
    private final TabPane tabs=new TabPane();private final Tab inspectorTab=new Tab("Inspector"),scriptTab=new Tab("Script");private final VBox inspector=new VBox(10);private final TextArea script=new TextArea();private final Label scriptStatus=new Label();private final Set<String>expandedGroups=new HashSet<>();private final LinkedHashSet<EntityDef>selectedEntities=new LinkedHashSet<>();
    private ToggleButton selectTool,drawTool;private Tool tool=Tool.SELECT;private Target target=Target.SCENE;private EntityDef selected;private TileLayer selectedLayer;private boolean loading,dragging;private double dragX,dragY;private int lastPaintX=Integer.MIN_VALUE,lastPaintY=Integer.MIN_VALUE;private List<EntityDef>entityClipboard=List.of();private TileLayer layerClipboard;private Level sceneClipboard;

    SceneEditorPane(StudioApp app){this.app=app;canvas.getGraphicsContext2D().setImageSmoothing(false);canvas.setFocusTraversable(true);zoomScale.setValue(1);getItems().addAll(leftPane(),centerPane(),rightPane());setDividerPositions(.195,.78);EditorShortcuts.install(this,this::copyContext,this::pasteContext,this::deleteContext);refresh();}

    private Node leftPane(){
        VBox box=new VBox(8);box.getStyleClass().add("side-panel");box.setPadding(new Insets(12));box.setPrefWidth(285);
        scenePicker.setMaxWidth(Double.MAX_VALUE);scenePicker.setOnAction(e->{if(loading)return;selected=null;selectedEntities.clear();target=Target.SCENE;refreshTileLayers(false);refreshHierarchy();resizeCanvas();loadScriptTarget();rebuildInspector();});Button inspectScene=new Button("Propiedades y script"),addScene=new Button("＋ Escena"),removeScene=new Button("Eliminar");inspectScene.setMaxWidth(Double.MAX_VALUE);inspectScene.setOnAction(e->selectSceneTarget());addScene.setOnAction(e->addScene());removeScene.setOnAction(e->removeScene());
        tileLayers.setPrefHeight(155);tileLayers.setCellFactory(v->new ListCell<>(){@Override protected void updateItem(TileLayer l,boolean empty){super.updateItem(l,empty);if(empty||l==null){setText(null);return;}setText(l.name+(l.collision?"  ◼":""));setOpacity(l.visible?1:.5);setStyle(l.locked?"-fx-font-style:italic;":"");}});tileLayers.getSelectionModel().selectedItemProperty().addListener((o,a,b)->{if(loading)return;selectedLayer=b;if(b!=null){target=Target.LAYER;selected=null;selectedEntities.clear();hierarchy.getSelectionModel().clearSelection();loadScriptTarget();rebuildInspector();redraw();}});Button addLayer=new Button("＋ Capa"),deleteLayer=new Button("Eliminar"),back=new Button("Enviar atrás"),front=new Button("Traer delante"),layerSettings=new Button("Capas y matriz de colisiones…");addLayer.setOnAction(e->addTileLayer());deleteLayer.setOnAction(e->deleteTileLayer());back.setOnAction(e->moveTileLayer(-1));front.setOnAction(e->moveTileLayer(1));layerSettings.setMaxWidth(Double.MAX_VALUE);layerSettings.setOnAction(e->LayerSettingsDialog.show(app.owner(),app.project(),()->{refreshTileLayers(true);rebuildInspector();redraw();app.changed();}));
        hierarchy.setShowRoot(false);hierarchy.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);hierarchy.getSelectionModel().getSelectedItems().addListener((javafx.collections.ListChangeListener<TreeItem<HierarchyNode>>)c->{if(loading)return;selectedEntities.clear();for(TreeItem<HierarchyNode>item:hierarchy.getSelectionModel().getSelectedItems())if(item!=null&&item.getValue()!=null&&item.getValue().entity()!=null)selectedEntities.add(item.getValue().entity());selected=selectedEntities.isEmpty()?null:selectedEntities.iterator().next();if(selected!=null){target=Target.ENTITY;selectedLayer=null;tileLayers.getSelectionModel().clearSelection();loadScriptTarget();}redraw();rebuildInspector();});hierarchy.setOnMouseClicked(e->{TreeItem<HierarchyNode>item=hierarchy.getSelectionModel().getSelectedItem();if(e.getClickCount()>=2&&item!=null&&item.getValue().entity()!=null)tabs.getSelectionModel().select(scriptTab);});VBox.setVgrow(hierarchy,Priority.ALWAYS);Button addObject=new Button("＋ Objeto vacío"),removeObject=new Button("Eliminar"),makePrefab=new Button("Crear Prefab");addObject.setOnAction(e->addAtCenter());removeObject.setOnAction(e->removeSelected());makePrefab.setOnAction(e->createPrefabFromSelected());
        box.getChildren().addAll(title("ESCENA"),scenePicker,new HBox(6,addScene,removeScene),inspectScene,new Separator(),title("CAPAS TILEMAP"),tileLayers,new HBox(6,addLayer,deleteLayer),new HBox(6,back,front),layerSettings,muted("Las capas guardan matrices compactas; un suelo de miles de celdas no crea miles de entidades."),new Separator(),title("ENTIDADES DE LA ESCENA"),hierarchy,new HBox(6,addObject,removeObject),makePrefab,muted("Ctrl+C / Ctrl+V duplican. Supr elimina. Ctrl/Shift permiten selección múltiple."));return box;
    }

    private Node centerPane(){ToggleGroup group=new ToggleGroup();selectTool=toolButton("Selección",group,true,Tool.SELECT);drawTool=toolButton("Dibujar",group,false,Tool.DRAW);ToggleButton fill=toolButton("Rellenar",group,false,Tool.FILL),erase=toolButton("Borrar",group,false,Tool.ERASE),empty=toolButton("Objeto",group,false,Tool.EMPTY_ENTITY);brushPicker.setPrefWidth(205);brushPicker.setCellFactory(v->brushCell());brushPicker.setButtonCell(brushCell());brushPicker.setOnAction(e->{if(loading)return;target=Target.BRUSH;selected=null;selectedEntities.clear();selectedLayer=null;loadScriptTarget();rebuildInspector();redraw();});zoomScale.setPrefWidth(62);zoomScale.setButtonCell(scaleCell());zoomScale.setCellFactory(v->scaleCell());zoomScale.valueProperty().addListener((o,a,b)->resizeCanvas());gridInfo.getStyleClass().add("muted");Region spacer=new Region();HBox.setHgrow(spacer,Priority.ALWAYS);HBox tools=new HBox(5,selectTool,drawTool,fill,erase,empty,new Separator(),new Label("Pincel:"),brushPicker,spacer,new Label("Zoom"),zoomScale,gridInfo);tools.setAlignment(Pos.CENTER_LEFT);tools.setPadding(new Insets(6,8,6,8));tools.getStyleClass().add("context-toolbar");StackPane shell=new StackPane(canvas);shell.getStyleClass().add("canvas-shell");shell.setPadding(new Insets(28));ScrollPane scroll=new ScrollPane(shell);scroll.setPannable(true);scroll.getStyleClass().add("editor-scroll");VBox center=new VBox(tools,scroll);VBox.setVgrow(scroll,Priority.ALWAYS);installCanvasHandlers();return center;}
    private ListCell<PrefabDef>brushCell(){return new ListCell<>(){@Override protected void updateItem(PrefabDef p,boolean empty){super.updateItem(p,empty);if(empty||p==null){setText(null);return;}setText(p.name+"  ·  "+effectivePlacement(p));}};}
    private ListCell<Integer>scaleCell(){return new ListCell<>(){@Override protected void updateItem(Integer item,boolean empty){super.updateItem(item,empty);setText(empty||item==null?"":item+"×");}};}
    private ToggleButton toolButton(String text,ToggleGroup group,boolean active,Tool next){ToggleButton b=new ToggleButton(text);b.setToggleGroup(group);b.setSelected(active);b.setOnAction(e->{if(!b.isSelected()){b.setSelected(true);return;}tool=next;lastPaintX=lastPaintY=Integer.MIN_VALUE;if(next==Tool.DRAW||next==Tool.FILL){target=Target.BRUSH;selected=null;selectedEntities.clear();hierarchy.getSelectionModel().clearSelection();loadScriptTarget();rebuildInspector();}app.status(switch(next){case SELECT->"Seleccionar: clic y arrastre sobre entidades.";case DRAW->"Dibujar: el Pincel usa tilemap o Prefab automáticamente.";case FILL->"Rellenar: disponible para Pinceles que usan TILEMAP.";case ERASE->"Borrar: elimina celdas tilemap al arrastrar.";case EMPTY_ENTITY->"Objeto vacío: coloca una entidad sin Prefab.";});redraw();});return b;}

    private Node rightPane(){tabs.setTabClosingPolicy(TabPane.TabClosingPolicy.UNAVAILABLE);tabs.setPrefWidth(380);ScrollPane inspectorScroll=new ScrollPane(inspector);inspectorScroll.setFitToWidth(true);inspectorScroll.getStyleClass().add("editor-scroll");inspectorTab.setContent(inspectorScroll);scriptTab.setContent(scriptPane());tabs.getTabs().addAll(inspectorTab,scriptTab);return tabs;}
    private Node scriptPane(){script.setStyle("-fx-font-family:'Consolas','JetBrains Mono',monospace;-fx-font-size:13px;");script.setWrapText(false);script.textProperty().addListener((o,a,b)->{if(!loading){setTargetScript(b);app.changed();validate(false);}});Button validate=new Button("Validar script"),template=new Button("Insertar plantilla"),tutorial=new Button("Tutorial + API");validate.getStyleClass().add("primary-button");validate.setOnAction(e->validate(true));template.setOnAction(e->script.setText(template()));tutorial.setOnAction(e->ScriptTutorialDialog.show(app.owner(),this::insertTutorialExample));Label help=muted("El Script puede pertenecer a escena, capa, entidad o Prefab/Pincel. El tutorial contiene cada comando, firma, componente y ejemplos WASD/salto.");VBox box=new VBox(8,new HBox(8,validate,template,tutorial),scriptStatus,script,help);box.setPadding(new Insets(12));VBox.setVgrow(script,Priority.ALWAYS);return box;}
    private void insertTutorialExample(String example){if(example==null||example.isBlank())return;int caret=Math.max(0,Math.min(script.getCaretPosition(),script.getLength()));String before=script.getText(0,caret),after=script.getText(caret,script.getLength());String prefix=caret==0?"":before.endsWith("\n\n")?"":before.endsWith("\n")?"\n":"\n\n",suffix=after.isEmpty()?"":after.startsWith("\n\n")?"":after.startsWith("\n")?"\n":"\n\n";script.insertText(caret,prefix+example.strip()+suffix);tabs.getSelectionModel().select(scriptTab);script.requestFocus();}

    private void installCanvasHandlers(){canvas.setOnMousePressed(e->{canvas.requestFocus();Level l=level();if(l==null)return;double cell=cellSize(),wx=e.getX()/cell,wy=e.getY()/cell;int cx=cellX(e.getX()),cy=cellY(e.getY());if(e.getButton()==MouseButton.SECONDARY){if(tool==Tool.DRAW||tool==Tool.ERASE)eraseTile(cx,cy);return;}switch(tool){case SELECT->selectAt(wx,wy,e);case DRAW->paintBrush(cx,cy);case FILL->fillBrush(cx,cy);case ERASE->eraseTile(cx,cy);case EMPTY_ENTITY->{EntityDef created=createEmpty(wx,wy);selectCreated(created);tool=Tool.SELECT;selectTool.setSelected(true);}}});canvas.setOnMouseDragged(e->{double cell=cellSize(),wx=e.getX()/cell,wy=e.getY()/cell;if(tool==Tool.SELECT&&dragging&&selected!=null){double nx=snap(wx-dragX),ny=snap(wy-dragY),dx=nx-selected.x,dy=ny-selected.y;for(EntityDef ent:selectedEntities){ent.x=snap(ent.x+dx);ent.y=snap(ent.y+dy);}app.changed();redraw();}else if(tool==Tool.DRAW)paintBrush(cellX(e.getX()),cellY(e.getY()));else if(tool==Tool.ERASE)eraseTile(cellX(e.getX()),cellY(e.getY()));});canvas.setOnMouseReleased(e->{dragging=false;lastPaintX=lastPaintY=Integer.MIN_VALUE;if(selected!=null)rebuildInspector();});}
    private void selectAt(double wx,double wy,javafx.scene.input.MouseEvent e){EntityDef hit=hit(wx,wy);if(e.isControlDown()){if(hit!=null){if(selectedEntities.contains(hit))selectedEntities.remove(hit);else selectedEntities.add(hit);selected=selectedEntities.isEmpty()?null:selectedEntities.iterator().next();selectHierarchySet();}}else{selectedEntities.clear();if(hit!=null)selectedEntities.add(hit);selected=hit;selectHierarchySet();}if(selected!=null){target=Target.ENTITY;selectedLayer=null;tileLayers.getSelectionModel().clearSelection();dragging=true;dragX=wx-selected.x;dragY=wy-selected.y;if(e.getClickCount()>=2)tabs.getSelectionModel().select(scriptTab);}loadScriptTarget();rebuildInspector();redraw();}

    private void paintBrush(int x,int y){if(x==lastPaintX&&y==lastPaintY)return;lastPaintX=x;lastPaintY=y;Level l=level();PrefabDef p=brushPicker.getValue();if(l==null||p==null||x<0||y<0||x>=l.width||y>=l.height)return;if(useTilemap(p)){TileLayer layer=activeTileLayer();if(layer==null){app.status("Selecciona o crea una capa tilemap.");return;}if(layer.locked){app.status("La capa está bloqueada.");return;}ensureTile(p);layer.set(x,y,p.tileId);app.changed();redraw();}else{EntityDef e=instantiatePrefab(p,x,y);l.entities.add(e);app.changed();refreshHierarchy();redraw();}}
    private void fillBrush(int x,int y){Level l=level();PrefabDef p=brushPicker.getValue();TileLayer layer=activeTileLayer();if(l==null||p==null)return;if(!useTilemap(p)){app.status("Rellenar solo se aplica a Pinceles TILEMAP. Los Prefabs se colocan como entidades con Dibujar.");return;}if(layer==null||layer.locked)return;ensureTile(p);int old=layer.get(x,y),replacement=p.tileId;if(old==replacement)return;ArrayDeque<int[]>q=new ArrayDeque<>();boolean[]seen=new boolean[l.width*l.height];q.add(new int[]{x,y});while(!q.isEmpty()){int[]c=q.removeFirst();int cx=c[0],cy=c[1];if(cx<0||cy<0||cx>=l.width||cy>=l.height)continue;int idx=cy*l.width+cx;if(seen[idx]||layer.get(cx,cy)!=old)continue;seen[idx]=true;layer.set(cx,cy,replacement);q.add(new int[]{cx+1,cy});q.add(new int[]{cx-1,cy});q.add(new int[]{cx,cy+1});q.add(new int[]{cx,cy-1});}app.changed();redraw();}
    private void eraseTile(int x,int y){TileLayer layer=activeTileLayer();if(layer==null||layer.locked)return;layer.set(x,y,-1);app.changed();redraw();}
    private boolean useTilemap(PrefabDef p){if(p.placement==PlacementMode.TILEMAP)return true;if(p.placement==PlacementMode.ENTITY)return false;if(p.tileId<0)return false;if(p.template==null)return true;if(p.template.script!=null&&!p.template.script.replace("# Doble clic sobre una entidad para editar su script.","").trim().isBlank()&&!p.template.script.trim().equals("# Script de "+p.name))return false;for(ComponentDef c:p.template.components)if(!Set.of("SpriteRenderer","BoxCollider2D").contains(c.type))return false;return true;}
    private String effectivePlacement(PrefabDef p){return p.placement==PlacementMode.AUTO?(useTilemap(p)?"AUTO→TILEMAP":"AUTO→ENTIDAD"):p.placement.name();}
    private void ensureTile(PrefabDef p){if(p.tileId>=0&&app.project().getTiles().containsKey(p.tileId))return;int id=app.project().nextTileId();String asset=p.template==null?"":p.template.assetKey;app.project().getTiles().put(id,new TileDef(id,p.name,new java.awt.Color(80,88,104),true,asset));p.tileId=id;}
    private EntityDef instantiatePrefab(PrefabDef p,double x,double y){EntityDef template=resolvePrefabTemplate(p,new HashSet<>());String id=uniqueEntityId(p.key);EntityDef e=cloneWithId(template,id);e.name=p.name;e.x=snap(x);e.y=snap(y);e.prefabKey=p.key;return e;}
    private EntityDef resolvePrefabTemplate(PrefabDef p,Set<String>seen){if(p==null||!seen.add(p.key))return new EntityDef("prefab","Prefab",0,0);EntityDef base=p.parentPrefab.isBlank()?null:resolvePrefabTemplate(app.project().getPrefabs().get(p.parentPrefab),seen);if(base==null)base=p.template==null?new EntityDef(p.key,p.name,0,0):p.template.copy();else if(p.template!=null)overlay(base,p.template);for(var o:p.variantOverrides.entrySet())override(base,o.getKey(),o.getValue());return base;}
    private static void overlay(EntityDef base,EntityDef child){if(!child.assetKey.isBlank())base.assetKey=child.assetKey;base.width=child.width;base.height=child.height;base.renderLayer=child.renderLayer;base.physicsLayer=child.physicsLayer;if(child.script!=null&&!child.script.isBlank())base.script=child.script;for(ComponentDef c:child.components){base.components.removeIf(x->x.type.equals(c.type));base.components.add(c.copy());}base.variables.putAll(child.variables);}
    private static void override(EntityDef e,String path,String value){String[]p=path.split("\\.");if(p.length==2){ComponentDef c=e.component(p[0]);if(c!=null)c.properties.put(p[1],value);}else if(path.equals("sprite")||path.equals("asset"))e.assetKey=value;}
    private static EntityDef cloneWithId(EntityDef source,String id){EntityDef e=new EntityDef(id,source.name,source.x,source.y);e.width=source.width;e.height=source.height;e.enabled=source.enabled;e.layer=source.layer;e.group=source.group;e.renderLayer=source.renderLayer;e.physicsLayer=source.physicsLayer;e.assetKey=source.assetKey;e.script=source.script;e.prefabKey=source.prefabKey;source.components.forEach(c->e.components.add(c.copy()));e.variables.putAll(source.variables);e.prefabOverrides.putAll(source.prefabOverrides);return e;}

    private void refresh(){loading=true;scenePicker.setItems(FXCollections.observableArrayList(app.project().getLevels().values()));if(!scenePicker.getItems().isEmpty()){Level start=app.project().getLevels().get(app.project().getStartLevel());scenePicker.setValue(start==null?scenePicker.getItems().getFirst():start);}brushPicker.setItems(FXCollections.observableArrayList(app.project().getPrefabs().values()));if(!brushPicker.getItems().isEmpty())brushPicker.setValue(brushPicker.getItems().getFirst());selected=null;selectedEntities.clear();selectedLayer=null;target=Target.SCENE;refreshTileLayers(false);refreshHierarchy();resizeCanvas();loading=false;loadScriptTarget();rebuildInspector();}
    private void refreshTileLayers(boolean preserve){Level l=level();TileLayer previous=preserve?selectedLayer:null;List<TileLayer>ordered=l==null?List.of():l.tileLayers.stream().sorted(Comparator.comparingInt(a->a.order)).toList();loading=true;tileLayers.setItems(FXCollections.observableArrayList(ordered));if(previous!=null&&tileLayers.getItems().contains(previous))tileLayers.getSelectionModel().select(previous);else tileLayers.getSelectionModel().clearSelection();loading=false;}
    private void refreshHierarchy(){Level l=level();TreeItem<HierarchyNode>root=new TreeItem<>(new HierarchyNode("ROOT","",null));hierarchy.setRoot(root);if(l==null)return;LinkedHashMap<String,List<EntityDef>>groups=new LinkedHashMap<>();for(EntityDef e:l.entities)groups.computeIfAbsent(e.group==null||e.group.isBlank()?"(Sin grupo)":e.group,k->new ArrayList<>()).add(e);for(var entry:groups.entrySet()){String groupName=entry.getKey();TreeItem<HierarchyNode>groupItem=new TreeItem<>(new HierarchyNode(groupName,groupName,null));groupItem.setExpanded(expandedGroups.contains(groupName)||groups.size()==1);groupItem.expandedProperty().addListener((o,a,b)->{if(b)expandedGroups.add(groupName);else expandedGroups.remove(groupName);});for(EntityDef e:entry.getValue())groupItem.getChildren().add(new TreeItem<>(new HierarchyNode((e.prefabKey.isBlank()?"":"◆ ")+e.name,groupName,e)));root.getChildren().add(groupItem);}selectHierarchySet();}
    private void selectHierarchySet(){loading=true;hierarchy.getSelectionModel().clearSelection();TreeItem<HierarchyNode>root=hierarchy.getRoot();if(root!=null)for(TreeItem<HierarchyNode>group:root.getChildren())for(TreeItem<HierarchyNode>child:group.getChildren())if(selectedEntities.contains(child.getValue().entity())){group.setExpanded(true);hierarchy.getSelectionModel().select(child);}loading=false;}
    private Level level(){return scenePicker.getValue();}private TileLayer activeTileLayer(){if(selectedLayer!=null)return selectedLayer;TileLayer s=tileLayers.getSelectionModel().getSelectedItem();if(s!=null)return s;Level l=level();return l==null||l.tileLayers.isEmpty()?null:l.baseLayer();}
    private int cellX(double x){return(int)Math.floor(x/cellSize());}private int cellY(double y){return(int)Math.floor(y/cellSize());}private double cellSize(){return app.project().getTileSize()*Math.max(1,zoomScale.getValue()==null?1:zoomScale.getValue());}private double snap(double v){return Math.rint(v*4)/4.0;}
    private void resizeCanvas(){Level l=level();if(l==null)return;double cell=cellSize();canvas.setWidth(Math.rint(l.width*cell));canvas.setHeight(Math.rint(l.height*cell));gridInfo.setText("Celda "+app.project().getTileSize()+" px · vista "+(zoomScale.getValue()==null?1:zoomScale.getValue())+"×");redraw();}

    private void redraw(){Level l=level();if(l==null)return;double cell=cellSize();GraphicsContext g=canvas.getGraphicsContext2D();g.setImageSmoothing(false);drawBackground(g,l,cell);List<RenderPass>passes=new ArrayList<>();for(TileLayer layer:l.tileLayers)if(layer.visible)passes.add(new RenderPass(layer.order*1000,()->drawTileLayer(g,l,layer,cell)));for(EntityDef e:l.entities)if(e.enabled)passes.add(new RenderPass(entityZ(e),()->drawEntity(g,e,cell)));passes.stream().sorted(Comparator.comparingInt(RenderPass::z)).forEach(p->p.draw.run());g.setStroke(Color.rgb(255,255,255,.10));g.setLineWidth(1);for(int x=0;x<=l.width;x++)g.strokeLine(Math.rint(x*cell)+.5,0,Math.rint(x*cell)+.5,canvas.getHeight());for(int y=0;y<=l.height;y++)g.strokeLine(0,Math.rint(y*cell)+.5,canvas.getWidth(),Math.rint(y*cell)+.5);for(EntityDef e:selectedEntities)drawSelection(g,e,cell);}
    private void drawBackground(GraphicsContext g,Level l,double cell){g.setFill(fx(l.backgroundColor));g.fillRect(0,0,canvas.getWidth(),canvas.getHeight());if(l.backgroundAssetKey.isBlank()||app.image(l.backgroundAssetKey)==null||l.backgroundMode==BackgroundMode.COLOR)return;double w=canvas.getWidth(),h=canvas.getHeight();int aw=app.assetWidth(l.backgroundAssetKey),ah=app.assetHeight(l.backgroundAssetKey);if(aw<=0||ah<=0)return;switch(l.backgroundMode){case STRETCH->app.drawAsset(g,l.backgroundAssetKey,0,0,w,h);case COVER,CONTAIN->{double s=l.backgroundMode==BackgroundMode.COVER?Math.max(w/aw,h/ah):Math.min(w/aw,h/ah),dw=aw*s,dh=ah*s;app.drawAsset(g,l.backgroundAssetKey,(w-dw)/2,(h-dh)/2,dw,dh);}case TILE->{for(double y=0;y<h;y+=ah)for(double x=0;x<w;x+=aw)app.drawAsset(g,l.backgroundAssetKey,x,y,aw,ah);}default->{}}}
    private void drawTileLayer(GraphicsContext g,Level l,TileLayer layer,double cell){double alpha=g.getGlobalAlpha();g.setGlobalAlpha(layer.opacity);for(int y=0;y<l.height;y++)for(int x=0;x<l.width;x++){int id=layer.get(x,y);if(id<0)continue;TileDef t=app.project().getTiles().get(id);if(t==null)continue;String asset=t.animationClip==null||t.animationClip.isBlank()?AdvancedTileResolver.assetFor(app.project(),l,layer,x,y,t):t.assetKey;if(!t.animationClip.isBlank()){AnimationClip clip=app.project().getAnimationClips().get(t.animationClip);if(clip!=null&&!clip.frames.isEmpty())asset=clip.frames.getFirst().assetKey;}if(!asset.isBlank()&&app.image(asset)!=null)app.drawAsset(g,asset,x*cell,y*cell,cell,cell);else{g.setFill(fx(t.color));g.fillRect(x*cell,y*cell,cell,cell);}}g.setGlobalAlpha(alpha);}
    private int entityZ(EntityDef e){ComponentDef sg=e.component("SortingGroup");int order=sg==null?e.layer:(int)Math.round(sg.number("order",e.layer));boolean ys=sg!=null&&sg.bool("ySort",false);return app.project().renderOrder(e.renderLayer)*100000+50000+order*100+(ys?(int)Math.round(e.y*10):0);}
    private void drawEntity(GraphicsContext g,EntityDef e,double cell){String asset=e.assetKey;ComponentDef animator=e.component("Animator");if(animator!=null){String clipKey=animator.get("clip","");AnimatorController controller=app.project().getAnimatorControllers().get(animator.get("controller",""));if(controller!=null){String state=animator.get("state",controller.defaultState);AnimatorState st=controller.states.get(state);if(st!=null)clipKey=st.clipKey;}AnimationClip clip=app.project().getAnimationClips().get(clipKey);if(clip!=null&&!clip.frames.isEmpty())asset=clip.frames.getFirst().assetKey;}double x=e.x*cell,y=e.y*cell,w=Math.max(4,e.width*cell),h=Math.max(4,e.height*cell);if(!asset.isBlank()&&app.image(asset)!=null)app.drawAsset(g,asset,x,y,w,h);else{g.setFill(Color.web("#4da7dc"));g.fillRoundRect(x,y,w,h,5,5);g.setStroke(Color.WHITE);g.strokeRoundRect(x,y,w,h,5,5);}}
    private void drawSelection(GraphicsContext g,EntityDef e,double cell){g.setStroke(Color.web("#42c7ff"));g.setLineWidth(2);g.strokeRect(Math.rint(e.x*cell)-2,Math.rint(e.y*cell)-2,Math.rint(e.width*cell)+4,Math.rint(e.height*cell)+4);ComponentDef c=e.component("BoxCollider2D");if(c!=null){g.setStroke(Color.web("#ffbf55"));double ox=c.number("offsetX",0),oy=c.number("offsetY",0),w=c.number("width",e.width),h=c.number("height",e.height);g.strokeRect((e.x+ox)*cell,(e.y+oy)*cell,w*cell,h*cell);}ComponentDef patrol=e.component("Patrol");if(patrol!=null){g.setStroke(Color.web("#ff6aa8"));double dist=patrol.number("distance",4);if(patrol.get("axis","x").equalsIgnoreCase("y"))g.strokeLine((e.x+e.width/2)*cell,e.y*cell,(e.x+e.width/2)*cell,(e.y+dist)*cell);else g.strokeLine(e.x*cell,(e.y+e.height/2)*cell,(e.x+dist)*cell,(e.y+e.height/2)*cell);}}
    private static Color fx(java.awt.Color c){return Color.rgb(c.getRed(),c.getGreen(),c.getBlue(),c.getAlpha()/255.0);}
    private EntityDef hit(double wx,double wy){Level l=level();if(l==null)return null;return l.entities.stream().filter(e->e.enabled&&wx>=e.x&&wy>=e.y&&wx<=e.x+e.width&&wy<=e.y+e.height).max(Comparator.comparingInt(this::entityZ)).orElse(null);}

    private void rebuildInspector(){inspector.getChildren().clear();inspector.setPadding(new Insets(10));switch(target){case SCENE->buildSceneInspector();case LAYER->buildLayerInspector();case ENTITY->buildEntityInspector();case BRUSH->buildBrushInspector();}}
    private void buildSceneInspector(){Level l=level();if(l==null)return;TextField name=new TextField(l.name);ComboBox<BackgroundMode>mode=new ComboBox<>(FXCollections.observableArrayList(BackgroundMode.values()));mode.setValue(l.backgroundMode);ComboBox<String>bg=assetPicker(l.backgroundAssetKey);ColorPicker color=new ColorPicker(fx(l.backgroundColor));CheckBox left=new CheckBox("Límite izquierdo"),right=new CheckBox("Límite derecho"),top=new CheckBox("Límite superior"),bottom=new CheckBox("Límite inferior"),pixelSnap=new CheckBox("Camera pixel snap");left.setSelected(l.boundaryLeft);right.setSelected(l.boundaryRight);top.setSelected(l.boundaryTop);bottom.setSelected(l.boundaryBottom);pixelSnap.setSelected(l.cameraPixelSnap);TextField cameraTarget=new TextField(l.cameraTarget);Spinner<Double>cameraZoom=new Spinner<>(.05,32.0,l.cameraZoom,.05);Runnable apply=()->{l.name=name.getText().isBlank()?l.id:name.getText();l.backgroundMode=mode.getValue();l.backgroundAssetKey=assetValue(bg);Color c=color.getValue();l.backgroundColor=new java.awt.Color((float)c.getRed(),(float)c.getGreen(),(float)c.getBlue(),(float)c.getOpacity());l.boundaryLeft=left.isSelected();l.boundaryRight=right.isSelected();l.boundaryTop=top.isSelected();l.boundaryBottom=bottom.isSelected();l.cameraTarget=cameraTarget.getText().trim();l.cameraZoom=cameraZoom.getValue();l.cameraPixelSnap=pixelSnap.isSelected();app.changed();scenePicker.setButtonCell(null);redraw();};name.setOnAction(e->apply.run());name.focusedProperty().addListener((o,a,b)->{if(!b)apply.run();});mode.setOnAction(e->apply.run());bg.setOnAction(e->apply.run());color.setOnAction(e->apply.run());for(CheckBox c:List.of(left,right,top,bottom,pixelSnap))c.setOnAction(e->apply.run());cameraTarget.setOnAction(e->apply.run());cameraZoom.valueProperty().addListener((o,a,b)->apply.run());GridPane f=form();row(f,0,"Nombre",name);row(f,1,"Fondo",bg);row(f,2,"Modo fondo",mode);row(f,3,"Color fondo",color);row(f,4,"Camera target",cameraTarget);row(f,5,"Camera zoom",cameraZoom);inspector.getChildren().addAll(title("ESCENA · "+l.id),f,new Separator(),title("LÍMITES INDEPENDIENTES"),left,right,top,bottom,new Separator(),title("CAMERA2D BASE"),pixelSnap,muted("El juego usa la resolución lógica de Configuración; la cámara no cambia según el monitor."));}
    private void buildLayerInspector(){TileLayer l=selectedLayer;if(l==null)return;TextField name=new TextField(l.name);ComboBox<String>render=new ComboBox<>(FXCollections.observableArrayList(app.project().getRenderLayers()));render.setValue(l.renderLayer);ComboBox<String>physics=new ComboBox<>(FXCollections.observableArrayList(app.project().getPhysicsLayers().keySet()));physics.setValue(l.physicsLayer);CheckBox visible=new CheckBox("Visible"),locked=new CheckBox("Bloqueada"),collision=new CheckBox("Participa en colisiones"),ySort=new CheckBox("Y-sort");visible.setSelected(l.visible);locked.setSelected(l.locked);collision.setSelected(l.collision);ySort.setSelected(l.ySort);Spinner<Double>opacity=new Spinner<>(0.0,1.0,l.opacity,.05),px=new Spinner<>(-10.0,10.0,l.parallaxX,.05),py=new Spinner<>(-10.0,10.0,l.parallaxY,.05);Runnable apply=()->{l.name=name.getText().isBlank()?l.id:name.getText();l.renderLayer=render.getValue();l.physicsLayer=physics.getValue();l.visible=visible.isSelected();l.locked=locked.isSelected();l.collision=collision.isSelected();l.ySort=ySort.isSelected();l.opacity=opacity.getValue();l.parallaxX=px.getValue();l.parallaxY=py.getValue();app.changed();tileLayers.refresh();redraw();};name.setOnAction(e->apply.run());render.setOnAction(e->apply.run());physics.setOnAction(e->apply.run());for(CheckBox c:List.of(visible,locked,collision,ySort))c.setOnAction(e->apply.run());for(Spinner<?> s:List.of(opacity,px,py))s.valueProperty().addListener((o,a,b)->apply.run());GridPane f=form();row(f,0,"Nombre",name);row(f,1,"Capa visual",render);row(f,2,"Capa física",physics);row(f,3,"Opacidad",opacity);row(f,4,"Parallax X",px);row(f,5,"Parallax Y",py);inspector.getChildren().addAll(title("CAPA · "+l.id),f,visible,locked,collision,ySort,muted("La solidez pertenece al Pincel/superficie. Esta capa decide si participa en física y en qué matriz de colisión."));}
    private void buildBrushInspector(){PrefabDef p=brushPicker.getValue();if(p==null){inspector.getChildren().add(muted("No hay Pincel seleccionado."));return;}ensureTile(p);TileDef t=app.project().getTiles().get(p.tileId);TextField name=new TextField(p.name);ComboBox<PlacementMode>placement=new ComboBox<>(FXCollections.observableArrayList(PlacementMode.values()));placement.setValue(p.placement);ComboBox<String>asset=assetPicker(p.template==null?t.assetKey:p.template.assetKey);CheckBox solid=new CheckBox("Sólido"),oneWay=new CheckBox("One-way" );solid.setSelected(!t.walkable);oneWay.setSelected(t.oneWay);Spinner<Double>friction=new Spinner<>(0.0,4.0,t.friction,.05),damage=new Spinner<>(0.0,100000.0,t.damage,1);ComboBox<String>animation=new ComboBox<>();animation.getItems().add("(ninguna)");animation.getItems().addAll(app.project().getAnimationClips().keySet());animation.setValue(t.animationClip.isBlank()?"(ninguna)":t.animationClip);Runnable apply=()->{p.name=name.getText().isBlank()?p.key:name.getText();p.placement=placement.getValue();String visual=assetValue(asset);t.name=p.name;t.assetKey=visual;t.walkable=!solid.isSelected();t.oneWay=oneWay.isSelected();t.friction=friction.getValue();t.damage=damage.getValue();t.animationClip="(ninguna)".equals(animation.getValue())?"":Objects.toString(animation.getValue(),"");if(p.template!=null)p.template.assetKey=visual;app.changed();brushPicker.setButtonCell(brushCell());redraw();};name.setOnAction(e->apply.run());placement.setOnAction(e->apply.run());asset.setOnAction(e->apply.run());solid.setOnAction(e->apply.run());oneWay.setOnAction(e->apply.run());friction.valueProperty().addListener((o,a,b)->apply.run());damage.valueProperty().addListener((o,a,b)->apply.run());animation.setOnAction(e->apply.run());GridPane f=form();row(f,0,"ID",new Label(p.key));row(f,1,"Nombre",name);row(f,2,"Colocación",placement);row(f,3,"Efectiva",new Label(effectivePlacement(p)));row(f,4,"Sprite/región",asset);row(f,5,"Fricción",friction);row(f,6,"Daño/s",damage);row(f,7,"Animación tile",animation);inspector.getChildren().addAll(title("PINCEL · "+p.name),f,new Separator(),title("FÍSICA DE SUPERFICIE"),solid,oneWay,muted("Aquí mismo decides si el suelo es sólido. No necesitas ir a Gráficos a buscar un 'Tile 0'."));if(p.template!=null){inspector.getChildren().add(new Separator());inspector.getChildren().add(title("COMPORTAMIENTOS DE PREFAB"));for(ComponentDef c:p.template.components)inspector.getChildren().add(componentCard(p.template,c));ComboBox<String>type=new ComboBox<>(FXCollections.observableArrayList(GameProject.BUILTIN_COMPONENTS));Button add=new Button("＋ Componente");add.setOnAction(e->{String v=type.getValue();if(v!=null&&p.template.component(v)==null){p.template.components.add(ComponentDef.preset(v));app.changed();rebuildInspector();}});inspector.getChildren().add(new HBox(6,type,add));}}
    private void buildEntityInspector(){EntityDef e=selected;if(e==null)return;TextField name=new TextField(e.name),group=new TextField(e.group);Spinner<Double>x=new Spinner<>(-10000.0,10000.0,e.x,.25),y=new Spinner<>(-10000.0,10000.0,e.y,.25),w=new Spinner<>(.05,1000.0,e.width,.05),h=new Spinner<>(.05,1000.0,e.height,.05);for(Spinner<Double>s:List.of(x,y,w,h))s.setEditable(true);ComboBox<String>sprite=assetPicker(e.assetKey),render=new ComboBox<>(FXCollections.observableArrayList(app.project().getRenderLayers())),physics=new ComboBox<>(FXCollections.observableArrayList(app.project().getPhysicsLayers().keySet()));render.setValue(e.renderLayer);physics.setValue(e.physicsLayer);CheckBox enabled=new CheckBox("Activa");enabled.setSelected(e.enabled);Runnable apply=()->{e.name=name.getText().isBlank()?e.id:name.getText();e.group=group.getText();e.x=x.getValue();e.y=y.getValue();e.width=w.getValue();e.height=h.getValue();e.assetKey=assetValue(sprite);e.renderLayer=render.getValue();e.physicsLayer=physics.getValue();e.enabled=enabled.isSelected();app.changed();refreshHierarchy();redraw();};name.setOnAction(ev->apply.run());group.setOnAction(ev->apply.run());sprite.setOnAction(ev->apply.run());render.setOnAction(ev->apply.run());physics.setOnAction(ev->apply.run());enabled.setOnAction(ev->apply.run());for(Spinner<?>s:List.of(x,y,w,h))s.valueProperty().addListener((o,a,b)->apply.run());GridPane f=form();row(f,0,"ID",new Label(e.id));row(f,1,"Nombre",name);row(f,2,"Grupo",group);row(f,3,"X",x);row(f,4,"Y",y);row(f,5,"Ancho",w);row(f,6,"Alto",h);row(f,7,"Sprite",sprite);row(f,8,"Capa visual",render);row(f,9,"Capa física",physics);inspector.getChildren().addAll(title("ENTIDAD"),f,enabled);
        if(!e.prefabKey.isBlank()){Label link=new Label("◆ Instancia de Prefab: "+e.prefabKey);link.getStyleClass().add("panel-title");Button revert=new Button("Revertir al Prefab"),applyPrefab=new Button("Aplicar al Prefab"),detach=new Button("Desvincular");revert.setOnAction(ev->revertPrefab(e));applyPrefab.setOnAction(ev->applyToPrefab(e));detach.setOnAction(ev->{e.prefabKey="";e.prefabOverrides.clear();app.changed();refreshHierarchy();rebuildInspector();});inspector.getChildren().addAll(new Separator(),link,new HBox(6,revert,applyPrefab),detach);}
        inspector.getChildren().addAll(new Separator(),title("COMPONENTES"));for(ComponentDef c:e.components)inspector.getChildren().add(componentCard(e,c));ComboBox<String>type=new ComboBox<>(FXCollections.observableArrayList(GameProject.BUILTIN_COMPONENTS));type.setPromptText("Componente…");Button add=new Button("＋ Añadir");add.setOnAction(ev->{String t=type.getValue();if(t!=null&&e.component(t)==null){e.components.add(ComponentDef.preset(t));app.changed();rebuildInspector();redraw();}});Button makePrefab=new Button("Crear / actualizar Prefab desde entidad");makePrefab.setOnAction(ev->createPrefabFromSelected());inspector.getChildren().addAll(new HBox(6,type,add),makePrefab);}
    private Node componentCard(EntityDef entity,ComponentDef c){VBox card=new VBox(6);card.getStyleClass().add("component-card");Label head=new Label(c.type+" · "+GameProject.componentDescription(c.type));head.setWrapText(true);Button remove=new Button("×");Region space=new Region();HBox.setHgrow(space,Priority.ALWAYS);remove.setOnAction(e->{entity.components.remove(c);app.changed();rebuildInspector();redraw();});card.getChildren().add(new HBox(6,head,space,remove));for(var prop:c.properties.entrySet()){String key=prop.getKey(),value=prop.getValue();boolean readOnly=Set.of("grounded","touchingLeft","touchingRight","touchingTop","finished","frame").contains(key);if(value.equalsIgnoreCase("true")||value.equalsIgnoreCase("false")){CheckBox cb=new CheckBox(key);cb.setSelected(Boolean.parseBoolean(value));cb.setDisable(readOnly);cb.setOnAction(e->{prop.setValue(Boolean.toString(cb.isSelected()));app.changed();redraw();});card.getChildren().add(cb);}else{TextField field=new TextField(value);field.setDisable(readOnly);Runnable save=()->{prop.setValue(field.getText());app.changed();redraw();};field.setOnAction(e->save.run());field.focusedProperty().addListener((o,a,b)->{if(!b)save.run();});card.getChildren().add(line(key,field));}}return card;}
    private Node componentCard(PrefabDef p,ComponentDef c){return componentCard(p.template,c);}

    private void applyToPrefab(EntityDef e){PrefabDef p=app.project().getPrefabs().get(e.prefabKey);if(p==null)return;p.template=cloneWithId(e,p.key);p.template.prefabKey="";p.template.x=p.template.y=0;e.prefabOverrides.clear();app.changed();app.status("Cambios aplicados al Prefab "+p.name+".");}
    private void revertPrefab(EntityDef e){PrefabDef p=app.project().getPrefabs().get(e.prefabKey);if(p==null)return;double x=e.x,y=e.y;String id=e.id,name=e.name,group=e.group;EntityDef r=instantiatePrefab(p,x,y);r=cloneWithId(r,id);r.x=x;r.y=y;r.name=name;r.group=group;Level l=level();int index=l.entities.indexOf(e);l.entities.set(index,r);selected=r;selectedEntities.clear();selectedEntities.add(r);app.changed();refreshHierarchy();rebuildInspector();redraw();}
    private void createPrefabFromSelected(){EntityDef e=selected;if(e==null){app.status("Selecciona una entidad primero.");return;}PrefabDef existing=e.prefabKey.isBlank()?null:app.project().getPrefabs().get(e.prefabKey);String key=existing==null?uniquePrefabKey(e.name):existing.key;PrefabDef p=existing==null?new PrefabDef(key,e.name):existing;p.placement=PlacementMode.ENTITY;p.template=cloneWithId(e,key);p.template.x=p.template.y=0;p.template.prefabKey="";if(existing==null)app.project().getPrefabs().put(key,p);e.prefabKey=key;app.changed();brushPicker.setItems(FXCollections.observableArrayList(app.project().getPrefabs().values()));brushPicker.setValue(p);refreshHierarchy();rebuildInspector();app.status("Prefab creado: "+p.name);}

    private void selectSceneTarget(){target=Target.SCENE;selected=null;selectedLayer=null;selectedEntities.clear();hierarchy.getSelectionModel().clearSelection();tileLayers.getSelectionModel().clearSelection();loadScriptTarget();rebuildInspector();redraw();}
    private void loadScriptTarget(){loading=true;script.setText(getTargetScript());loading=false;validate(false);}
    private String getTargetScript(){return switch(target){case SCENE->level()==null?"":level().script;case LAYER->selectedLayer==null?"":selectedLayer.script;case ENTITY->selected==null?"":selected.script;case BRUSH->{PrefabDef p=brushPicker.getValue();yield p==null||p.template==null?"":p.template.script;}};}
    private void setTargetScript(String value){switch(target){case SCENE->{if(level()!=null)level().script=value;}case LAYER->{if(selectedLayer!=null)selectedLayer.script=value;}case ENTITY->{if(selected!=null)selected.script=value;}case BRUSH->{PrefabDef p=brushPicker.getValue();if(p!=null){if(p.template==null){p.template=new EntityDef(p.key,p.name,0,0);}p.template.script=value;}}}}
    private void validate(boolean report){ScriptProgram.Validation v=ScriptProgram.compile(script.getText()).validation();scriptStatus.setText((v.valid()?"✓ ":"✕ ")+targetName()+" · "+(v.valid()?"Script válido":String.join(" | ",v.errors())));scriptStatus.setStyle(v.valid()?"-fx-text-fill:#74d99f;":"-fx-text-fill:#ff7d7d;");if(report)app.status(v.valid()?"Script válido.":String.join(" · ",v.errors()));}
    private String targetName(){return switch(target){case SCENE->"Escena";case LAYER->selectedLayer==null?"Capa":selectedLayer.name;case ENTITY->selected==null?"Entidad":selected.name;case BRUSH->brushPicker.getValue()==null?"Pincel":brushPicker.getValue().name;};}
    private String template(){return switch(target){case SCENE->"on start\n  # lógica global de escena\nend\n\non event alarma\n  # responde a señales\nend\n";case LAYER->"on event activarCapa\n  layer.visible = true\n  layer.collision = true\nend\n";case ENTITY,BRUSH->"on start\n  # inicialización\nend\n\non update\n  # lógica por frame\nend\n";};}

    private void addScene(){String id=uniqueSceneId("level");Level l=new Level(id,"Nueva escena",24,16);app.project().getLevels().put(id,l);app.changed();loading=true;scenePicker.setItems(FXCollections.observableArrayList(app.project().getLevels().values()));scenePicker.setValue(l);loading=false;target=Target.SCENE;refreshTileLayers(false);refreshHierarchy();resizeCanvas();loadScriptTarget();rebuildInspector();}
    private void removeScene(){Level l=level();if(l==null||app.project().getLevels().size()<=1){app.status("Debe existir al menos una escena.");return;}app.project().getLevels().remove(l.id);if(l.id.equals(app.project().getStartLevel()))app.project().setStartLevel(app.project().getLevels().keySet().iterator().next());app.changed();refresh();}
    private void addTileLayer(){Level l=level();if(l==null)return;String id="layer-"+(l.tileLayers.size()+1);Set<String>ids=new HashSet<>();l.tileLayers.forEach(x->ids.add(x.id));int n=2;while(ids.contains(id))id="layer-"+n++;TileLayer layer=new TileLayer(id,"Capa "+(l.tileLayers.size()+1),l.width,l.height,l.tileLayers.size());l.tileLayers.add(layer);selectedLayer=layer;target=Target.LAYER;app.changed();refreshTileLayers(true);tileLayers.getSelectionModel().select(layer);loadScriptTarget();rebuildInspector();}
    private void deleteTileLayer(){TileLayer layer=selectedLayer;if(layer==null||level()==null)return;if(level().tileLayers.size()<=1){app.status("Debe existir al menos una capa tilemap.");return;}level().tileLayers.remove(layer);selectedLayer=null;target=Target.SCENE;normalizeLayerOrder();app.changed();refreshTileLayers(false);loadScriptTarget();rebuildInspector();redraw();}
    private void moveTileLayer(int delta){if(selectedLayer==null||level()==null)return;List<TileLayer>list=new ArrayList<>(level().tileLayers.stream().sorted(Comparator.comparingInt(l->l.order)).toList());int i=list.indexOf(selectedLayer),j=Math.max(0,Math.min(list.size()-1,i+delta));if(i==j)return;Collections.swap(list,i,j);level().tileLayers.clear();level().tileLayers.addAll(list);normalizeLayerOrder();app.changed();refreshTileLayers(true);redraw();}
    private void normalizeLayerOrder(){if(level()==null)return;for(int i=0;i<level().tileLayers.size();i++)level().tileLayers.get(i).order=i;}
    private EntityDef createEmpty(double x,double y){Level l=level();String id=uniqueEntityId("entity");EntityDef e=new EntityDef(id,"Objeto",snap(x),snap(y));l.entities.add(e);app.changed();refreshHierarchy();return e;}
    private void addAtCenter(){Level l=level();if(l==null)return;EntityDef e=createEmpty(l.width/2.0,l.height/2.0);selectCreated(e);}
    private void selectCreated(EntityDef e){selected=e;selectedEntities.clear();selectedEntities.add(e);target=Target.ENTITY;refreshHierarchy();selectHierarchySet();loadScriptTarget();rebuildInspector();redraw();}
    private void removeSelected(){if(level()==null||selectedEntities.isEmpty())return;level().entities.removeAll(selectedEntities);selectedEntities.clear();selected=null;target=Target.SCENE;app.changed();refreshHierarchy();loadScriptTarget();rebuildInspector();redraw();}

    private void copyContext(){if(target==Target.ENTITY&&!selectedEntities.isEmpty()){entityClipboard=selectedEntities.stream().map(EntityDef::copy).toList();app.status(entityClipboard.size()+" entidad(es) copiadas.");}else if(target==Target.LAYER&&selectedLayer!=null){layerClipboard=selectedLayer.copy();app.status("Capa copiada.");}else if(target==Target.SCENE&&level()!=null){sceneClipboard=level().copy();app.status("Escena copiada.");}}
    private void pasteContext(){if(target==Target.ENTITY&&!entityClipboard.isEmpty()&&level()!=null){selectedEntities.clear();for(EntityDef source:entityClipboard){EntityDef c=cloneWithId(source,uniqueEntityId(source.id));c.x+=.5;c.y+=.5;level().entities.add(c);selectedEntities.add(c);}selected=selectedEntities.iterator().next();app.changed();refreshHierarchy();selectHierarchySet();rebuildInspector();redraw();}else if(target==Target.LAYER&&layerClipboard!=null&&level()!=null){TileLayer c=layerClipboard.copy();TileLayer n=new TileLayer(uniqueLayerId(c.id),c.name+" copia",level().width,level().height,level().tileLayers.size());n.visible=c.visible;n.locked=c.locked;n.collision=c.collision;n.renderLayer=c.renderLayer;n.physicsLayer=c.physicsLayer;n.opacity=c.opacity;n.parallaxX=c.parallaxX;n.parallaxY=c.parallaxY;n.replaceCells(c.cells());n.script=c.script;n.variables.putAll(c.variables);level().tileLayers.add(n);selectedLayer=n;app.changed();refreshTileLayers(true);redraw();}else if(target==Target.SCENE&&sceneClipboard!=null){Level c=sceneClipboard.copy();String id=uniqueSceneId(c.id);Level n=new Level(id,c.name+" copia",c.width,c.height);n.tileLayers.clear();c.tileLayers.forEach(l->n.tileLayers.add(l.copy()));c.entities.forEach(e->n.entities.add(e.copy()));n.backgroundAssetKey=c.backgroundAssetKey;n.backgroundColor=c.backgroundColor;n.backgroundMode=c.backgroundMode;n.script=c.script;app.project().getLevels().put(id,n);app.changed();refresh();}}
    private void deleteContext(){if(target==Target.ENTITY)removeSelected();else if(target==Target.LAYER)deleteTileLayer();else if(target==Target.SCENE)removeScene();}

    private String uniqueEntityId(String base){Set<String>ids=new HashSet<>();if(level()!=null)level().entities.forEach(e->ids.add(e.id));String clean=base==null||base.isBlank()?"entity":base.replaceAll("[^A-Za-z0-9_-]","-");String id=clean;int n=2;while(ids.contains(id))id=clean+"-"+n++;return id;}private String uniqueLayerId(String base){Set<String>ids=new HashSet<>();level().tileLayers.forEach(l->ids.add(l.id));String id=base+"-copy";int n=2;while(ids.contains(id))id=base+"-copy-"+n++;return id;}private String uniqueSceneId(String base){String id=base;int n=2;while(app.project().getLevels().containsKey(id))id=base+"-"+n++;return id;}private String uniquePrefabKey(String base){String clean=base==null?"prefab":base.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-").replaceAll("(^-|-$)","");if(clean.isBlank())clean="prefab";String k=clean;int n=2;while(app.project().getPrefabs().containsKey(k))k=clean+"-"+n++;return k;}
    private ComboBox<String>assetPicker(String value){ComboBox<String>c=new ComboBox<>();c.getItems().add("(ninguno)");c.getItems().addAll(app.project().getDrawableAssetKeys());c.setValue(value==null||value.isBlank()?"(ninguno)":value);c.setMaxWidth(Double.MAX_VALUE);return c;}private static String assetValue(ComboBox<String>c){return c.getValue()==null||"(ninguno)".equals(c.getValue())?"":c.getValue();}
    private static GridPane form(){GridPane g=new GridPane();g.setHgap(8);g.setVgap(7);ColumnConstraints a=new ColumnConstraints();a.setMinWidth(120);ColumnConstraints b=new ColumnConstraints();b.setHgrow(Priority.ALWAYS);g.getColumnConstraints().addAll(a,b);return g;}private static void row(GridPane g,int r,String label,Node n){g.add(new Label(label),0,r);g.add(n,1,r);if(n instanceof Region region)region.setMaxWidth(Double.MAX_VALUE);}private static Label title(String t){Label l=new Label(t);l.getStyleClass().add("panel-title");return l;}private static Label muted(String t){Label l=new Label(t);l.getStyleClass().add("muted");l.setWrapText(true);return l;}private static HBox line(String label,Node n){HBox h=new HBox(7,new Label(label),n);h.setAlignment(Pos.CENTER_LEFT);if(n instanceof Region r)HBox.setHgrow(r,Priority.ALWAYS);return h;}
}
