package com.buttclapdev.twogamerl.studio;

import com.buttclapdev.twogamerl.model.GameProject;
import com.buttclapdev.twogamerl.model.GameProject.*;
import javafx.animation.AnimationTimer;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.*;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;

import java.lang.reflect.Method;
import java.util.*;

final class SceneTools222 {
    private static final String INSTALLED="2rl.scene.tools.2.2.2",ENHANCED="2rl.scene.card.2.2.2";
    private SceneTools222(){}

    static void install(SceneEditorPane pane,StudioApp app){
        if(Boolean.TRUE.equals(pane.getProperties().get(INSTALLED)))return;pane.getProperties().put(INSTALLED,true);
        HBox toolbar=findByStyle(pane,HBox.class,"scene-tools-row"),options=findByStyle(pane,HBox.class,"scene-options-row");Canvas base=findFirst(pane,Canvas.class);if(toolbar==null||base==null)return;
        ToggleGroup group=null;for(Node n:toolbar.getChildren())if(n instanceof ToggleButton b&&b.getToggleGroup()!=null){group=b.getToggleGroup();break;}if(group==null)group=new ToggleGroup();
        ToggleButton line=new ToggleButton("Línea"),rect=new ToggleButton("Rectángulo"),pick=new ToggleButton("Cuentagotas"),stamp=new ToggleButton("Stamp");for(ToggleButton b:List.of(line,rect,pick,stamp))b.setToggleGroup(group);ComboBox<StampPattern>stampPicker=new ComboBox<>();stampPicker.setPromptText("Patrón…");stampPicker.setPrefWidth(150);Runnable refreshStamps=()->{StampPattern selected=stampPicker.getValue();stampPicker.setItems(javafx.collections.FXCollections.observableArrayList(app.project().getStampPatterns().values()));if(selected!=null)stampPicker.getSelectionModel().select(selected);};refreshStamps.run();
        toolbar.getChildren().addAll(line,rect,pick,stamp);if(options!=null){int insert=Math.max(0,options.getChildren().size()-3);options.getChildren().addAll(insert,List.of(new Label("Patrón"),stampPicker));}else toolbar.getChildren().add(stampPicker);
        int[]start={0,0};boolean[]armed={false};
        base.addEventFilter(MouseEvent.MOUSE_PRESSED,e->{if(!selected(line,rect,pick,stamp)||e.getButton()!=javafx.scene.input.MouseButton.PRIMARY)return;int x=cell(pane,app,e.getX()),y=cell(pane,app,e.getY());if(pick.isSelected()){eyedrop(pane,app,x,y);e.consume();return;}if(stamp.isSelected()){paintStamp(pane,app,stampPicker.getValue(),x,y);invokeRedraw(pane);refreshStamps.run();e.consume();return;}start[0]=x;start[1]=y;armed[0]=true;e.consume();});
        base.addEventFilter(MouseEvent.MOUSE_DRAGGED,e->{if(selected(line,rect,pick,stamp))e.consume();});
        base.addEventFilter(MouseEvent.MOUSE_RELEASED,e->{if(!armed[0])return;armed[0]=false;int x=cell(pane,app,e.getX()),y=cell(pane,app,e.getY());if(line.isSelected())paintLine(pane,app,start[0],start[1],x,y);else if(rect.isSelected())paintRect(pane,app,start[0],start[1],x,y,e.isShiftDown());invokeRedraw(pane);e.consume();});
        installSemantic(pane,app);installCameraOverlay(pane,app,base);
        AnimationTimer watcher=new AnimationTimer(){@Override public void handle(long now){enhanceTypedEditors(pane,app);}};watcher.start();pane.parentProperty().addListener((o,a,b)->{if(a!=null&&b==null)watcher.stop();});Platform.runLater(()->enhanceTypedEditors(pane,app));
    }

    private static boolean selected(ToggleButton...buttons){for(ToggleButton b:buttons)if(b.isSelected())return true;return false;}
    private static int cell(SceneEditorPane pane,StudioApp app,double v){return(int)Math.floor(v/cellSize(pane,app));}
    private static double cellSize(SceneEditorPane pane,StudioApp app){ComboBox<?>z=comboOf(pane,Integer.class);return app.project().getTileSize()*(z!=null&&z.getValue() instanceof Integer i?Math.max(1,i):1);}
    private static Level level(SceneEditorPane pane){ComboBox<?>c=comboOf(pane,Level.class);return c!=null&&c.getValue() instanceof Level l?l:null;}
    private static PrefabDef prefab(SceneEditorPane pane){ComboBox<?>c=comboOf(pane,PrefabDef.class);return c!=null&&c.getValue() instanceof PrefabDef p?p:null;}
    private static TileLayer activeLayer(SceneEditorPane pane){for(ListView<?>v:findAll(pane,ListView.class)){Object o=v.getSelectionModel().getSelectedItem();if(o instanceof TileLayer l)return l;if(!v.getItems().isEmpty()&&v.getItems().getFirst() instanceof TileLayer){Object s=v.getSelectionModel().getSelectedItem();if(s instanceof TileLayer l)return l;}}Level l=level(pane);return l==null?null:l.baseLayer();}
    private static int tileId(SceneEditorPane pane,StudioApp app){PrefabDef p=prefab(pane);if(p==null||p.placement==PlacementMode.ENTITY)return-1;if(p.tileId>=0&&app.project().getTiles().containsKey(p.tileId))return p.tileId;int id=app.project().nextTileId();String asset=p.template==null?"":p.template.assetKey;app.project().getTiles().put(id,new TileDef(id,p.name,new java.awt.Color(80,88,104),true,asset));p.tileId=id;return id;}
    private static void put(SceneEditorPane pane,StudioApp app,int x,int y,int id){Level l=level(pane);TileLayer layer=activeLayer(pane);if(l==null||layer==null||layer.locked||id<0||x<0||y<0||x>=l.width||y>=l.height)return;layer.set(x,y,id);}
    private static void paintLine(SceneEditorPane pane,StudioApp app,int x0,int y0,int x1,int y1){int id=tileId(pane,app);if(id<0){app.status("Línea requiere un Pincel TILEMAP/AUTO.");return;}int dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,err=dx+dy;for(;;){put(pane,app,x0,y0,id);if(x0==x1&&y0==y1)break;int e2=2*err;if(e2>=dy){err+=dy;x0+=sx;}if(e2<=dx){err+=dx;y0+=sy;}}app.changed();}
    private static void paintRect(SceneEditorPane pane,StudioApp app,int x0,int y0,int x1,int y1,boolean fill){int id=tileId(pane,app);if(id<0){app.status("Rectángulo requiere un Pincel TILEMAP/AUTO.");return;}int minX=Math.min(x0,x1),maxX=Math.max(x0,x1),minY=Math.min(y0,y1),maxY=Math.max(y0,y1);for(int y=minY;y<=maxY;y++)for(int x=minX;x<=maxX;x++)if(fill||x==minX||x==maxX||y==minY||y==maxY)put(pane,app,x,y,id);app.changed();}
    private static void paintStamp(SceneEditorPane pane,StudioApp app,StampPattern pattern,int x,int y){if(pattern==null){app.status("Selecciona un patrón Stamp.");return;}Level l=level(pane);TileLayer layer=activeLayer(pane);if(l==null||layer==null||layer.locked)return;for(int py=0;py<pattern.height;py++)for(int px=0;px<pattern.width;px++){int id=pattern.get(px,py);if(id>=0&&app.project().getTiles().containsKey(id))put(pane,app,x+px,y+py,id);}app.changed();}

    @SuppressWarnings("unchecked") private static void eyedrop(SceneEditorPane pane,StudioApp app,int x,int y){TileLayer layer=activeLayer(pane);if(layer==null)return;int id=layer.get(x,y);if(id<0){app.status("Cuentagotas: celda vacía.");return;}ComboBox<?>raw=comboOf(pane,PrefabDef.class);if(raw==null)return;ComboBox<PrefabDef>box=(ComboBox<PrefabDef>)raw;for(PrefabDef p:box.getItems())if(p.tileId==id){box.setValue(p);app.status("Pincel seleccionado: "+p.name);return;}app.status("Cuentagotas: tile sin Pincel asociado.");}

    private static void installSemantic(SceneEditorPane pane,StudioApp app){TextArea script=null;for(TextArea a:findAll(pane,TextArea.class)){String s=Objects.toString(a.getStyle(),"").toLowerCase(Locale.ROOT);if(s.contains("monospace")||s.contains("consolas")){script=a;break;}}if(script==null||!(script.getParent() instanceof VBox box))return;TextArea editor=script;Label semantic=new Label();semantic.setWrapText(true);semantic.getStyleClass().add("muted");box.getChildren().add(Math.max(0,box.getChildren().indexOf(editor)),semantic);Runnable run=()->{List<String>errors=ScriptSemantic222.validate(app.project(),editor.getText());semantic.setText(errors.isEmpty()?"✓ Referencias del proyecto válidas":String.join(" | ",errors));semantic.setStyle(errors.isEmpty()?"-fx-text-fill:#74d99f;":"-fx-text-fill:#ff7d7d;");};editor.textProperty().addListener((o,a,b)->run.run());run.run();}

    private static void enhanceTypedEditors(SceneEditorPane pane,StudioApp app){for(VBox card:findAll(pane,VBox.class)){if(!card.getStyleClass().contains("component-card")||Boolean.TRUE.equals(card.getProperties().get(ENHANCED)))continue;String type=componentType(card);if("ParticleEmitter2D".equals(type))replaceField(card,"preset",new ArrayList<>(app.project().getParticlePresets().keySet()));else if("Camera2D".equals(type))replaceField(card,"target",entityRefs(pane));card.getProperties().put(ENHANCED,true);}for(HBox row:findAll(pane,HBox.class))if(!Boolean.TRUE.equals(row.getProperties().get(ENHANCED))&&row.getChildren().size()>=2&&row.getChildren().getFirst() instanceof Label l&&"Camera target".equals(l.getText())&&row.getChildren().get(1) instanceof TextField f){replace(row,f,entityRefs(pane));row.getProperties().put(ENHANCED,true);}}
    private static String componentType(VBox card){for(Node n:card.getChildren())if(n instanceof HBox h)for(Node c:h.getChildren())if(c instanceof Label l)for(String type:GameProject.BUILTIN_COMPONENTS)if(Objects.toString(l.getText(),"").startsWith(type))return type;return null;}
    private static void replaceField(VBox card,String name,List<String>values){for(HBox row:findAll(card,HBox.class))if(row.getChildren().size()>=2&&row.getChildren().getFirst() instanceof Label l&&name.equals(l.getText())&&row.getChildren().get(1) instanceof TextField f){replace(row,f,values);return;}}
    private static void replace(HBox row,TextField hidden,List<String>values){ComboBox<String>pick=new ComboBox<>();pick.getItems().add("(ninguno)");pick.getItems().addAll(values);pick.setMaxWidth(Double.MAX_VALUE);String current=hidden.getText();pick.setValue(current==null||current.isBlank()?"(ninguno)":current);pick.setOnAction(e->{hidden.setText("(ninguno)".equals(pick.getValue())?"":Objects.toString(pick.getValue(),""));hidden.fireEvent(new ActionEvent());});row.getChildren().set(1,pick);}
    private static List<String>entityRefs(SceneEditorPane pane){Level l=level(pane);if(l==null)return List.of();ArrayList<String>r=new ArrayList<>();for(EntityDef e:l.entities)r.add(e.id);return r;}

    private static void installCameraOverlay(SceneEditorPane pane,StudioApp app,Canvas base){if(!(base.getParent() instanceof StackPane stack))return;Canvas overlay=new Canvas();overlay.setMouseTransparent(true);overlay.widthProperty().bind(base.widthProperty());overlay.heightProperty().bind(base.heightProperty());stack.getChildren().add(overlay);AnimationTimer timer=new AnimationTimer(){@Override public void handle(long now){drawCameraGuides(overlay,pane,app);}};timer.start();pane.parentProperty().addListener((o,a,b)->{if(a!=null&&b==null)timer.stop();});}
    private static void drawCameraGuides(Canvas canvas,SceneEditorPane pane,StudioApp app){GraphicsContext g=canvas.getGraphicsContext2D();g.clearRect(0,0,canvas.getWidth(),canvas.getHeight());Level l=level(pane);if(l==null)return;double cell=cellSize(pane,app);ComponentDef camera=null;EntityDef cameraEntity=null;double best=-Double.MAX_VALUE;for(EntityDef e:l.entities){ComponentDef c=e.component("Camera2D");if(c!=null&&c.bool("enabled",true)&&c.number("priority",0)>=best){best=c.number("priority",0);camera=c;cameraEntity=e;}}String target=l.cameraTarget;double zoom=Math.max(.05,l.cameraZoom),offX=l.cameraOffsetX,offY=l.cameraOffsetY,deadX=0,deadY=0;if(camera!=null){target=camera.get("target",target);if(target.isBlank()&&camera.bool("follow",true)&&cameraEntity!=null)target=cameraEntity.id;zoom=Math.max(.05,camera.number("zoom",zoom));offX=camera.number("offsetX",offX);offY=camera.number("offsetY",offY);deadX=Math.max(0,camera.number("deadZoneX",0));deadY=Math.max(0,camera.number("deadZoneY",0));}EntityDef t=null;for(EntityDef e:l.entities)if(e.id.equalsIgnoreCase(target)||e.name.equalsIgnoreCase(target)){t=e;break;}if(t==null)for(EntityDef e:l.entities)if(e.has("PlayerController")||e.has("PlatformerController")||e.has("GridMovement")){t=e;break;}double cx=t==null?l.width/2.0:t.x+t.width/2,cy=t==null?l.height/2.0:t.y+t.height/2,viewW=(double)app.project().getLogicalWidth()/(app.project().getTileSize()*zoom),viewH=(double)app.project().getLogicalHeight()/(app.project().getTileSize()*zoom),x=cx-viewW/2+offX,y=cy-viewH/2+offY;if(l.width<=viewW)x=(l.width-viewW)/2;else x=Math.max(0,Math.min(l.width-viewW,x));if(l.height<=viewH)y=(l.height-viewH)/2;else y=Math.max(0,Math.min(l.height-viewH,y));g.setStroke(Color.rgb(66,199,255,.9));g.setLineWidth(2);g.strokeRect(x*cell,y*cell,viewW*cell,viewH*cell);g.setStroke(Color.rgb(255,191,85,.85));g.strokeLine((x+viewW/2)*cell,y*cell,(x+viewW/2)*cell,(y+viewH)*cell);g.strokeLine(x*cell,(y+viewH/2)*cell,(x+viewW)*cell,(y+viewH/2)*cell);if(deadX>0||deadY>0){g.setStroke(Color.rgb(255,106,168,.85));g.strokeRect((cx-deadX/2)*cell,(cy-deadY/2)*cell,deadX*cell,deadY*cell);}}

    private static void invokeRedraw(SceneEditorPane pane){try{Method m=SceneEditorPane.class.getDeclaredMethod("redraw");m.setAccessible(true);m.invoke(pane);}catch(Exception ignored){}}
    private static <T extends Node>T findByStyle(Node root,Class<T>type,String style){for(T n:findAll(root,type))if(n.getStyleClass().contains(style))return n;return null;}
    private static <T extends Node>T findFirst(Node root,Class<T>type){if(type.isInstance(root))return type.cast(root);if(root instanceof Parent p)for(Node c:p.getChildrenUnmodifiable()){T f=findFirst(c,type);if(f!=null)return f;}return null;}
    private static <T extends Node>List<T>findAll(Node root,Class<T>type){ArrayList<T>out=new ArrayList<>();walk(root,type,out);return out;}private static <T extends Node>void walk(Node n,Class<T>type,List<T>out){if(type.isInstance(n))out.add(type.cast(n));if(n instanceof Parent p)for(Node c:p.getChildrenUnmodifiable())walk(c,type,out);}
    private static ComboBox<?>comboOf(Node root,Class<?>kind){for(ComboBox<?>c:findAll(root,ComboBox.class)){Object v=c.getValue();if(v!=null&&kind.isInstance(v))return c;for(Object i:c.getItems())if(i!=null&&kind.isInstance(i))return c;}return null;}
}
