package com.buttclapdev.twogamerl.io;

import com.buttclapdev.twogamerl.model.GameProject;
import com.buttclapdev.twogamerl.model.GameProject.*;

import java.awt.Color;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.zip.*;

public final class ProjectIO {
    private ProjectIO() {}

    public static void save(GameProject project,Path file)throws IOException{
        if(file.getParent()!=null)Files.createDirectories(file.getParent());
        try(ZipOutputStream zip=new ZipOutputStream(Files.newOutputStream(file))){
            Properties root=new Properties();
            root.setProperty("formatVersion",Integer.toString(GameProject.FORMAT_VERSION));root.setProperty("title",project.getTitle());root.setProperty("startLevel",safe(project.getStartLevel()));root.setProperty("startMenu",safe(project.getStartMenu()));root.setProperty("tileSize",Integer.toString(project.getTileSize()));
            root.setProperty("logicalWidth",Integer.toString(project.getLogicalWidth()));root.setProperty("logicalHeight",Integer.toString(project.getLogicalHeight()));root.setProperty("screenMode",project.getScreenMode().name());root.setProperty("scaleMode",project.getScaleMode().name());root.setProperty("defaultFilter",project.getDefaultFilter().name());root.setProperty("keepAspect",Boolean.toString(project.isKeepAspect()));root.setProperty("integerScale",Boolean.toString(project.isIntegerScale()));root.setProperty("uiSmooth",Boolean.toString(project.isUiSmooth()));root.setProperty("letterboxColor",Integer.toString(project.getLetterboxColor().getRGB()));
            putProperties(zip,"project.properties",root);writeLayerConfig(zip,project);writeTiles(zip,project);writeVisualResources(zip,project);
            for(Level level:project.getLevels().values())writeLevel(zip,level);for(MenuScreen menu:project.getMenus().values())writeMenu(zip,menu);
            for(Asset asset:project.getAssets().values()){Properties meta=new Properties();meta.setProperty("sourceName",safe(asset.sourceName));meta.setProperty("sourceOnly",Boolean.toString(asset.sourceOnly));meta.setProperty("region",Boolean.toString(asset.isRegion()));meta.setProperty("sourceAsset",safe(asset.sourceAssetKey));meta.setProperty("regionX",Integer.toString(asset.regionX));meta.setProperty("regionY",Integer.toString(asset.regionY));meta.setProperty("regionWidth",Integer.toString(asset.regionWidth));meta.setProperty("regionHeight",Integer.toString(asset.regionHeight));meta.setProperty("filter",asset.filterMode.name());meta.setProperty("category",asset.category.name());meta.setProperty("pivotX",Double.toString(asset.pivotX));meta.setProperty("pivotY",Double.toString(asset.pivotY));meta.setProperty("sourcePath",safe(asset.sourcePath));meta.setProperty("sourceModified",Long.toString(asset.sourceModified));meta.setProperty("sliceTop",Integer.toString(asset.sliceTop));meta.setProperty("sliceBottom",Integer.toString(asset.sliceBottom));meta.setProperty("sliceLeft",Integer.toString(asset.sliceLeft));meta.setProperty("sliceRight",Integer.toString(asset.sliceRight));meta.setProperty("tags",String.join("|",asset.tags));putProperties(zip,"asset-meta/"+asset.key+".properties",meta);if(asset.data!=null)putBytes(zip,"assets/"+asset.key,asset.data);}
            for(FontAsset font:project.getFonts().values()){Properties meta=new Properties();meta.setProperty("sourceName",safe(font.sourceName));putProperties(zip,"font-meta/"+font.key+".properties",meta);if(font.data!=null)putBytes(zip,"fonts/"+font.key,font.data);}
            for(SoundAsset sound:project.getSounds().values()){Properties meta=new Properties();meta.setProperty("name",safe(sound.name));meta.setProperty("volume",Double.toString(sound.volume));meta.setProperty("loop",Boolean.toString(sound.loop));meta.setProperty("category",sound.category.name());putProperties(zip,"sound-meta/"+sound.key+".properties",meta);if(sound.data!=null)putBytes(zip,"audio/"+sound.key,sound.data);}
        }
    }

    private static void writeLayerConfig(ZipOutputStream zip,GameProject project)throws IOException{Properties p=new Properties();p.setProperty("renderCount",Integer.toString(project.getRenderLayers().size()));for(int i=0;i<project.getRenderLayers().size();i++)p.setProperty("render."+i,project.getRenderLayers().get(i));p.setProperty("physicsCount",Integer.toString(project.getPhysicsLayers().size()));int i=0;for(PhysicsLayerDef layer:project.getPhysicsLayers().values()){String k="physics."+i+++".";p.setProperty(k+"name",layer.name);p.setProperty(k+"collisionCount",Integer.toString(layer.collidesWith.size()));int c=0;for(String target:layer.collidesWith)p.setProperty(k+"collision."+c++,target);}putProperties(zip,"layers.properties",p);}
    private static void writeTiles(ZipOutputStream zip,GameProject project)throws IOException{Properties p=new Properties();p.setProperty("count",Integer.toString(project.getTiles().size()));int i=0;for(TileDef t:project.getTiles().values()){String k="tile."+i+++".";p.setProperty(k+"id",Integer.toString(t.id));p.setProperty(k+"name",safe(t.name));p.setProperty(k+"rgb",Integer.toString(t.color.getRGB()));p.setProperty(k+"walkable",Boolean.toString(t.walkable));p.setProperty(k+"asset",safe(t.assetKey));p.setProperty(k+"oneWay",Boolean.toString(t.oneWay));p.setProperty(k+"friction",Double.toString(t.friction));p.setProperty(k+"damage",Double.toString(t.damage));p.setProperty(k+"animation",safe(t.animationClip));p.setProperty(k+"tags",String.join("|",t.tags));}putProperties(zip,"tiles.properties",p);}

    private static void writeVisualResources(ZipOutputStream zip,GameProject project)throws IOException{
        Properties text=new Properties();text.setProperty("count",Integer.toString(project.getTextStyles().size()));int i=0;for(TextStyle s:project.getTextStyles().values()){String k="style."+i+++".";text.setProperty(k+"key",s.key);text.setProperty(k+"name",safe(s.name));text.setProperty(k+"font",safe(s.fontKey));text.setProperty(k+"skin",safe(s.skinAssetKey));text.setProperty(k+"fontSize",Integer.toString(s.fontSize));text.setProperty(k+"speakerFontSize",Integer.toString(s.speakerFontSize));text.setProperty(k+"textColor",Integer.toString(s.textColor.getRGB()));text.setProperty(k+"speakerColor",Integer.toString(s.speakerColor.getRGB()));text.setProperty(k+"backgroundColor",Integer.toString(s.backgroundColor.getRGB()));text.setProperty(k+"borderColor",Integer.toString(s.borderColor.getRGB()));text.setProperty(k+"outlineColor",Integer.toString(s.outlineColor.getRGB()));text.setProperty(k+"shadowColor",Integer.toString(s.shadowColor.getRGB()));text.setProperty(k+"bold",Boolean.toString(s.bold));text.setProperty(k+"boldSpeaker",Boolean.toString(s.boldSpeaker));text.setProperty(k+"shadow",Boolean.toString(s.shadow));text.setProperty(k+"tail",Boolean.toString(s.tail));for(String n:List.of("borderWidth","radius","paddingX","paddingY","outlineWidth","fadeIn","fadeOut","maxWidth","panelHeight"))text.setProperty(k+n,Double.toString(switch(n){case"borderWidth"->s.borderWidth;case"radius"->s.radius;case"paddingX"->s.paddingX;case"paddingY"->s.paddingY;case"outlineWidth"->s.outlineWidth;case"fadeIn"->s.fadeIn;case"fadeOut"->s.fadeOut;case"maxWidth"->s.maxWidth;default->s.panelHeight;}));text.setProperty(k+"alignment",safe(s.alignment));}putProperties(zip,"text-styles.properties",text);
        Properties anim=new Properties();anim.setProperty("count",Integer.toString(project.getAnimationClips().size()));i=0;for(AnimationClip c:project.getAnimationClips().values()){String k="clip."+i+++".";anim.setProperty(k+"key",c.key);anim.setProperty(k+"name",safe(c.name));anim.setProperty(k+"category",c.category.name());anim.setProperty(k+"loop",Boolean.toString(c.loop));anim.setProperty(k+"pingPong",Boolean.toString(c.pingPong));anim.setProperty(k+"randomStart",Boolean.toString(c.randomStart));anim.setProperty(k+"speed",Double.toString(c.speed));anim.setProperty(k+"frameCount",Integer.toString(c.frames.size()));for(int f=0;f<c.frames.size();f++){AnimationFrame fr=c.frames.get(f);anim.setProperty(k+"frame."+f+".asset",safe(fr.assetKey));anim.setProperty(k+"frame."+f+".duration",Double.toString(fr.duration));anim.setProperty(k+"frame."+f+".event",safe(fr.event));}}putProperties(zip,"animations.properties",anim);
        Properties ctr=new Properties();ctr.setProperty("count",Integer.toString(project.getAnimatorControllers().size()));i=0;for(AnimatorController c:project.getAnimatorControllers().values()){String k="controller."+i+++".";ctr.setProperty(k+"key",c.key);ctr.setProperty(k+"name",safe(c.name));ctr.setProperty(k+"default",safe(c.defaultState));ctr.setProperty(k+"stateCount",Integer.toString(c.states.size()));int s=0;for(AnimatorState st:c.states.values()){ctr.setProperty(k+"state."+s+".name",safe(st.name));ctr.setProperty(k+"state."+s+".clip",safe(st.clipKey));ctr.setProperty(k+"state."+s+".speed",Double.toString(st.speed));s++;}ctr.setProperty(k+"transitionCount",Integer.toString(c.transitions.size()));for(int t=0;t<c.transitions.size();t++){AnimatorTransition tr=c.transitions.get(t);ctr.setProperty(k+"transition."+t+".from",safe(tr.from));ctr.setProperty(k+"transition."+t+".to",safe(tr.to));ctr.setProperty(k+"transition."+t+".path",safe(tr.path));ctr.setProperty(k+"transition."+t+".operator",safe(tr.operator));ctr.setProperty(k+"transition."+t+".value",safe(tr.value));ctr.setProperty(k+"transition."+t+".exitTime",Double.toString(tr.exitTime));ctr.setProperty(k+"transition."+t+".priority",Integer.toString(tr.priority));}}putProperties(zip,"animators.properties",ctr);
        Properties pref=new Properties();pref.setProperty("count",Integer.toString(project.getPrefabs().size()));i=0;for(PrefabDef p:project.getPrefabs().values()){String k="prefab."+i+++".";pref.setProperty(k+"key",p.key);pref.setProperty(k+"name",safe(p.name));pref.setProperty(k+"parent",safe(p.parentPrefab));pref.setProperty(k+"placement",p.placement.name());pref.setProperty(k+"tileId",Integer.toString(p.tileId));pref.setProperty(k+"overrideCount",Integer.toString(p.variantOverrides.size()));int o=0;for(var e:p.variantOverrides.entrySet()){pref.setProperty(k+"override."+o+".path",e.getKey());pref.setProperty(k+"override."+o+".value",e.getValue());o++;}if(p.template!=null)writeEntityProperties(pref,k+"template.",p.template,true);}putProperties(zip,"prefabs.properties",pref);
        Properties input=new Properties();input.setProperty("count",Integer.toString(project.getInputActions().size()));i=0;for(InputAction a:project.getInputActions().values()){String k="action."+i+++".";input.setProperty(k+"key",a.key);input.setProperty(k+"name",safe(a.name));input.setProperty(k+"deadZone",Double.toString(a.deadZone));input.setProperty(k+"bindings",String.join("|",a.bindings));}putProperties(zip,"input.properties",input);
        Properties pal=new Properties();pal.setProperty("count",Integer.toString(project.getPalettes().size()));i=0;for(PaletteAsset a:project.getPalettes().values()){String k="palette."+i+++".";pal.setProperty(k+"key",a.key);pal.setProperty(k+"name",safe(a.name));pal.setProperty(k+"count",Integer.toString(a.colors.size()));int c=0;for(var e:a.colors.entrySet()){pal.setProperty(k+"from."+c,Integer.toString(e.getKey()));pal.setProperty(k+"to."+c,Integer.toString(e.getValue()));c++;}}putProperties(zip,"palettes.properties",pal);
        Properties part=new Properties();part.setProperty("count",Integer.toString(project.getParticlePresets().size()));i=0;for(ParticlePreset p:project.getParticlePresets().values()){String k="particle."+i+++".";part.setProperty(k+"key",p.key);part.setProperty(k+"name",safe(p.name));part.setProperty(k+"asset",safe(p.assetKey));part.setProperty(k+"renderMode",p.renderMode.name());part.setProperty(k+"shape",p.shape.name());part.setProperty(k+"color",Integer.toString(p.color.getRGB()));part.setProperty(k+"rate",Double.toString(p.rate));part.setProperty(k+"lifetime",Double.toString(p.lifetime));part.setProperty(k+"speed",Double.toString(p.speed));part.setProperty(k+"spread",Double.toString(p.spread));part.setProperty(k+"direction",Double.toString(p.direction));part.setProperty(k+"gravity",Double.toString(p.gravity));part.setProperty(k+"startScale",Double.toString(p.startScale));part.setProperty(k+"endScale",Double.toString(p.endScale));part.setProperty(k+"startOpacity",Double.toString(p.startOpacity));part.setProperty(k+"endOpacity",Double.toString(p.endOpacity));part.setProperty(k+"burst",Boolean.toString(p.burst));part.setProperty(k+"burstCount",Integer.toString(p.burstCount));part.setProperty(k+"localSpace",Boolean.toString(p.localSpace));}putProperties(zip,"particles.properties",part);
    }

    private static void writeLevel(ZipOutputStream zip,Level level)throws IOException{Properties p=new Properties();p.setProperty("id",level.id);p.setProperty("name",safe(level.name));p.setProperty("width",Integer.toString(level.width));p.setProperty("height",Integer.toString(level.height));p.setProperty("backgroundAsset",safe(level.backgroundAssetKey));p.setProperty("backgroundColor",Integer.toString(level.backgroundColor.getRGB()));p.setProperty("backgroundMode",level.backgroundMode.name());p.setProperty("boundaryLeft",Boolean.toString(level.boundaryLeft));p.setProperty("boundaryRight",Boolean.toString(level.boundaryRight));p.setProperty("boundaryTop",Boolean.toString(level.boundaryTop));p.setProperty("boundaryBottom",Boolean.toString(level.boundaryBottom));p.setProperty("cameraTarget",safe(level.cameraTarget));p.setProperty("cameraZoom",Double.toString(level.cameraZoom));p.setProperty("cameraOffsetX",Double.toString(level.cameraOffsetX));p.setProperty("cameraOffsetY",Double.toString(level.cameraOffsetY));p.setProperty("cameraPixelSnap",Boolean.toString(level.cameraPixelSnap));writeVars(p,"variable.",level.variables);putBytes(zip,"scripts/"+level.id+"/@scene.2gs",safe(level.script).getBytes(StandardCharsets.UTF_8));p.setProperty("tileLayerCount",Integer.toString(level.tileLayers.size()));for(int i=0;i<level.tileLayers.size();i++){TileLayer layer=level.tileLayers.get(i);String k="tileLayer."+i+".";p.setProperty(k+"id",layer.id);p.setProperty(k+"name",safe(layer.name));p.setProperty(k+"visible",Boolean.toString(layer.visible));p.setProperty(k+"locked",Boolean.toString(layer.locked));p.setProperty(k+"collision",Boolean.toString(layer.collision));p.setProperty(k+"ySort",Boolean.toString(layer.ySort));p.setProperty(k+"opacity",Double.toString(layer.opacity));p.setProperty(k+"parallaxX",Double.toString(layer.parallaxX));p.setProperty(k+"parallaxY",Double.toString(layer.parallaxY));p.setProperty(k+"physicsLayer",safe(layer.physicsLayer));p.setProperty(k+"renderLayer",safe(layer.renderLayer));p.setProperty(k+"order",Integer.toString(layer.order));StringJoiner cells=new StringJoiner(",");for(int cell:layer.cells())cells.add(Integer.toString(cell));p.setProperty(k+"cells",cells.toString());writeVars(p,k+"variable.",layer.variables);putBytes(zip,"scripts/"+level.id+"/@layer-"+layer.id+".2gs",safe(layer.script).getBytes(StandardCharsets.UTF_8));}p.setProperty("entityCount",Integer.toString(level.entities.size()));for(int i=0;i<level.entities.size();i++){EntityDef e=level.entities.get(i);writeEntityProperties(p,"entity."+i+".",e,false);putBytes(zip,"scripts/"+level.id+"/"+e.id+".2gs",safe(e.script).getBytes(StandardCharsets.UTF_8));}putProperties(zip,"levels/"+level.id+".properties",p);}
    private static void writeEntityProperties(Properties p,String k,EntityDef e,boolean inlineScript){p.setProperty(k+"id",e.id);p.setProperty(k+"name",safe(e.name));p.setProperty(k+"x",Double.toString(e.x));p.setProperty(k+"y",Double.toString(e.y));p.setProperty(k+"width",Double.toString(e.width));p.setProperty(k+"height",Double.toString(e.height));p.setProperty(k+"enabled",Boolean.toString(e.enabled));p.setProperty(k+"layer",Integer.toString(e.layer));p.setProperty(k+"group",safe(e.group));p.setProperty(k+"renderLayer",safe(e.renderLayer));p.setProperty(k+"physicsLayer",safe(e.physicsLayer));p.setProperty(k+"asset",safe(e.assetKey));p.setProperty(k+"prefab",safe(e.prefabKey));if(inlineScript)p.setProperty(k+"script",safe(e.script));p.setProperty(k+"componentCount",Integer.toString(e.components.size()));for(int c=0;c<e.components.size();c++){ComponentDef component=e.components.get(c);String ck=k+"component."+c+".";p.setProperty(ck+"type",component.type);p.setProperty(ck+"propertyCount",Integer.toString(component.properties.size()));int pi=0;for(var prop:component.properties.entrySet()){p.setProperty(ck+"property."+pi+".name",prop.getKey());p.setProperty(ck+"property."+pi+".value",prop.getValue());pi++;}}writeVars(p,k+"variable.",e.variables);writeVars(p,k+"override.",e.prefabOverrides);}
    private static void writeVars(Properties p,String prefix,Map<String,String>vars){p.setProperty(prefix+"count",Integer.toString(vars.size()));int i=0;for(var v:vars.entrySet()){p.setProperty(prefix+i+".name",v.getKey());p.setProperty(prefix+i+".value",v.getValue());i++;}}

    private static void writeMenu(ZipOutputStream zip,MenuScreen menu)throws IOException{Properties p=new Properties();p.setProperty("id",menu.id);p.setProperty("title",safe(menu.title));p.setProperty("background",Integer.toString(menu.background.getRGB()));p.setProperty("backgroundAsset",safe(menu.backgroundAssetKey));p.setProperty("canvasWidth",Integer.toString(menu.canvasWidth));p.setProperty("canvasHeight",Integer.toString(menu.canvasHeight));p.setProperty("titleX",Integer.toString(menu.titleX));p.setProperty("titleY",Integer.toString(menu.titleY));p.setProperty("titleWidth",Integer.toString(menu.titleWidth));p.setProperty("titleHeight",Integer.toString(menu.titleHeight));p.setProperty("titleFontSize",Integer.toString(menu.titleFontSize));p.setProperty("titleFont",safe(menu.titleFontKey));p.setProperty("titleTextStyle",safe(menu.titleTextStyleKey));p.setProperty("titleColor",Integer.toString(menu.titleColor.getRGB()));p.setProperty("titleAsset",safe(menu.titleAssetKey));p.setProperty("titleAnimation",menu.titleAnimation.name());p.setProperty("titleAnimationSpeed",Double.toString(menu.titleAnimationSpeed));p.setProperty("buttonCount",Integer.toString(menu.buttons.size()));for(int i=0;i<menu.buttons.size();i++){MenuButton b=menu.buttons.get(i);String k="button."+i+".";p.setProperty(k+"text",safe(b.text));p.setProperty(k+"x",Integer.toString(b.x));p.setProperty(k+"y",Integer.toString(b.y));p.setProperty(k+"width",Integer.toString(b.width));p.setProperty(k+"height",Integer.toString(b.height));p.setProperty(k+"action",b.action.name());p.setProperty(k+"target",safe(b.target));p.setProperty(k+"asset",safe(b.assetKey));p.setProperty(k+"hoverAsset",safe(b.hoverAssetKey));p.setProperty(k+"font",safe(b.fontKey));p.setProperty(k+"textStyle",safe(b.textStyleKey));p.setProperty(k+"fontSize",Integer.toString(b.fontSize));p.setProperty(k+"textColor",Integer.toString(b.textColor.getRGB()));p.setProperty(k+"backgroundColor",Integer.toString(b.backgroundColor.getRGB()));p.setProperty(k+"animation",b.animation.name());p.setProperty(k+"hoverEffect",b.hoverEffect.name());p.setProperty(k+"animationSpeed",Double.toString(b.animationSpeed));}putProperties(zip,"menus/"+menu.id+".properties",p);}

    public static GameProject load(Path file)throws IOException{try(InputStream in=Files.newInputStream(file)){return load(in);}}
    public static GameProject load(InputStream input)throws IOException{
        GameProject project=new GameProject();Map<String,byte[]>entries=new LinkedHashMap<>();try(ZipInputStream zip=new ZipInputStream(input)){ZipEntry entry;while((entry=zip.getNextEntry())!=null){if(!entry.isDirectory())entries.put(entry.getName(),zip.readAllBytes());zip.closeEntry();}}
        Properties root=props(entries.get("project.properties"));if(root.isEmpty())throw new IOException("El archivo no contiene un proyecto 2gameRL válido.");int version=integer(root,"formatVersion",1);project.setTitle(root.getProperty("title","2gameRL"));project.setStartLevel(root.getProperty("startLevel",""));project.setStartMenu(root.getProperty("startMenu",""));project.setTileSize(integer(root,"tileSize",32));project.setLogicalWidth(integer(root,"logicalWidth",320));project.setLogicalHeight(integer(root,"logicalHeight",180));project.setScreenMode(enumValue(ScreenMode.class,root.getProperty("screenMode"),ScreenMode.FULLSCREEN_BORDERLESS));project.setScaleMode(enumValue(ScaleMode.class,root.getProperty("scaleMode"),ScaleMode.PIXEL_PERFECT));project.setDefaultFilter(enumValue(FilterMode.class,root.getProperty("defaultFilter"),FilterMode.PIXEL));project.setKeepAspect(bool(root,"keepAspect",true));project.setIntegerScale(bool(root,"integerScale",true));project.setUiSmooth(bool(root,"uiSmooth",true));project.setLetterboxColor(new Color(integer(root,"letterboxColor",new Color(8,12,18).getRGB()),true));readLayerConfig(project,entries.get("layers.properties"));readTiles(project,entries.get("tiles.properties"));readVisualResources(project,entries);
        for(var entry:entries.entrySet()){String name=entry.getKey();if(name.startsWith("levels/")&&name.endsWith(".properties"))readLevel(project,entries,entry.getValue(),name,version);else if(name.startsWith("menus/")&&name.endsWith(".properties"))readMenu(project,entry.getValue(),name);else if(name.startsWith("assets/")&&!name.endsWith("/")){String key=name.substring("assets/".length());Properties meta=props(entries.get("asset-meta/"+key+".properties"));Asset a=new Asset(key,meta.getProperty("sourceName",key),entry.getValue(),bool(meta,"sourceOnly",false));applyAssetMeta(a,meta);project.getAssets().put(key,a);}else if(name.startsWith("fonts/")&&!name.endsWith("/")){String key=name.substring("fonts/".length());Properties meta=props(entries.get("font-meta/"+key+".properties"));project.getFonts().put(key,new FontAsset(key,meta.getProperty("sourceName",key),entry.getValue()));}else if(name.startsWith("audio/")&&!name.endsWith("/")){String key=name.substring("audio/".length());Properties meta=props(entries.get("sound-meta/"+key+".properties"));SoundAsset s=new SoundAsset(key,meta.getProperty("name",key),entry.getValue());s.volume=decimal(meta,"volume",1);s.loop=bool(meta,"loop",false);s.category=enumValue(SoundCategory.class,meta.getProperty("category"),SoundCategory.SFX);project.getSounds().put(key,s);}}
        for(var entry:entries.entrySet()){String name=entry.getKey();if(!name.startsWith("asset-meta/")||!name.endsWith(".properties"))continue;String key=name.substring("asset-meta/".length(),name.length()-".properties".length());Properties meta=props(entry.getValue());if(bool(meta,"region",false)){Asset a=new Asset(key,meta.getProperty("sourceName",key),meta.getProperty("sourceAsset",""),integer(meta,"regionX",0),integer(meta,"regionY",0),integer(meta,"regionWidth",1),integer(meta,"regionHeight",1));applyAssetMeta(a,meta);project.getAssets().put(key,a);}}
        if(project.getTiles().isEmpty())project.getTiles().putAll(GameProject.createDefault().getTiles());if(project.getPrefabs().isEmpty())for(TileDef t:project.getTiles().values())project.getPrefabs().put(slug(t.name),PrefabDef.tile(slug(t.name),t.name,t.id));if(version<2)migrateV1(project);inferLegacyLayers(project,version);return project;
    }

    private static void readLayerConfig(GameProject project,byte[]data)throws IOException{if(data==null)return;Properties p=props(data);int rc=integer(p,"renderCount",0);if(rc>0){project.getRenderLayers().clear();for(int i=0;i<rc;i++){String n=p.getProperty("render."+i,"").trim();if(!n.isBlank())project.getRenderLayers().add(n);}}int pc=integer(p,"physicsCount",0);if(pc>0){project.getPhysicsLayers().clear();for(int i=0;i<pc;i++){String k="physics."+i+".",n=p.getProperty(k+"name","Layer "+(i+1));PhysicsLayerDef l=new PhysicsLayerDef(n);int cc=integer(p,k+"collisionCount",0);for(int c=0;c<cc;c++)l.collidesWith.add(p.getProperty(k+"collision."+c,""));project.getPhysicsLayers().put(n,l);}}}
    private static void readTiles(GameProject project,byte[]data)throws IOException{Properties p=props(data);int count=integer(p,"count",0);for(int i=0;i<count;i++){String k="tile."+i+".";int id=integer(p,k+"id",i);TileDef t=new TileDef(id,p.getProperty(k+"name","Tile "+id),new Color(integer(p,k+"rgb",Color.GRAY.getRGB()),true),bool(p,k+"walkable",true),p.getProperty(k+"asset",""));t.oneWay=bool(p,k+"oneWay",false);t.friction=decimal(p,k+"friction",1);t.damage=decimal(p,k+"damage",0);t.animationClip=p.getProperty(k+"animation","");addTags(t.tags,p.getProperty(k+"tags",""));project.getTiles().put(id,t);}}

    private static void readVisualResources(GameProject project,Map<String,byte[]>entries)throws IOException{
        Properties text=props(entries.get("text-styles.properties"));if(!text.isEmpty()){project.getTextStyles().clear();int count=integer(text,"count",0);for(int i=0;i<count;i++){String k="style."+i+".",key=text.getProperty(k+"key","style-"+i);TextStyle s=new TextStyle(key,text.getProperty(k+"name",key));s.fontKey=text.getProperty(k+"font","");s.skinAssetKey=text.getProperty(k+"skin","");s.fontSize=integer(text,k+"fontSize",18);s.speakerFontSize=integer(text,k+"speakerFontSize",16);s.textColor=color(text,k+"textColor",Color.WHITE);s.speakerColor=color(text,k+"speakerColor",new Color(143,207,255));s.backgroundColor=color(text,k+"backgroundColor",new Color(0,0,0,0));s.borderColor=color(text,k+"borderColor",new Color(0,0,0,0));s.outlineColor=color(text,k+"outlineColor",Color.BLACK);s.shadowColor=color(text,k+"shadowColor",new Color(0,0,0,180));s.bold=bool(text,k+"bold",false);s.boldSpeaker=bool(text,k+"boldSpeaker",false);s.shadow=bool(text,k+"shadow",false);s.tail=bool(text,k+"tail",false);s.borderWidth=decimal(text,k+"borderWidth",0);s.radius=decimal(text,k+"radius",0);s.paddingX=decimal(text,k+"paddingX",12);s.paddingY=decimal(text,k+"paddingY",8);s.outlineWidth=decimal(text,k+"outlineWidth",0);s.fadeIn=decimal(text,k+"fadeIn",.15);s.fadeOut=decimal(text,k+"fadeOut",.35);s.maxWidth=decimal(text,k+"maxWidth",720);s.panelHeight=decimal(text,k+"panelHeight",190);s.alignment=text.getProperty(k+"alignment","CENTER");project.getTextStyles().put(key,s);}}
        Properties anim=props(entries.get("animations.properties"));int ac=integer(anim,"count",0);for(int i=0;i<ac;i++){String k="clip."+i+".",key=anim.getProperty(k+"key","clip-"+i);AnimationClip c=new AnimationClip(key,anim.getProperty(k+"name",key));c.category=enumValue(AnimationCategory.class,anim.getProperty(k+"category"),AnimationCategory.ENTITY);c.loop=bool(anim,k+"loop",true);c.pingPong=bool(anim,k+"pingPong",false);c.randomStart=bool(anim,k+"randomStart",false);c.speed=decimal(anim,k+"speed",1);int fc=integer(anim,k+"frameCount",0);for(int f=0;f<fc;f++){AnimationFrame fr=new AnimationFrame(anim.getProperty(k+"frame."+f+".asset",""),decimal(anim,k+"frame."+f+".duration",.1));fr.event=anim.getProperty(k+"frame."+f+".event","");c.frames.add(fr);}project.getAnimationClips().put(key,c);}
        Properties ctr=props(entries.get("animators.properties"));int cc=integer(ctr,"count",0);for(int i=0;i<cc;i++){String k="controller."+i+".",key=ctr.getProperty(k+"key","controller-"+i);AnimatorController c=new AnimatorController(key,ctr.getProperty(k+"name",key));c.defaultState=ctr.getProperty(k+"default","");int sc=integer(ctr,k+"stateCount",0);for(int s=0;s<sc;s++){AnimatorState st=new AnimatorState(ctr.getProperty(k+"state."+s+".name","State"+s),ctr.getProperty(k+"state."+s+".clip",""));st.speed=decimal(ctr,k+"state."+s+".speed",1);c.states.put(st.name,st);}int tc=integer(ctr,k+"transitionCount",0);for(int t=0;t<tc;t++){AnimatorTransition tr=new AnimatorTransition(ctr.getProperty(k+"transition."+t+".from",""),ctr.getProperty(k+"transition."+t+".to",""));tr.path=ctr.getProperty(k+"transition."+t+".path","");tr.operator=ctr.getProperty(k+"transition."+t+".operator","==");tr.value=ctr.getProperty(k+"transition."+t+".value","true");tr.exitTime=decimal(ctr,k+"transition."+t+".exitTime",-1);tr.priority=integer(ctr,k+"transition."+t+".priority",0);c.transitions.add(tr);}project.getAnimatorControllers().put(key,c);}
        Properties pref=props(entries.get("prefabs.properties"));int pc=integer(pref,"count",0);for(int i=0;i<pc;i++){String k="prefab."+i+".",key=pref.getProperty(k+"key","prefab-"+i);PrefabDef p=new PrefabDef(key,pref.getProperty(k+"name",key));p.parentPrefab=pref.getProperty(k+"parent","");p.placement=enumValue(PlacementMode.class,pref.getProperty(k+"placement"),PlacementMode.AUTO);p.tileId=integer(pref,k+"tileId",-1);int oc=integer(pref,k+"overrideCount",0);for(int o=0;o<oc;o++)p.variantOverrides.put(pref.getProperty(k+"override."+o+".path",""),pref.getProperty(k+"override."+o+".value",""));if(pref.getProperty(k+"template.id")!=null)p.template=readEntityProperties(pref,k+"template.",null);project.getPrefabs().put(key,p);}
        Properties input=props(entries.get("input.properties"));if(!input.isEmpty()){project.getInputActions().clear();int count=integer(input,"count",0);for(int i=0;i<count;i++){String k="action."+i+".",key=input.getProperty(k+"key","Action"+i);InputAction a=new InputAction(key,split(input.getProperty(k+"bindings","")));a.name=input.getProperty(k+"name",key);a.deadZone=decimal(input,k+"deadZone",.2);project.getInputActions().put(key,a);}}
        Properties pal=props(entries.get("palettes.properties"));int plc=integer(pal,"count",0);for(int i=0;i<plc;i++){String k="palette."+i+".",key=pal.getProperty(k+"key","palette-"+i);PaletteAsset a=new PaletteAsset(key,pal.getProperty(k+"name",key));int n=integer(pal,k+"count",0);for(int c=0;c<n;c++)a.colors.put(integer(pal,k+"from."+c,0),integer(pal,k+"to."+c,0));project.getPalettes().put(key,a);}
        Properties part=props(entries.get("particles.properties"));int prc=integer(part,"count",0);for(int i=0;i<prc;i++){String k="particle."+i+".",key=part.getProperty(k+"key","particle-"+i);ParticlePreset p=new ParticlePreset(key,part.getProperty(k+"name",key));p.assetKey=part.getProperty(k+"asset","");String legacyMode=p.assetKey.isBlank()?ParticleRenderMode.PIXEL.name():ParticleRenderMode.SPRITE.name();p.renderMode=enumValue(ParticleRenderMode.class,part.getProperty(k+"renderMode"),ParticleRenderMode.valueOf(legacyMode));p.shape=enumValue(ParticleShape.class,part.getProperty(k+"shape"),ParticleShape.SQUARE);p.color=color(part,k+"color",Color.WHITE);p.rate=decimal(part,k+"rate",10);p.lifetime=decimal(part,k+"lifetime",1);p.speed=decimal(part,k+"speed",1);p.spread=decimal(part,k+"spread",45);p.direction=decimal(part,k+"direction",-90);p.gravity=decimal(part,k+"gravity",0);p.startScale=decimal(part,k+"startScale",1);p.endScale=decimal(part,k+"endScale",.2);p.startOpacity=decimal(part,k+"startOpacity",1);p.endOpacity=decimal(part,k+"endOpacity",0);p.burst=bool(part,k+"burst",false);p.burstCount=integer(part,k+"burstCount",12);p.localSpace=bool(part,k+"localSpace",true);project.getParticlePresets().put(key,p);}
    }

    private static void readLevel(GameProject project,Map<String,byte[]>entries,byte[]data,String path,int version)throws IOException{Properties p=props(data);String id=p.getProperty("id",fileStem(path));Level level=new Level(id,p.getProperty("name",id),integer(p,"width",20),integer(p,"height",15));level.tileLayers.clear();level.backgroundAssetKey=p.getProperty("backgroundAsset","");level.backgroundColor=color(p,"backgroundColor",new Color(16,22,32));level.backgroundMode=enumValue(BackgroundMode.class,p.getProperty("backgroundMode"),BackgroundMode.COLOR);level.boundaryLeft=bool(p,"boundaryLeft",false);level.boundaryRight=bool(p,"boundaryRight",false);level.boundaryTop=bool(p,"boundaryTop",false);level.boundaryBottom=bool(p,"boundaryBottom",false);level.cameraTarget=p.getProperty("cameraTarget","");level.cameraZoom=decimal(p,"cameraZoom",1);level.cameraOffsetX=decimal(p,"cameraOffsetX",0);level.cameraOffsetY=decimal(p,"cameraOffsetY",0);level.cameraPixelSnap=bool(p,"cameraPixelSnap",true);readVars(p,"variable.",level.variables);byte[]ss=entries.get("scripts/"+id+"/@scene.2gs");level.script=ss==null?"# Script de escena\n":new String(ss,StandardCharsets.UTF_8);int lc=integer(p,"tileLayerCount",0);if(lc>0){for(int i=0;i<lc;i++){String k="tileLayer."+i+".";TileLayer l=new TileLayer(p.getProperty(k+"id","layer-"+(i+1)),p.getProperty(k+"name","Capa "+(i+1)),level.width,level.height,integer(p,k+"order",i));l.visible=bool(p,k+"visible",true);l.locked=bool(p,k+"locked",false);l.collision=bool(p,k+"collision",true);l.ySort=bool(p,k+"ySort",false);l.opacity=decimal(p,k+"opacity",1);l.parallaxX=decimal(p,k+"parallaxX",1);l.parallaxY=decimal(p,k+"parallaxY",1);l.physicsLayer=p.getProperty(k+"physicsLayer","World");l.renderLayer=p.getProperty(k+"renderLayer","Suelo");l.replaceCells(parseCells(p.getProperty(k+"cells",""),level.width*level.height));readVars(p,k+"variable.",l.variables);byte[]ls=entries.get("scripts/"+id+"/@layer-"+l.id+".2gs");l.script=ls==null?"# Script de capa\n":new String(ls,StandardCharsets.UTF_8);level.tileLayers.add(l);}}else{TileLayer base=new TileLayer("base","Suelo",level.width,level.height,0);base.replaceCells(parseCells(p.getProperty("cells",""),level.width*level.height));level.tileLayers.add(base);}int ec=integer(p,"entityCount",0);for(int i=0;i<ec;i++){EntityDef e=readEntityProperties(p,"entity."+i+".",entries.get("scripts/"+id+"/"+p.getProperty("entity."+i+".id","entity-"+(i+1))+".2gs"));level.entities.add(e);}if(version<2&&level.entities.isEmpty())level.entities.add(legacyPlayer(integer(p,"spawnX",2),integer(p,"spawnY",2)));project.getLevels().put(id,level);}
    private static EntityDef readEntityProperties(Properties p,String k,byte[]script){String id=p.getProperty(k+"id","entity");EntityDef e=new EntityDef(id,p.getProperty(k+"name",id),decimal(p,k+"x",1),decimal(p,k+"y",1));e.width=decimal(p,k+"width",.82);e.height=decimal(p,k+"height",.82);e.enabled=bool(p,k+"enabled",true);e.layer=integer(p,k+"layer",0);e.group=p.getProperty(k+"group","");e.renderLayer=p.getProperty(k+"renderLayer","Objetos");e.physicsLayer=p.getProperty(k+"physicsLayer","Default");e.assetKey=p.getProperty(k+"asset","");e.prefabKey=p.getProperty(k+"prefab","");int cc=integer(p,k+"componentCount",0);for(int c=0;c<cc;c++){String ck=k+"component."+c+".";ComponentDef cd=new ComponentDef(p.getProperty(ck+"type","Component"));int pc=integer(p,ck+"propertyCount",0);for(int pi=0;pi<pc;pi++)cd.properties.put(p.getProperty(ck+"property."+pi+".name","property"+pi),p.getProperty(ck+"property."+pi+".value",""));if(!cd.properties.containsKey("enabled"))cd.properties.put("enabled","true");e.components.add(cd);}readVars(p,k+"variable.",e.variables);readVars(p,k+"override.",e.prefabOverrides);String inline=p.getProperty(k+"script");e.script=script!=null?new String(script,StandardCharsets.UTF_8):inline!=null?inline:"# Script de "+e.name+"\n";return e;}

    private static void readMenu(GameProject project,byte[]data,String path)throws IOException{Properties p=props(data);String id=p.getProperty("id",fileStem(path));MenuScreen m=new MenuScreen(id,p.getProperty("title",id));m.background=color(p,"background",new Color(19,24,34));m.backgroundAssetKey=p.getProperty("backgroundAsset","");m.canvasWidth=integer(p,"canvasWidth",640);m.canvasHeight=integer(p,"canvasHeight",480);m.titleX=integer(p,"titleX",30);m.titleY=integer(p,"titleY",30);m.titleWidth=integer(p,"titleWidth",360);m.titleHeight=integer(p,"titleHeight",80);m.titleFontSize=integer(p,"titleFontSize",34);m.titleFontKey=p.getProperty("titleFont","");m.titleTextStyleKey=p.getProperty("titleTextStyle","");m.titleColor=color(p,"titleColor",Color.WHITE);m.titleAssetKey=p.getProperty("titleAsset","");m.titleAnimation=enumValue(MenuAnimation.class,p.getProperty("titleAnimation"),MenuAnimation.NONE);m.titleAnimationSpeed=decimal(p,"titleAnimationSpeed",1);int count=integer(p,"buttonCount",0);for(int i=0;i<count;i++){String k="button."+i+".";MenuButton b=new MenuButton(p.getProperty(k+"text","Botón"),integer(p,k+"x",100),integer(p,k+"y",100),integer(p,k+"width",180),integer(p,k+"height",44),enumValue(MenuAction.class,p.getProperty(k+"action"),MenuAction.START_GAME),p.getProperty(k+"target",""));b.assetKey=p.getProperty(k+"asset","");b.hoverAssetKey=p.getProperty(k+"hoverAsset","");b.fontKey=p.getProperty(k+"font","");b.textStyleKey=p.getProperty(k+"textStyle","");b.fontSize=integer(p,k+"fontSize",16);b.textColor=color(p,k+"textColor",Color.WHITE);b.backgroundColor=color(p,k+"backgroundColor",new Color(31,115,170));b.animation=enumValue(MenuAnimation.class,p.getProperty(k+"animation"),MenuAnimation.NONE);b.hoverEffect=enumValue(MenuHoverEffect.class,p.getProperty(k+"hoverEffect"),MenuHoverEffect.SCALE);b.animationSpeed=decimal(p,k+"animationSpeed",1);m.buttons.add(b);}project.getMenus().put(id,m);}

    private static void applyAssetMeta(Asset a,Properties m){a.sourceOnly=bool(m,"sourceOnly",a.sourceOnly);a.filterMode=enumValue(FilterMode.class,m.getProperty("filter"),FilterMode.PIXEL);a.category=enumValue(AssetCategory.class,m.getProperty("category"),a.isRegion()?AssetCategory.SPRITE:AssetCategory.IMAGE);a.pivotX=decimal(m,"pivotX",.5);a.pivotY=decimal(m,"pivotY",.5);a.sourcePath=m.getProperty("sourcePath","");a.sliceTop=Math.max(0,integer(m,"sliceTop",0));a.sliceBottom=Math.max(0,integer(m,"sliceBottom",0));a.sliceLeft=Math.max(0,integer(m,"sliceLeft",0));a.sliceRight=Math.max(0,integer(m,"sliceRight",0));try{a.sourceModified=Long.parseLong(m.getProperty("sourceModified","0"));}catch(Exception ignored){}addTags(a.tags,m.getProperty("tags",""));}
    private static void inferLegacyLayers(GameProject project,int version){if(version>=4)return;for(Level level:project.getLevels().values())for(EntityDef e:level.entities){if(e.has("PlayerController")||e.has("GridMovement")){e.renderLayer="Personajes";e.physicsLayer="Player";}else if(e.has("Trigger")||e.has("ScenePortal"))e.physicsLayer="Trigger";else if(e.has("Patrol")||e.has("DamageOnContact")){e.renderLayer="Personajes";e.physicsLayer="Enemy";}}}
    private static EntityDef legacyPlayer(double x,double y){EntityDef p=new EntityDef("player","Jugador",x,y);p.assetKey="placeholder-player.png";p.renderLayer="Personajes";p.physicsLayer="Player";p.components.add(ComponentDef.preset("PlayerController"));ComponentDef body=ComponentDef.preset("Rigidbody2D");body.properties.put("gravityScale","0");p.components.add(body);p.components.add(ComponentDef.preset("BoxCollider2D"));return p;}
    private static void migrateV1(GameProject project){Asset p=GameProject.createDefault().getAssets().get("placeholder-player.png");if(p!=null&&!project.getAssets().containsKey(p.key))project.getAssets().put(p.key,p.copy());}
    private static int[]parseCells(String raw,int size){String[]v=raw==null?new String[0]:raw.split(",");int[]r=new int[size];Arrays.fill(r,-1);for(int i=0;i<Math.min(size,v.length);i++)try{r[i]=Integer.parseInt(v[i]);}catch(Exception ignored){}return r;}
    private static void readVars(Properties p,String prefix,Map<String,String>out){int n=integer(p,prefix+"count",0);for(int i=0;i<n;i++)out.put(p.getProperty(prefix+i+".name","var"+i),p.getProperty(prefix+i+".value",""));}
    private static void addTags(Collection<String>out,String raw){for(String s:split(raw))if(!s.isBlank())out.add(s);}
    private static List<String>split(String raw){return raw==null||raw.isBlank()?List.of():Arrays.stream(raw.split("\\|",-1)).filter(s->!s.isBlank()).toList();}
    private static String slug(String raw){String s=raw==null?"brush":raw.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-").replaceAll("(^-|-$)","");return s.isBlank()?"brush":s;}
    private static void putProperties(ZipOutputStream zip,String path,Properties p)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();p.store(new OutputStreamWriter(out,StandardCharsets.UTF_8),"2gameRL");putBytes(zip,path,out.toByteArray());}
    private static void putBytes(ZipOutputStream zip,String path,byte[]data)throws IOException{ZipEntry e=new ZipEntry(path);zip.putNextEntry(e);zip.write(data);zip.closeEntry();}
    private static Properties props(byte[]data)throws IOException{Properties p=new Properties();if(data!=null)p.load(new InputStreamReader(new ByteArrayInputStream(data),StandardCharsets.UTF_8));return p;}
    private static int integer(Properties p,String key,int def){try{return Integer.parseInt(p.getProperty(key,Integer.toString(def)));}catch(Exception e){return def;}}private static double decimal(Properties p,String key,double def){try{return Double.parseDouble(p.getProperty(key,Double.toString(def)));}catch(Exception e){return def;}}private static boolean bool(Properties p,String key,boolean def){return Boolean.parseBoolean(p.getProperty(key,Boolean.toString(def)));}private static Color color(Properties p,String key,Color def){return new Color(integer(p,key,def.getRGB()),true);}private static String safe(String v){return v==null?"":v;}private static String fileStem(String path){String n=path.substring(path.lastIndexOf('/')+1);int d=n.lastIndexOf('.');return d>0?n.substring(0,d):n;}private static <E extends Enum<E>>E enumValue(Class<E>type,String raw,E def){if(raw==null)return def;try{return Enum.valueOf(type,raw);}catch(Exception e){return def;}}
}
