package com.buttclapdev.twogamerl.io;

import com.buttclapdev.twogamerl.model.GameProject;
import com.buttclapdev.twogamerl.model.GameProject.*;

import java.awt.Color;
import java.io.*;
import java.util.*;
import java.util.zip.*;

/** RC sidecar persistence. Optional by design so every 2.2.x project remains loadable. */
final class RcProjectIO {
    private static final String ENTRY="rc-2.3.properties";
    private RcProjectIO(){}
    static void write(ZipOutputStream zip,GameProject p)throws IOException{
        Properties x=new Properties();
        int i=0;for(Asset a:p.getAssets().values()){String k="asset."+i+++".";x.setProperty(k+"key",a.key);x.setProperty(k+"folder",safe(a.folder));x.setProperty(k+"favorite",Boolean.toString(a.favorite));}x.setProperty("asset.count",Integer.toString(i));
        i=0;for(TileDef t:p.getTiles().values()){String k="tile."+i+++".";x.setProperty(k+"id",Integer.toString(t.id));x.setProperty(k+"mode",t.autotileMode.name());x.setProperty(k+"connectTag",safe(t.connectTag));x.setProperty(k+"variant.count",Integer.toString(t.variants.size()));for(int v=0;v<t.variants.size();v++){TileVariant tv=t.variants.get(v);x.setProperty(k+"variant."+v+".asset",safe(tv.assetKey));x.setProperty(k+"variant."+v+".weight",Double.toString(tv.weight));}x.setProperty(k+"rule.count",Integer.toString(t.autotileAssets.size()));int r=0;for(var e:t.autotileAssets.entrySet()){x.setProperty(k+"rule."+r+".mask",Integer.toString(e.getKey()));x.setProperty(k+"rule."+r+".asset",safe(e.getValue()));r++;}}x.setProperty("tile.count",Integer.toString(i));
        i=0;for(AnimationClip c:p.getAnimationClips().values()){String k="clip."+i+++".";x.setProperty(k+"key",c.key);x.setProperty(k+"reverse",Boolean.toString(c.reverse));x.setProperty(k+"fps",Double.toString(c.fps));for(int f=0;f<c.frames.size();f++){AnimationFrame fr=c.frames.get(f);x.setProperty(k+"frame."+f+".shape.count",Integer.toString(fr.shapes.size()));for(int s=0;s<fr.shapes.size();s++){FrameShape h=fr.shapes.get(s);String q=k+"frame."+f+".shape."+s+".";x.setProperty(q+"name",safe(h.name));x.setProperty(q+"role",h.role.name());x.setProperty(q+"x",Double.toString(h.x));x.setProperty(q+"y",Double.toString(h.y));x.setProperty(q+"w",Double.toString(h.width));x.setProperty(q+"h",Double.toString(h.height));}}}x.setProperty("clip.count",Integer.toString(i));
        i=0;for(AnimatorController c:p.getAnimatorControllers().values()){String k="controller."+i+++".";x.setProperty(k+"key",c.key);x.setProperty(k+"param.count",Integer.toString(c.parameters.size()));int z=0;for(AnimatorParameter a:c.parameters.values()){String q=k+"param."+z+++".";x.setProperty(q+"name",a.name);x.setProperty(q+"type",a.type.name());x.setProperty(q+"default",safe(a.defaultValue));}x.setProperty(k+"state.count",Integer.toString(c.states.size()));z=0;for(AnimatorState st:c.states.values()){String q=k+"state."+z+++".";x.setProperty(q+"name",st.name);x.setProperty(q+"blend.type",st.blendTree.type.name());x.setProperty(q+"blend.x",safe(st.blendTree.parameterX));x.setProperty(q+"blend.y",safe(st.blendTree.parameterY));x.setProperty(q+"blend.count",Integer.toString(st.blendTree.children.size()));for(int b=0;b<st.blendTree.children.size();b++){BlendChild ch=st.blendTree.children.get(b);String w=q+"blend."+b+".";x.setProperty(w+"clip",safe(ch.clipKey));x.setProperty(w+"x",Double.toString(ch.x));x.setProperty(w+"y",Double.toString(ch.y));}}}x.setProperty("controller.count",Integer.toString(i));
        i=0;for(UISkinAsset s:p.getUiSkins().values()){String k="skin."+i+++".";x.setProperty(k+"key",s.key);x.setProperty(k+"name",safe(s.name));x.setProperty(k+"normal",safe(s.normalAssetKey));x.setProperty(k+"hover",safe(s.hoverAssetKey));x.setProperty(k+"pressed",safe(s.pressedAssetKey));x.setProperty(k+"disabled",safe(s.disabledAssetKey));x.setProperty(k+"font",safe(s.fontKey));x.setProperty(k+"text",Integer.toString(s.textColor.getRGB()));x.setProperty(k+"disabledText",Integer.toString(s.disabledTextColor.getRGB()));x.setProperty(k+"background",Integer.toString(s.backgroundColor.getRGB()));x.setProperty(k+"border",Integer.toString(s.borderColor.getRGB()));x.setProperty(k+"paddingX",Double.toString(s.paddingX));x.setProperty(k+"paddingY",Double.toString(s.paddingY));x.setProperty(k+"borderWidth",Double.toString(s.borderWidth));x.setProperty(k+"radius",Double.toString(s.radius));x.setProperty(k+"animation",s.animation.name());}x.setProperty("skin.count",Integer.toString(i));
        i=0;for(AnimationSet s:p.getAnimationSets().values()){String k="set."+i+++".";x.setProperty(k+"key",s.key);x.setProperty(k+"name",safe(s.name));x.setProperty(k+"mode",s.directionMode.name());x.setProperty(k+"flip",Boolean.toString(s.useFlipX));x.setProperty(k+"clip.count",Integer.toString(s.clips.size()));int z=0;for(var e:s.clips.entrySet()){x.setProperty(k+"clip."+z+".slot",e.getKey());x.setProperty(k+"clip."+z+".value",e.getValue());z++;}}x.setProperty("set.count",Integer.toString(i));
        i=0;for(StampPattern s:p.getStampPatterns().values()){String k="stamp."+i+++".";x.setProperty(k+"key",s.key);x.setProperty(k+"name",safe(s.name));x.setProperty(k+"width",Integer.toString(s.width));x.setProperty(k+"height",Integer.toString(s.height));StringJoiner j=new StringJoiner(",");for(int c:s.cells())j.add(Integer.toString(c));x.setProperty(k+"cells",j.toString());}x.setProperty("stamp.count",Integer.toString(i));
        i=0;for(TextStyle s:p.getTextStyles().values()){String k="text."+i+++".";x.setProperty(k+"key",s.key);x.setProperty(k+"uiSkin",safe(s.uiSkinKey));}x.setProperty("text.count",Integer.toString(i));
        i=0;for(MenuScreen m:p.getMenus().values()){String k="menu."+i+++".";x.setProperty(k+"id",m.id);x.setProperty(k+"button.count",Integer.toString(m.buttons.size()));for(int b=0;b<m.buttons.size();b++){MenuButton btn=m.buttons.get(b);x.setProperty(k+"button."+b+".skin",safe(btn.uiSkinKey));x.setProperty(k+"button."+b+".enabled",Boolean.toString(btn.enabled));}}x.setProperty("menu.count",Integer.toString(i));
        ByteArrayOutputStream out=new ByteArrayOutputStream();x.store(out,"2gameRL 2.3 RC feature sidecar");zip.putNextEntry(new ZipEntry(ENTRY));zip.write(out.toByteArray());zip.closeEntry();
    }
    static void read(GameProject p,Map<String,byte[]>entries)throws IOException{
        byte[] raw=entries.get(ENTRY);if(raw==null)return;Properties x=new Properties();try(InputStream in=new ByteArrayInputStream(raw)){x.load(in);}
        for(int i=0;i<num(x,"asset.count",0);i++){String k="asset."+i+".";Asset a=p.getAssets().get(x.getProperty(k+"key",""));if(a!=null){a.folder=x.getProperty(k+"folder","");a.favorite=bool(x,k+"favorite",false);}}
        for(int i=0;i<num(x,"tile.count",0);i++){String k="tile."+i+".";TileDef t=p.getTiles().get(num(x,k+"id",-1));if(t==null)continue;t.autotileMode=en(TileAutotileMode.class,x.getProperty(k+"mode"),TileAutotileMode.NONE);t.connectTag=x.getProperty(k+"connectTag","");t.variants.clear();for(int v=0;v<num(x,k+"variant.count",0);v++)t.variants.add(new TileVariant(x.getProperty(k+"variant."+v+".asset",""),dec(x,k+"variant."+v+".weight",1)));t.autotileAssets.clear();for(int r=0;r<num(x,k+"rule.count",0);r++)t.autotileAssets.put(num(x,k+"rule."+r+".mask",0),x.getProperty(k+"rule."+r+".asset",""));}
        for(int i=0;i<num(x,"clip.count",0);i++){String k="clip."+i+".";AnimationClip c=p.getAnimationClips().get(x.getProperty(k+"key",""));if(c==null)continue;c.reverse=bool(x,k+"reverse",false);c.fps=Math.max(0,dec(x,k+"fps",0));for(int f=0;f<c.frames.size();f++){AnimationFrame fr=c.frames.get(f);fr.shapes.clear();for(int s=0;s<num(x,k+"frame."+f+".shape.count",0);s++){String q=k+"frame."+f+".shape."+s+".";fr.shapes.add(new FrameShape(x.getProperty(q+"name","shape"),en(FrameShapeRole.class,x.getProperty(q+"role"),FrameShapeRole.HITBOX),dec(x,q+"x",0),dec(x,q+"y",0),dec(x,q+"w",.5),dec(x,q+"h",.5)));}}}
        for(int i=0;i<num(x,"controller.count",0);i++){String k="controller."+i+".";AnimatorController c=p.getAnimatorControllers().get(x.getProperty(k+"key",""));if(c==null)continue;c.parameters.clear();for(int z=0;z<num(x,k+"param.count",0);z++){String q=k+"param."+z+".",name=x.getProperty(q+"name","param"+z);c.parameters.put(name,new AnimatorParameter(name,en(AnimatorParameterType.class,x.getProperty(q+"type"),AnimatorParameterType.FLOAT),x.getProperty(q+"default","0")));}for(int z=0;z<num(x,k+"state.count",0);z++){String q=k+"state."+z+".";AnimatorState st=c.states.get(x.getProperty(q+"name",""));if(st==null)continue;st.blendTree.type=en(BlendTreeType.class,x.getProperty(q+"blend.type"),BlendTreeType.NONE);st.blendTree.parameterX=x.getProperty(q+"blend.x","");st.blendTree.parameterY=x.getProperty(q+"blend.y","");st.blendTree.children.clear();for(int b=0;b<num(x,q+"blend.count",0);b++){String w=q+"blend."+b+".";st.blendTree.children.add(new BlendChild(x.getProperty(w+"clip",""),dec(x,w+"x",0),dec(x,w+"y",0)));}}}
        p.getUiSkins().clear();for(int i=0;i<num(x,"skin.count",0);i++){String k="skin."+i+".",key=x.getProperty(k+"key","skin-"+i);UISkinAsset s=new UISkinAsset(key,x.getProperty(k+"name",key));s.normalAssetKey=x.getProperty(k+"normal","");s.hoverAssetKey=x.getProperty(k+"hover","");s.pressedAssetKey=x.getProperty(k+"pressed","");s.disabledAssetKey=x.getProperty(k+"disabled","");s.fontKey=x.getProperty(k+"font","");s.textColor=color(x,k+"text",Color.WHITE);s.disabledTextColor=color(x,k+"disabledText",new Color(170,170,170));s.backgroundColor=color(x,k+"background",new Color(31,115,170));s.borderColor=color(x,k+"border",new Color(75,106,132));s.paddingX=dec(x,k+"paddingX",12);s.paddingY=dec(x,k+"paddingY",8);s.borderWidth=dec(x,k+"borderWidth",1);s.radius=dec(x,k+"radius",7);s.animation=en(MenuAnimation.class,x.getProperty(k+"animation"),MenuAnimation.NONE);p.getUiSkins().put(key,s);}
        p.getAnimationSets().clear();for(int i=0;i<num(x,"set.count",0);i++){String k="set."+i+".",key=x.getProperty(k+"key","set-"+i);AnimationSet s=new AnimationSet(key,x.getProperty(k+"name",key));s.directionMode=en(DirectionMode.class,x.getProperty(k+"mode"),DirectionMode.FOUR);s.useFlipX=bool(x,k+"flip",false);for(int z=0;z<num(x,k+"clip.count",0);z++)s.clips.put(x.getProperty(k+"clip."+z+".slot",""),x.getProperty(k+"clip."+z+".value",""));p.getAnimationSets().put(key,s);}
        p.getStampPatterns().clear();for(int i=0;i<num(x,"stamp.count",0);i++){String k="stamp."+i+".",key=x.getProperty(k+"key","stamp-"+i);StampPattern s=new StampPattern(key,x.getProperty(k+"name",key),num(x,k+"width",1),num(x,k+"height",1));String[] cells=x.getProperty(k+"cells","").split(",");int[] values=new int[s.width*s.height];Arrays.fill(values,-1);for(int z=0;z<Math.min(values.length,cells.length);z++)try{values[z]=Integer.parseInt(cells[z]);}catch(Exception ignored){}s.replaceCells(values);p.getStampPatterns().put(key,s);}
        for(int i=0;i<num(x,"text.count",0);i++){String k="text."+i+".";TextStyle s=p.getTextStyles().get(x.getProperty(k+"key",""));if(s!=null)s.uiSkinKey=x.getProperty(k+"uiSkin","");}
        for(int i=0;i<num(x,"menu.count",0);i++){String k="menu."+i+".";MenuScreen m=p.getMenus().get(x.getProperty(k+"id",""));if(m==null)continue;for(int b=0;b<Math.min(m.buttons.size(),num(x,k+"button.count",0));b++){m.buttons.get(b).uiSkinKey=x.getProperty(k+"button."+b+".skin","");m.buttons.get(b).enabled=bool(x,k+"button."+b+".enabled",true);}}
    }
    private static String safe(String s){return s==null?"":s;}private static int num(Properties p,String k,int d){try{return Integer.parseInt(p.getProperty(k,Integer.toString(d)));}catch(Exception e){return d;}}private static double dec(Properties p,String k,double d){try{return Double.parseDouble(p.getProperty(k,Double.toString(d)));}catch(Exception e){return d;}}private static boolean bool(Properties p,String k,boolean d){return Boolean.parseBoolean(p.getProperty(k,Boolean.toString(d)));}private static Color color(Properties p,String k,Color d){try{return new Color(Integer.parseInt(p.getProperty(k,Integer.toString(d.getRGB()))),true);}catch(Exception e){return d;}}private static <E extends Enum<E>>E en(Class<E>c,String v,E d){try{return Enum.valueOf(c,v);}catch(Exception e){return d;}}
}
