package com.buttclapdev.twogamerl.script;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class ScriptProgram {
    public enum Event { START, UPDATE, CLICK, DOUBLECLICK, COLLISION, TRIGGER, DESTROY, ANIMATIONSTART, ANIMATIONEND, ANIMATIONLOOP }
    public record TextRequest(String type,String anchor,String text,double duration,String dismiss,String key,String style,String color) {
        public TextRequest(String type,String anchor,String text,double duration,String dismiss,String key){this(type,anchor,text,duration,dismiss,key,"","");}
    }

    public interface Context {
        boolean keyDown(String key); boolean keyPressed(String key); void move(double dx,double dy); void setVelocity(double vx,double vy); void teleport(double x,double y); void bounce(); void destroy(); void loadScene(String id); void setSprite(String assetKey); void createEntity(String template,Double x,Double y); void schedule(double seconds,Runnable action); void log(String message); void setVariable(String name,String value); String variable(String name); void setProperty(String name,String value);
        default boolean actionDown(String action){return false;} default boolean actionPressed(String action){return false;}
        default void createPrefab(String prefab,Double x,Double y){} default void playAnimation(String clip){} default void queueAnimation(String clip){} default void stopAnimation(){}
        default void playSound(String sound,double volume){} default void stopSound(String sound){} default void playMusic(String sound,double volume){} default void stopMusic(){} default void cameraShake(double intensity,double duration){}
        default String property(String name){return"";} default String otherEntity(){return"";} default boolean entityExists(String ref){return false;} default String entityProperty(String ref,String name){return"";} default void setEntityProperty(String ref,String name,String value){} default void moveEntity(String ref,double dx,double dy){} default void teleportEntity(String ref,double x,double y){} default void destroyEntity(String ref){} default void setEntitySprite(String ref,String assetKey){} default String entityVariable(String ref,String name){return"0";} default void setEntityVariable(String ref,String name,String value){} default boolean componentExists(String ref,String type){return false;} default String componentProperty(String ref,String type,String property){return"";} default void setComponentProperty(String ref,String type,String property,String value){} default void addComponent(String ref,String type){} default void removeComponent(String ref,String type){} default String globalVariable(String name){return"0";} default void setGlobalVariable(String name,String value){} default void damage(String ref,double amount){} default void heal(String ref,double amount){} default void showMenu(String id){} default void restartScene(){} default double random(){return Math.random();}
        default String saveVariable(String name){return"0";} default void setSaveVariable(String name,String value){} default String readPath(String path){return"";} default void writePath(String path,String value){} default void emit(String event){} default void showText(TextRequest request){}
    }

    private interface Instruction { default void run(Context context){} }
    private interface Condition { boolean test(Context context); }
    private record ActionInstruction(java.util.function.Consumer<Context> action) implements Instruction { @Override public void run(Context c){action.accept(c);} }
    private record WaitInstruction(double seconds) implements Instruction {}
    private record TimerInstruction(double seconds,Instruction nested) implements Instruction { @Override public void run(Context c){c.schedule(seconds,()->executeSingle(nested,c));} }
    private record EveryInstruction(double seconds,int count,Instruction nested) implements Instruction { @Override public void run(Context c){int[]left={count};Runnable[]task=new Runnable[1];task[0]=()->{if(left[0]<=0)return;executeSingle(nested,c);left[0]--;if(left[0]>0)c.schedule(seconds,task[0]);};c.schedule(seconds,task[0]);} }
    private record IfInstruction(Condition condition,List<Instruction>yes,List<Instruction>no) implements Instruction {}
    private record RepeatInstruction(int count,List<Instruction>body) implements Instruction {}
    private record WhileInstruction(Condition condition,List<Instruction>body,int limit) implements Instruction {}
    private record WhileStepInstruction(Condition condition,List<Instruction>body,int remaining) implements Instruction {}
    private enum StopInstruction implements Instruction { INSTANCE }
    public record Validation(boolean valid,List<String>errors) {}

    private final EnumMap<Event,List<Instruction>> instructions=new EnumMap<>(Event.class);
    private final LinkedHashMap<String,List<Instruction>> namedEvents=new LinkedHashMap<>();
    private final List<String>errors=new ArrayList<>();
    private ScriptProgram(){for(Event e:Event.values())instructions.put(e,new ArrayList<>());}
    public static ScriptProgram compile(String source){ScriptProgram p=new ScriptProgram();new Parser(p,source==null?"":source).parse();return p;}
    public Validation validation(){return new Validation(errors.isEmpty(),List.copyOf(errors));}
    public void fire(Event event,Context context){if(!errors.isEmpty()||context==null)return;executeQueue(new ArrayDeque<>(instructions.get(event)),context);}
    public void fireEvent(String name,Context context){if(!errors.isEmpty()||context==null||name==null)return;List<Instruction>list=namedEvents.get(name.toLowerCase(Locale.ROOT));if(list!=null)executeQueue(new ArrayDeque<>(list),context);}

    private static void executeSingle(Instruction instruction,Context c){ArrayDeque<Instruction>q=new ArrayDeque<>();q.add(instruction);executeQueue(q,c);}
    private static void executeQueue(ArrayDeque<Instruction>q,Context c){int guard=0;while(!q.isEmpty()&&guard++<100000){Instruction i=q.removeFirst();if(i instanceof WaitInstruction w){ArrayDeque<Instruction>cont=new ArrayDeque<>(q);c.schedule(w.seconds(),()->executeQueue(cont,c));return;}if(i instanceof IfInstruction f){pushFront(q,f.condition().test(c)?f.yes():f.no());continue;}if(i instanceof RepeatInstruction r){for(int n=0;n<r.count();n++)pushFront(q,r.body());continue;}if(i instanceof WhileInstruction w){q.addFirst(new WhileStepInstruction(w.condition(),w.body(),w.limit()));continue;}if(i instanceof WhileStepInstruction w){if(!w.condition().test(c))continue;if(w.remaining()<=0){c.log("Script: while alcanzó el límite de 10000 iteraciones.");continue;}q.addFirst(new WhileStepInstruction(w.condition(),w.body(),w.remaining()-1));pushFront(q,w.body());continue;}if(i==StopInstruction.INSTANCE)return;try{i.run(c);}catch(RuntimeException ex){c.log("Script: "+(ex.getMessage()==null?ex.getClass().getSimpleName():ex.getMessage()));}}if(guard>=100000)c.log("Script: se alcanzó el límite de instrucciones de un evento.");}
    private static void pushFront(ArrayDeque<Instruction>q,List<Instruction>b){ListIterator<Instruction>it=b.listIterator(b.size());while(it.hasPrevious())q.addFirst(it.previous());}
    private void error(int line,String message){errors.add("Línea "+line+": "+message);}

    private static final class Parser {
        private static final Pattern ASSIGN=Pattern.compile("^([A-Za-z_][A-Za-z0-9_#-]*(?:\\.[A-Za-z_][A-Za-z0-9_#-]*)+)\\s*(=|\\+=|-=|\\*=|/=)\\s*(.+)$");
        private record Line(int number,String text){} private record Block(List<Instruction>instructions,boolean hitElse,boolean closed){}
        private final ScriptProgram program;private final List<Line>lines=new ArrayList<>();private int index;
        Parser(ScriptProgram p,String source){program=p;String[]raw=source.replace("\r","").split("\n",-1);for(int i=0;i<raw.length;i++){String t=stripComment(raw[i]).trim();if(!t.isEmpty())lines.add(new Line(i+1,t));}}
        void parse(){while(index<lines.size()){Line line=lines.get(index);String lower=line.text().toLowerCase(Locale.ROOT);if(!lower.startsWith("on ")){program.error(line.number(),"comando fuera de un bloque 'on ... end'");index++;continue;}String eventSpec=line.text().substring(3).trim();String lowerSpec=eventSpec.toLowerCase(Locale.ROOT);if(lowerSpec.startsWith("event ")||lowerSpec.startsWith("animationevent ")){boolean animation=lowerSpec.startsWith("animationevent ");String name=eventSpec.substring(animation?15:6).trim();if(name.isBlank()){program.error(line.number(),animation?"on animationEvent requiere un nombre":"on event requiere un nombre");index++;skipUntilEnd();continue;}if(animation)name="animation:"+name;index++;Block b=parseBlock(false);program.namedEvents.computeIfAbsent(name.toLowerCase(Locale.ROOT),k->new ArrayList<>()).addAll(b.instructions());if(!b.closed())program.error(line.number(),"falta 'end' para cerrar el evento "+name);continue;}String eventName=eventSpec.replace("_","").toUpperCase(Locale.ROOT);Event event;try{event=Event.valueOf(eventName);}catch(IllegalArgumentException ex){program.error(line.number(),"evento desconocido: "+eventSpec);index++;skipUntilEnd();continue;}index++;Block b=parseBlock(false);program.instructions.get(event).addAll(b.instructions());if(!b.closed())program.error(line.number(),"falta 'end' para cerrar el evento "+eventSpec);}}
        private Block parseBlock(boolean allowElse){List<Instruction>result=new ArrayList<>();while(index<lines.size()){Line line=lines.get(index);String lower=line.text().toLowerCase(Locale.ROOT);if(lower.equals("end")){index++;return new Block(result,false,true);}if(lower.equals("else")){if(allowElse){index++;return new Block(result,true,true);}program.error(line.number(),"'else' sin bloque condicional");index++;continue;}if(lower.startsWith("on ")){program.error(line.number(),"hay un nuevo evento antes de cerrar el bloque actual con 'end'");return new Block(result,false,false);}List<String>parts=tokens(line.text());if(parts.isEmpty()){index++;continue;}String op=parts.getFirst().toLowerCase(Locale.ROOT);if(isBlockCondition(op,parts)){Condition condition=parseCondition(line.number(),parts);index++;Block yes=parseBlock(true);List<Instruction>no=List.of();boolean closed=yes.closed();if(yes.hitElse()){Block otherwise=parseBlock(false);no=otherwise.instructions();closed=otherwise.closed();}if(!closed)program.error(line.number(),"falta 'end' para cerrar el condicional");if(condition!=null)result.add(new IfInstruction(condition,List.copyOf(yes.instructions()),List.copyOf(no)));continue;}if(op.equals("while")){if(parts.size()<4){program.error(line.number(),"uso: while <ruta> <operador> <valor>");index++;continue;}ArrayList<String>condParts=new ArrayList<>(parts);condParts.set(0,"if");Condition condition=parseCondition(line.number(),condParts);index++;Block body=parseBlock(false);if(!body.closed())program.error(line.number(),"falta 'end' para cerrar while");if(condition!=null)result.add(new WhileInstruction(condition,List.copyOf(body.instructions()),10000));continue;}if(op.equals("repeat")&&parts.size()==2){int count=integer(parts.get(1),line.number(),0,10000,"repeat");index++;Block body=parseBlock(false);if(!body.closed())program.error(line.number(),"falta 'end' para cerrar repeat");result.add(new RepeatInstruction(count,List.copyOf(body.instructions())));continue;}Instruction instruction=parseInstruction(line.number(),line.text());if(instruction!=null)result.add(instruction);index++;}return new Block(result,false,false);}
        private boolean isBlockCondition(String op,List<String>parts){return switch(op){case"ifvar","ifglobal","ifproperty","ifentity","ifcomponent","chance","ifother","if"->true;case"ifkey","ifpressed","ifaction","ifactionpressed"->parts.size()==2;default->false;};}
        private Condition parseCondition(int lineNo,List<String>parts){String op=parts.getFirst().toLowerCase(Locale.ROOT);try{return switch(op){
            case"ifkey","ifpressed"->{requireExact(parts,2,lineNo,op+" <tecla>");String key=parts.get(1);yield c->op.equals("ifpressed")?c.keyPressed(key):c.keyDown(key);}
            case"ifaction","ifactionpressed"->{requireExact(parts,2,lineNo,op+" <acción>");String action=parts.get(1);yield c->op.equals("ifactionpressed")?c.actionPressed(action):c.actionDown(action);}
            case"if"->{require(parts,4,lineNo,"if <ruta> <operador> <valor>");String path=parts.get(1),operator=parts.get(2),value=join(parts,3);yield c->compare(readPath(c,path),interpolate(c,value),operator);}
            case"ifvar"->{require(parts,4,lineNo,"ifVar <nombre> <operador> <valor>");String name=parts.get(1),operator=parts.get(2),value=join(parts,3);yield c->compare(c.variable(name),interpolate(c,value),operator);}
            case"ifglobal"->{require(parts,4,lineNo,"ifGlobal <nombre> <operador> <valor>");String name=parts.get(1),operator=parts.get(2),value=join(parts,3);yield c->compare(c.globalVariable(name),interpolate(c,value),operator);}
            case"ifproperty"->{require(parts,4,lineNo,"ifProperty <propiedad> <operador> <valor>");String name=parts.get(1),operator=parts.get(2),value=join(parts,3);yield c->compare(c.property(name),interpolate(c,value),operator);}
            case"ifentity"->{requireExact(parts,3,lineNo,"ifEntity <entidad> <exists|missing>");String ref=parts.get(1),mode=parts.get(2).toLowerCase(Locale.ROOT);if(!mode.equals("exists")&&!mode.equals("missing")){program.error(lineNo,"ifEntity acepta exists o missing");throw new ParseFailure();}yield c->c.entityExists(ref)==mode.equals("exists");}
            case"ifcomponent"->{if(parts.size()<3||parts.size()>4){program.error(lineNo,"uso: ifComponent <entidad> <tipo> [exists|missing|enabled|disabled]");throw new ParseFailure();}String ref=parts.get(1),type=parts.get(2),mode=parts.size()==4?parts.get(3).toLowerCase(Locale.ROOT):"exists";yield c->switch(mode){case"exists"->c.componentExists(ref,type);case"missing"->!c.componentExists(ref,type);case"enabled"->c.componentExists(ref,type)&&Boolean.parseBoolean(c.componentProperty(ref,type,"enabled"));case"disabled"->c.componentExists(ref,type)&&!Boolean.parseBoolean(c.componentProperty(ref,type,"enabled"));default->false;};}
            case"chance"->{requireExact(parts,2,lineNo,"chance <0..1>");double probability=number(parts.get(1),lineNo);if(probability<0||probability>1){program.error(lineNo,"chance debe estar entre 0 y 1");throw new ParseFailure();}yield c->c.random()<probability;}
            case"ifother"->{requireExact(parts,1,lineNo,"ifOther");yield c->c.otherEntity()!=null&&!c.otherEntity().isBlank();}default->null;};}catch(ParseFailure ignored){return null;}}

        private Instruction parseInstruction(int lineNo,String line){Matcher assignment=ASSIGN.matcher(line);if(assignment.matches())return parseAssignment(lineNo,assignment.group(1),assignment.group(2),assignment.group(3));List<String>parts=tokens(line);if(parts.isEmpty())return null;String op=parts.getFirst().toLowerCase(Locale.ROOT);try{return switch(op){
            case"log","print"->{require(parts,2,lineNo,"log <texto>");String message=join(parts,1);yield action(c->c.log(interpolate(c,message)));}
            case"move"->{requireExact(parts,3,lineNo,"move <x> <y>");double x=number(parts.get(1),lineNo),y=number(parts.get(2),lineNo);yield action(c->c.move(x,y));}
            case"velocity"->{requireExact(parts,3,lineNo,"velocity <x> <y>");double x=number(parts.get(1),lineNo),y=number(parts.get(2),lineNo);yield action(c->c.setVelocity(x,y));}
            case"teleport"->{requireExact(parts,3,lineNo,"teleport <x> <y>");double x=number(parts.get(1),lineNo),y=number(parts.get(2),lineNo);yield action(c->c.teleport(x,y));}
            case"bounce"->{requireExact(parts,1,lineNo,"bounce");yield action(Context::bounce);}case"destroy"->{requireExact(parts,1,lineNo,"destroy");yield action(Context::destroy);}case"destroyentity"->{requireExact(parts,2,lineNo,"destroyEntity <entidad>");String ref=parts.get(1);yield action(c->c.destroyEntity(ref));}
            case"wait"->{requireExact(parts,2,lineNo,"wait <segundos>");yield new WaitInstruction(nonNegative(number(parts.get(1),lineNo),lineNo,"wait"));}
            case"timer"->{if(parts.size()<3){program.error(lineNo,"uso: timer <segundos> <comando>");throw new ParseFailure();}double seconds=nonNegative(number(parts.get(1),lineNo),lineNo,"timer");Instruction nested=parseInstruction(lineNo,join(parts,2));if(nested==null||nested instanceof WaitInstruction||nested instanceof EveryInstruction){program.error(lineNo,"timer necesita un comando normal y no puede contener wait/every");throw new ParseFailure();}yield new TimerInstruction(seconds,nested);}
            case"every"->{if(parts.size()<4){program.error(lineNo,"uso: every <segundos> <cantidad> <comando>");throw new ParseFailure();}double seconds=nonNegative(number(parts.get(1),lineNo),lineNo,"every");int count=integer(parts.get(2),lineNo,1,10000,"every");Instruction nested=parseInstruction(lineNo,join(parts,3));if(nested==null||nested instanceof WaitInstruction||nested instanceof EveryInstruction){program.error(lineNo,"every necesita un comando normal y no puede contener wait/every");throw new ParseFailure();}yield new EveryInstruction(seconds,count,nested);}
            case"create","spawn"->{if(parts.size()!=2&&parts.size()!=4){program.error(lineNo,"uso: create <entidad|prefab> [x y]");throw new ParseFailure();}String template=parts.get(1);Double x=null,y=null;if(parts.size()==4){x=number(parts.get(2),lineNo);y=number(parts.get(3),lineNo);}Double px=x,py=y;yield action(c->c.createEntity(template,px,py));}
            case"spawnprefab"->{if(parts.size()!=2&&parts.size()!=4){program.error(lineNo,"uso: spawnPrefab <prefab> [x y]");throw new ParseFailure();}String prefab=parts.get(1);Double x=null,y=null;if(parts.size()==4){x=number(parts.get(2),lineNo);y=number(parts.get(3),lineNo);}Double px=x,py=y;yield action(c->c.createPrefab(prefab,px,py));}
            case"playanimation"->{requireExact(parts,2,lineNo,"playAnimation <clip|estado>");String clip=parts.get(1);yield action(c->c.playAnimation(interpolate(c,clip)));}
            case"queueanimation"->{requireExact(parts,2,lineNo,"queueAnimation <clip|estado>");String clip=parts.get(1);yield action(c->c.queueAnimation(interpolate(c,clip)));}
            case"stopanimation"->{requireExact(parts,1,lineNo,"stopAnimation");yield action(Context::stopAnimation);}
            case"playsound"->{if(parts.size()!=2&&parts.size()!=3){program.error(lineNo,"uso: playSound <sonido> [volumen 0..1]");throw new ParseFailure();}String sound=parts.get(1);double volume=parts.size()==3?unit(number(parts.get(2),lineNo),lineNo,"playSound"):1;yield action(c->c.playSound(interpolate(c,sound),volume));}
            case"stopsound"->{requireExact(parts,2,lineNo,"stopSound <sonido>");String sound=parts.get(1);yield action(c->c.stopSound(interpolate(c,sound)));}
            case"playmusic"->{if(parts.size()!=2&&parts.size()!=3){program.error(lineNo,"uso: playMusic <sonido> [volumen 0..1]");throw new ParseFailure();}String sound=parts.get(1);double volume=parts.size()==3?unit(number(parts.get(2),lineNo),lineNo,"playMusic"):1;yield action(c->c.playMusic(interpolate(c,sound),volume));}
            case"stopmusic"->{requireExact(parts,1,lineNo,"stopMusic");yield action(Context::stopMusic);}
            case"camerashake"->{requireExact(parts,3,lineNo,"cameraShake <intensidad> <segundos>");double intensity=nonNegative(number(parts.get(1),lineNo),lineNo,"cameraShake"),duration=nonNegative(number(parts.get(2),lineNo),lineNo,"cameraShake");yield action(c->c.cameraShake(intensity,duration));}
            case"loadscene"->{requireExact(parts,2,lineNo,"loadScene <id>");String id=parts.get(1);yield action(c->c.loadScene(id));}case"showmenu"->{requireExact(parts,2,lineNo,"showMenu <id>");String id=parts.get(1);yield action(c->c.showMenu(id));}case"restartscene"->{requireExact(parts,1,lineNo,"restartScene");yield action(Context::restartScene);}case"setsprite"->{requireExact(parts,2,lineNo,"setSprite <asset>");String id=parts.get(1);yield action(c->c.setSprite(interpolate(c,id)));}case"setentitysprite"->{requireExact(parts,3,lineNo,"setEntitySprite <entidad> <asset>");String ref=parts.get(1),asset=parts.get(2);yield action(c->c.setEntitySprite(ref,interpolate(c,asset)));}
            case"emit"->{requireExact(parts,2,lineNo,"emit <evento>");String name=parts.get(1);yield action(c->c.emit(interpolate(c,name)));}case"showtext"->parseShowText(lineNo,parts);
            case"setvar"->{require(parts,3,lineNo,"setVar <nombre> <valor>");String key=parts.get(1),value=join(parts,2);yield action(c->c.setVariable(key,interpolate(c,value)));}case"addvar","mulvar","divvar"->{requireExact(parts,3,lineNo,op+" <nombre> <número>");String key=parts.get(1);double amount=number(parts.get(2),lineNo);yield action(c->{double old=parseDouble(c.variable(key),0);double next=switch(op){case"addvar"->old+amount;case"mulvar"->old*amount;default->amount==0?old:old/amount;};c.setVariable(key,trimNumber(next));});}case"randomvar"->{requireExact(parts,4,lineNo,"randomVar <nombre> <min> <max>");String key=parts.get(1);double min=number(parts.get(2),lineNo),max=number(parts.get(3),lineNo);if(max<min){program.error(lineNo,"randomVar requiere max >= min");throw new ParseFailure();}yield action(c->c.setVariable(key,trimNumber(min+c.random()*(max-min))));}
            case"setglobal"->{require(parts,3,lineNo,"setGlobal <nombre> <valor>");String key=parts.get(1),value=join(parts,2);yield action(c->c.setGlobalVariable(key,interpolate(c,value)));}case"addglobal"->{requireExact(parts,3,lineNo,"addGlobal <nombre> <número>");String key=parts.get(1);double amount=number(parts.get(2),lineNo);yield action(c->c.setGlobalVariable(key,trimNumber(parseDouble(c.globalVariable(key),0)+amount)));}
            case"set"->{require(parts,3,lineNo,"set <propiedad> <valor>");String key=parts.get(1),value=join(parts,2);yield action(c->c.setProperty(key,interpolate(c,value)));}case"setentity"->{require(parts,4,lineNo,"setEntity <entidad> <propiedad> <valor>");String ref=parts.get(1),key=parts.get(2),value=join(parts,3);yield action(c->c.setEntityProperty(ref,key,interpolate(c,value)));}case"moveentity"->{requireExact(parts,4,lineNo,"moveEntity <entidad> <x> <y>");String ref=parts.get(1);double x=number(parts.get(2),lineNo),y=number(parts.get(3),lineNo);yield action(c->c.moveEntity(ref,x,y));}case"teleportentity"->{requireExact(parts,4,lineNo,"teleportEntity <entidad> <x> <y>");String ref=parts.get(1);double x=number(parts.get(2),lineNo),y=number(parts.get(3),lineNo);yield action(c->c.teleportEntity(ref,x,y));}
            case"setentityvar"->{require(parts,4,lineNo,"setEntityVar <entidad> <nombre> <valor>");String ref=parts.get(1),key=parts.get(2),value=join(parts,3);yield action(c->c.setEntityVariable(ref,key,interpolate(c,value)));}case"addentityvar"->{requireExact(parts,4,lineNo,"addEntityVar <entidad> <nombre> <número>");String ref=parts.get(1),key=parts.get(2);double amount=number(parts.get(3),lineNo);yield action(c->c.setEntityVariable(ref,key,trimNumber(parseDouble(c.entityVariable(ref,key),0)+amount)));}
            case"addcomponent"->{requireExact(parts,3,lineNo,"addComponent <entidad> <tipo>");String ref=parts.get(1),type=parts.get(2);yield action(c->c.addComponent(ref,type));}case"removecomponent"->{requireExact(parts,3,lineNo,"removeComponent <entidad> <tipo>");String ref=parts.get(1),type=parts.get(2);yield action(c->c.removeComponent(ref,type));}case"setcomponent"->{require(parts,5,lineNo,"setComponent <entidad> <tipo> <propiedad> <valor>");String ref=parts.get(1),type=parts.get(2),key=parts.get(3),value=join(parts,4);yield action(c->c.setComponentProperty(ref,type,key,interpolate(c,value)));}case"enablecomponent"->{requireExact(parts,4,lineNo,"enableComponent <entidad> <tipo> <true|false>");String ref=parts.get(1),type=parts.get(2),value=parts.get(3);if(!value.equalsIgnoreCase("true")&&!value.equalsIgnoreCase("false")){program.error(lineNo,"enableComponent requiere true o false");throw new ParseFailure();}yield action(c->c.setComponentProperty(ref,type,"enabled",value.toLowerCase(Locale.ROOT)));}
            case"damage","heal"->{requireExact(parts,3,lineNo,op+" <entidad> <cantidad>");String ref=parts.get(1);double amount=nonNegative(number(parts.get(2),lineNo),lineNo,op);yield action(c->{if(op.equals("damage"))c.damage(ref,amount);else c.heal(ref,amount);});}
            case"ifkey","ifpressed"->parseInlineInputConditional(lineNo,parts,op.equals("ifpressed"),false);case"ifaction","ifactionpressed"->parseInlineInputConditional(lineNo,parts,op.equals("ifactionpressed"),true);case"stop","return"->{requireExact(parts,1,lineNo,op);yield StopInstruction.INSTANCE;}default->{program.error(lineNo,"comando desconocido: "+parts.getFirst());yield null;}
        };}catch(ParseFailure ignored){return null;}}

        private Instruction parseAssignment(int lineNo,String path,String operator,String rhs){String raw=unquote(rhs.trim());if(raw.isBlank()){program.error(lineNo,"la asignación necesita un valor");return null;}return action(c->{String value=interpolate(c,raw);if(operator.equals("=")){writePath(c,path,value);return;}String old=readPath(c,path);Double a=tryNumber(old),b=tryNumber(value);if(a!=null&&b!=null){double next=switch(operator){case"+="->a+b;case"-="->a-b;case"*="->a*b;case"/="->b==0?a:a/b;default->b;};writePath(c,path,trimNumber(next));}else if(operator.equals("+="))writePath(c,path,(old==null?"":old)+value);else c.log("Script: operación "+operator+" requiere valores numéricos en "+path);});}
        private Instruction parseShowText(int lineNo,List<String>parts){if(parts.size()<4){program.error(lineNo,"uso: showText <free|bubble|novel> ... [style nombre] [color #RRGGBB]");throw new ParseFailure();}String type=parts.get(1).toLowerCase(Locale.ROOT),style="",color="";int styleIndex=indexOfIgnoreCase(parts,"style"),colorIndex=indexOfIgnoreCase(parts,"color");if(styleIndex>=0&&styleIndex+1<parts.size())style=parts.get(styleIndex+1);if(colorIndex>=0&&colorIndex+1<parts.size())color=parts.get(colorIndex+1);int end=parts.size();if(styleIndex>=0)end=Math.min(end,styleIndex);if(colorIndex>=0)end=Math.min(end,colorIndex);List<String>core=parts.subList(0,end);
            if(type.equals("free")||type.equals("bubble")){String anchor,text,durationRaw;if(core.size()==4){anchor=type.equals("bubble")?"self":"screen";text=core.get(2);durationRaw=core.get(3);}else if(core.size()>=5){anchor=core.get(2);text=core.get(3);durationRaw=core.get(4);}else{program.error(lineNo,"uso: showText "+type+" [ancla] <texto> <segundos>");throw new ParseFailure();}double duration=nonNegative(number(durationRaw,lineNo),lineNo,"showText");String a=anchor,t=text,st=style,co=color;return action(c->c.showText(new TextRequest(type,interpolate(c,a),interpolate(c,t),duration,"time","",interpolate(c,st),interpolate(c,co))));}
            if(type.equals("novel")){String speaker=core.get(2),text=core.get(3),dismiss="click",key="";double duration=0;if(core.size()>=5){String d=core.get(4);if(d.equalsIgnoreCase("click"))dismiss="click";else if(d.equalsIgnoreCase("key")){dismiss="key";if(core.size()>=6)key=core.get(5);else key="SPACE";}else{duration=nonNegative(number(d,lineNo),lineNo,"showText");dismiss="time";}}String sp=speaker,tx=text,dm=dismiss,ky=key,st=style,co=color;double du=duration;return action(c->c.showText(new TextRequest("novel",interpolate(c,sp),interpolate(c,tx),du,dm,ky,interpolate(c,st),interpolate(c,co))));}program.error(lineNo,"showText acepta free, bubble o novel");throw new ParseFailure();}
        private Instruction parseInlineInputConditional(int lineNo,List<String>parts,boolean pressed,boolean actionInput){if(parts.size()<3){program.error(lineNo,(actionInput?(pressed?"ifActionPressed":"ifAction"):(pressed?"ifPressed":"ifKey"))+" <entrada> <comando>");throw new ParseFailure();}String key=parts.get(1);Instruction nested=parseInstruction(lineNo,join(parts,2));if(nested==null||nested instanceof WaitInstruction){program.error(lineNo,"wait debe ir en una línea propia");throw new ParseFailure();}return action(c->{boolean ok=actionInput?(pressed?c.actionPressed(key):c.actionDown(key)):(pressed?c.keyPressed(key):c.keyDown(key));if(ok)executeSingle(nested,c);});}
        private static int indexOfIgnoreCase(List<String>parts,String value){for(int i=0;i<parts.size();i++)if(parts.get(i).equalsIgnoreCase(value))return i;return-1;}
        private void skipUntilEnd(){while(index<lines.size())if(lines.get(index++).text().equalsIgnoreCase("end"))return;}
        private static ActionInstruction action(java.util.function.Consumer<Context>a){return new ActionInstruction(a);}private void require(List<String>p,int count,int lineNo,String usage){if(p.size()<count){program.error(lineNo,"uso: "+usage);throw new ParseFailure();}}private void requireExact(List<String>p,int count,int lineNo,String usage){if(p.size()!=count){program.error(lineNo,"uso: "+usage);throw new ParseFailure();}}private double number(String v,int lineNo){try{return Double.parseDouble(v);}catch(NumberFormatException e){program.error(lineNo,"número inválido: "+v);throw new ParseFailure();}}private int integer(String v,int lineNo,int min,int max,String op){try{int n=Integer.parseInt(v);if(n<min||n>max)throw new NumberFormatException();return n;}catch(NumberFormatException e){program.error(lineNo,op+" requiere un entero entre "+min+" y "+max);throw new ParseFailure();}}private double nonNegative(double v,int lineNo,String op){if(v<0){program.error(lineNo,op+" no acepta valores negativos");throw new ParseFailure();}return v;}private double unit(double v,int lineNo,String op){if(v<0||v>1){program.error(lineNo,op+" requiere volumen entre 0 y 1");throw new ParseFailure();}return v;}
    }

    private static String readPath(Context c,String path){String p=path.trim();if(p.startsWith("global."))return c.globalVariable(p.substring(7));if(p.startsWith("save."))return c.saveVariable(p.substring(5));return c.readPath(p);}
    private static void writePath(Context c,String path,String value){String p=path.trim();if(p.startsWith("global.")){c.setGlobalVariable(p.substring(7),value);return;}if(p.startsWith("save.")){c.setSaveVariable(p.substring(5),value);return;}c.writePath(p,value);}
    private static boolean compare(String left,String right,String operator){String op=operator.toLowerCase(Locale.ROOT);Double a=tryNumber(left),b=tryNumber(right);if(a!=null&&b!=null){int cmp=Double.compare(a,b);return switch(op){case"==","="->cmp==0;case"!="->cmp!=0;case">"->cmp>0;case">="->cmp>=0;case"<"->cmp<0;case"<="->cmp<=0;default->false;};}String l=left==null?"":left,r=right==null?"":right;int cmp=l.compareToIgnoreCase(r);return switch(op){case"==","="->l.equalsIgnoreCase(r);case"!="->!l.equalsIgnoreCase(r);case">"->cmp>0;case">="->cmp>=0;case"<"->cmp<0;case"<="->cmp<=0;case"contains"->l.toLowerCase(Locale.ROOT).contains(r.toLowerCase(Locale.ROOT));case"startswith"->l.toLowerCase(Locale.ROOT).startsWith(r.toLowerCase(Locale.ROOT));case"endswith"->l.toLowerCase(Locale.ROOT).endsWith(r.toLowerCase(Locale.ROOT));default->false;};}
    private static String interpolate(Context c,String text){if(text==null||text.indexOf('$')<0)return text==null?"":text;StringBuilder out=new StringBuilder();for(int i=0;i<text.length();){if(i+2<text.length()&&text.charAt(i)=='$'&&text.charAt(i+1)=='{'){int end=text.indexOf('}',i+2);if(end>i){String key=text.substring(i+2,end);String value;if(key.startsWith("global:"))value=c.globalVariable(key.substring(7));else if(key.startsWith("save:"))value=c.saveVariable(key.substring(5));else if(key.startsWith("prop:"))value=c.property(key.substring(5));else if(key.startsWith("path:"))value=readPath(c,key.substring(5));else if(key.equals("other"))value=c.otherEntity();else value=c.variable(key);out.append(value==null?"":value);i=end+1;continue;}}out.append(text.charAt(i++));}return out.toString();}
    private static List<String>tokens(String line){ArrayList<String>r=new ArrayList<>();StringBuilder cur=new StringBuilder();boolean quoted=false;for(int i=0;i<line.length();i++){char ch=line.charAt(i);if(ch=='"'){quoted=!quoted;continue;}if(Character.isWhitespace(ch)&&!quoted){if(!cur.isEmpty()){r.add(cur.toString());cur.setLength(0);}}else cur.append(ch);}if(!cur.isEmpty())r.add(cur.toString());return r;}
    private static String stripComment(String line){boolean quoted=false;for(int i=0;i<line.length();i++){char ch=line.charAt(i);if(ch=='"')quoted=!quoted;else if(ch=='#'&&!quoted){int remaining=line.length()-i-1;boolean six=remaining>=6&&isHex(line,i+1,6)&&(i+7==line.length()||Character.isWhitespace(line.charAt(i+7)));boolean eight=remaining>=8&&isHex(line,i+1,8)&&(i+9==line.length()||Character.isWhitespace(line.charAt(i+9)));if(!six&&!eight)return line.substring(0,i);}}return line;}
    private static boolean isHex(String line,int start,int length){if(start<0||start+length>line.length())return false;for(int i=start;i<start+length;i++)if(Character.digit(line.charAt(i),16)<0)return false;return true;}
    private static String join(List<String>p,int start){return String.join(" ",p.subList(start,p.size()));}private static double parseDouble(String v,double fallback){try{return Double.parseDouble(v);}catch(Exception e){return fallback;}}private static Double tryNumber(String v){try{return Double.parseDouble(v);}catch(Exception e){return null;}}private static String trimNumber(double n){return n==Math.rint(n)?Long.toString((long)n):Double.toString(n);}private static String unquote(String s){if(s.length()>=2&&s.startsWith("\"")&&s.endsWith("\""))return s.substring(1,s.length()-1);return s;}private static final class ParseFailure extends RuntimeException{}
}
