from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
def read(p):return (ROOT/p).read_text(encoding='utf-8')
def write(p,s):(ROOT/p).write_text(s,encoding='utf-8',newline='\n')
def rep(p,o,n):
 s=read(p);c=s.count(o)
 if c!=1:raise RuntimeError(f'{p}: expected 1 match, got {c}: {o[:120]}')
 write(p,s.replace(o,n,1))
def rex(p,pat,n):
 s=read(p);out,c=re.subn(pat,n,s,count=1,flags=re.S)
 if c!=1:raise RuntimeError(f'{p}: regex expected 1 match, got {c}: {pat[:120]}')
 write(p,out)

# ---------------------------------------------------------------------------
# Runtime: advanced tiles, UISkin state rendering, Animator RC features,
# animation hitbox/hurtbox contacts, directional sets, blend trees and camera.
# ---------------------------------------------------------------------------
g='src/main/java/com/buttclapdev/twogamerl/runtime/GameView.java'
rep(g,'import com.buttclapdev.twogamerl.model.GameProject;\nimport com.buttclapdev.twogamerl.model.GameProject.*;','import com.buttclapdev.twogamerl.model.GameProject;\nimport com.buttclapdev.twogamerl.model.AdvancedTileResolver;\nimport com.buttclapdev.twogamerl.model.GameProject.*;')
rep(g,'private boolean cameraInitialized;private double cameraCenterX,cameraCenterY,cameraZoomRuntime=1,cameraOffsetXRuntime,cameraOffsetYRuntime,shakeIntensity,shakeRemaining,shakeTotal,shakeX,shakeY;private boolean cameraPixelSnapRuntime=true;','private boolean cameraInitialized;private double cameraCenterX,cameraCenterY,cameraZoomRuntime=1,cameraOffsetXRuntime,cameraOffsetYRuntime,shakeIntensity,shakeRemaining,shakeTotal,shakeX,shakeY,cameraMinX=Double.NaN,cameraMinY=Double.NaN,cameraMaxX=Double.NaN,cameraMaxY=Double.NaN;private boolean cameraPixelSnapRuntime=true;')
rep(g,'button.setOnMouseClicked(e->{switch(def.action){case START_GAME->startGame(def.target);case OPEN_MENU->showMenu(def.target);case EXIT->{var w=getScene()==null?null:getScene().getWindow();if(w!=null)w.hide();}}e.consume();});','button.setOnMouseClicked(e->{if(!def.enabled){e.consume();return;}switch(def.action){case START_GAME->startGame(def.target);case OPEN_MENU->showMenu(def.target);case EXIT->{var w=getScene()==null?null:getScene().getWindow();if(w!=null)w.hide();}}e.consume();});')
rex(g,r'    private Node menuButton\(MenuButton def\)\{.*?return wrapper;\}',r'''    private Node menuButton(MenuButton def){
        UISkinAsset skin=project.getUiSkins().get(def.uiSkinKey);String normal=skin!=null&&!skin.normalAssetKey.isBlank()?skin.normalAssetKey:def.assetKey,hover=skin!=null&&!skin.hoverAssetKey.isBlank()?skin.hoverAssetKey:def.hoverAssetKey,pressed=skin==null?"":skin.pressedAssetKey,disabled=skin==null?"":skin.disabledAssetKey;
        StackPane content=new StackPane();content.setPrefSize(def.width,def.height);content.setMinSize(def.width,def.height);content.setMaxSize(def.width,def.height);String initial=!def.enabled&&!disabled.isBlank()?disabled:normal;ImageView iv=initial.isBlank()?null:pixelAsset(initial,def.width,def.height,false);if(iv!=null)content.getChildren().add(iv);else{java.awt.Color bg=skin==null?def.backgroundColor:skin.backgroundColor,border=skin==null?new java.awt.Color(75,106,132):skin.borderColor;double radius=skin==null?7:skin.radius,bw=skin==null?1:skin.borderWidth;content.setStyle("-fx-background-color:"+css(bg)+";-fx-background-radius:"+radius+";-fx-border-color:"+css(border)+";-fx-border-width:"+bw+";-fx-border-radius:"+radius+";");}
        TextStyle s=project.getTextStyles().get(def.textStyleKey);String fontKey=s==null?def.fontKey:s.fontKey;if(skin!=null&&!skin.fontKey.isBlank())fontKey=skin.fontKey;java.awt.Color text=s==null?def.textColor:s.textColor;if(skin!=null)text=def.enabled?skin.textColor:skin.disabledTextColor;Label label=new Label(def.text);label.setFont(font(fontKey,s==null?def.fontSize:s.fontSize));label.setTextFill(fx(text));label.setMouseTransparent(true);content.getChildren().add(label);
        MenuAnimation anim=skin!=null&&skin.animation!=MenuAnimation.NONE?skin.animation:def.animation;StackPane wrapper=MenuEffects.decorate(content,anim,def.animationSpeed,def.hoverEffect);wrapper.setDisable(!def.enabled);wrapper.setOpacity(def.enabled?1:.72);
        if(iv!=null&&def.enabled){if(!hover.isBlank()){content.addEventHandler(MouseEvent.MOUSE_ENTERED,e->configureAssetView(iv,hover));content.addEventHandler(MouseEvent.MOUSE_EXITED,e->configureAssetView(iv,normal));}if(!pressed.isBlank()){content.addEventHandler(MouseEvent.MOUSE_PRESSED,e->configureAssetView(iv,pressed));content.addEventHandler(MouseEvent.MOUSE_RELEASED,e->configureAssetView(iv,hover.isBlank()?normal:hover));}}
        return wrapper;
    }''')
rep(g,'checkEntityOverlaps();refreshContactSensors();applyTileSurfaceEffects(dt);','checkEntityOverlaps();checkAnimationHitboxes();refreshContactSensors();applyTileSurfaceEffects(dt);')
rep(g,'String asset=animatedTileAsset(t);if(!asset.isBlank()&&image(asset)!=null)','String asset=t.animationClip==null||t.animationClip.isBlank()?AdvancedTileResolver.assetFor(project,level,layer,x,y,t):animatedTileAsset(t);if(!asset.isBlank()&&image(asset)!=null)')
rex(g,r'    private void updateAnimator\(Body b,double dt\)\{.*?private void stopAnimation\(Body b\)\{.*?\}\n',r'''    private void updateAnimator(Body b,double dt){ComponentDef a=activeComponent(b,"Animator");if(a==null)return;String desired=a.get("state","");AnimatorController controller=project.getAnimatorControllers().get(a.get("controller",""));if(controller!=null){ensureAnimatorParameters(b,controller);if(desired.isBlank())desired=controller.defaultState;evaluateTransitions(b,a,controller,desired);desired=a.get("state",desired);}AnimatorState state=controller==null?null:controller.states.get(desired);String clipKey=resolveAnimatorClip(b,a,state,desired);if(clipKey.isBlank())clipKey=a.get("clip","");if(clipKey.isBlank())return;if(!Objects.equals(b.animationClip,clipKey))startAnimation(b,a,clipKey);if(!b.animationPlaying)return;AnimationClip clip=project.getAnimationClips().get(b.animationClip);if(clip==null||clip.frames.isEmpty())return;double stateSpeed=state==null?1:Math.max(0,state.speed),speed=Math.max(0,a.number("speed",1))*Math.max(0,clip.speed)*stateSpeed;b.frameElapsed+=dt*speed;int guard=0;while(guard++<100&&b.frameElapsed>=clip.frameDuration(Math.max(0,Math.min(clip.frames.size()-1,b.animationFrame)))){b.frameElapsed-=clip.frameDuration(b.animationFrame);int old=b.animationFrame;b.animationFrame+=b.animationDirection;if(b.animationFrame>=clip.frames.size()||b.animationFrame<0){if(clip.pingPong&&clip.frames.size()>1){b.animationDirection*=-1;b.animationFrame=Math.max(0,Math.min(clip.frames.size()-1,b.animationFrame+2*b.animationDirection));fire(b,ScriptProgram.Event.ANIMATIONLOOP,null);}else if(clip.loop){b.animationFrame=b.animationDirection>0?0:clip.frames.size()-1;fire(b,ScriptProgram.Event.ANIMATIONLOOP,null);}else{b.animationFrame=Math.max(0,Math.min(clip.frames.size()-1,b.animationFrame));b.animationPlaying=false;a.properties.put("finished","true");fire(b,ScriptProgram.Event.ANIMATIONEND,null);if(!b.queuedAnimation.isBlank()){String q=b.queuedAnimation;b.queuedAnimation="";playAnimation(b,q);}break;}}if(old!=b.animationFrame){b.frameHitTargets.clear();String event=clip.frames.get(b.animationFrame).event;if(event!=null&&!event.isBlank()){fireNamed(b,"animation:"+event,null);emitWorldEvent("animation:"+event);}}}a.properties.put("frame",Integer.toString(b.animationFrame));}
    private void ensureAnimatorParameters(Body b,AnimatorController c){if(Objects.equals(b.animatorControllerKey,c.key))return;b.animatorControllerKey=c.key;b.animatorParameters.clear();for(AnimatorParameter p:c.parameters.values())b.animatorParameters.put(p.name,p.defaultValue);}
    private String resolveAnimatorClip(Body b,ComponentDef a,AnimatorState state,String desired){String clip=state==null?"":state.clipKey;if(state!=null&&state.blendTree.type!=BlendTreeType.NONE&&!state.blendTree.children.isEmpty()){double x=animatorParamNumber(b,state.blendTree.parameterX),y=animatorParamNumber(b,state.blendTree.parameterY);BlendChild best=null;double dist=Double.MAX_VALUE;for(BlendChild child:state.blendTree.children){double d=state.blendTree.type==BlendTreeType.ONE_D?Math.abs(x-child.x):Math.hypot(x-child.x,y-child.y);if(d<dist){dist=d;best=child;}}if(best!=null&&!best.clipKey.isBlank())clip=best.clipKey;}AnimationSet set=project.getAnimationSets().get(a.get("animationSet",""));if(set!=null){String dir=directionFor(b,set.directionMode);a.properties.put("direction",dir);String mapped=set.clip(desired,dir);if(!mapped.isBlank())clip=mapped;else if(set.useFlipX&&dir.equals("RIGHT")){String left=set.clip(desired,"LEFT");if(!left.isBlank()){clip=left;a.properties.put("flipX","true");}}else if(set.useFlipX&&dir.equals("LEFT"))a.properties.put("flipX","false");}return clip==null?"":clip;}
    private String directionFor(Body b,DirectionMode mode){double x=b.vx,y=b.vy;if(Math.hypot(x,y)<1e-6)return b.lastAnimationDirection;String d;if(mode==DirectionMode.TWO)d=x<0?"LEFT":"RIGHT";else if(mode==DirectionMode.FOUR)d=Math.abs(x)>Math.abs(y)?(x<0?"LEFT":"RIGHT"):(y<0?"UP":"DOWN");else{double ax=Math.abs(x),ay=Math.abs(y);if(ax>ay*2)d=x<0?"LEFT":"RIGHT";else if(ay>ax*2)d=y<0?"UP":"DOWN";else d=(y<0?"UP_":"DOWN_")+(x<0?"LEFT":"RIGHT");}b.lastAnimationDirection=d;return d;}
    private double animatorParamNumber(Body b,String name){try{return Double.parseDouble(b.animatorParameters.getOrDefault(name,"0"));}catch(Exception e){return 0;}}
    private String transitionValue(Body b,String path){if(path!=null&&path.toLowerCase(Locale.ROOT).startsWith("param."))return b.animatorParameters.getOrDefault(path.substring(6),"0");return readEntityPath(path,b,null);}
    private void consumeTrigger(Body b,AnimatorController c,String path){if(path==null||!path.toLowerCase(Locale.ROOT).startsWith("param."))return;String name=path.substring(6);AnimatorParameter p=c.parameters.get(name);if(p!=null&&p.type==AnimatorParameterType.TRIGGER)b.animatorParameters.put(name,"false");}
    private void evaluateTransitions(Body b,ComponentDef animator,AnimatorController c,String current){for(AnimatorTransition t:c.transitions.stream().sorted(Comparator.comparingInt(x->x.priority)).toList()){if(!(t.from.equalsIgnoreCase(current)||t.from.equalsIgnoreCase("Any")||t.from.equalsIgnoreCase("AnyState")))continue;if(t.exitTime>=0&&animationProgress(b)<t.exitTime)continue;if(t.path.isBlank()||compare(transitionValue(b,t.path),t.value,t.operator)){animator.properties.put("state",t.to);consumeTrigger(b,c,t.path);break;}}}
    private double animationProgress(Body b){AnimationClip c=project.getAnimationClips().get(b.animationClip);if(c==null||c.frames.isEmpty())return 0;double elapsed=0;if(b.animationDirection>=0){for(int i=0;i<b.animationFrame&&i<c.frames.size();i++)elapsed+=c.frameDuration(i);elapsed+=b.frameElapsed;}else{for(int i=c.frames.size()-1;i>b.animationFrame;i--)elapsed+=c.frameDuration(i);elapsed+=b.frameElapsed;}return c.duration()<=0?0:elapsed/c.duration();}
    private void startAnimation(Body b,ComponentDef a,String clipKey){AnimationClip clip=project.getAnimationClips().get(clipKey);if(clip==null||clip.frames.isEmpty()){a.properties.put("finished","true");return;}b.animationClip=clipKey;if(clip.randomStart)b.animationFrame=ThreadLocalRandom.current().nextInt(clip.frames.size());else b.animationFrame=clip.reverse?clip.frames.size()-1:0;b.animationDirection=clip.reverse?-1:1;b.frameElapsed=0;b.animationPlaying=true;b.frameHitTargets.clear();a.properties.put("clip",clipKey);a.properties.put("frame",Integer.toString(b.animationFrame));a.properties.put("finished","false");fire(b,ScriptProgram.Event.ANIMATIONSTART,null);}
    private void playAnimation(Body b,String clipOrState){ComponentDef a=b==null?null:b.def.component("Animator");if(a==null&&b!=null){a=ComponentDef.preset("Animator");b.def.components.add(a);}if(a==null)return;AnimatorController c=project.getAnimatorControllers().get(a.get("controller",""));if(c!=null&&c.states.containsKey(clipOrState)){a.properties.put("state",clipOrState);b.animationClip="";}else startAnimation(b,a,clipOrState);}
    private void queueAnimation(Body b,String clipOrState){if(b!=null)b.queuedAnimation=clipOrState==null?"":clipOrState;}private void stopAnimation(Body b){if(b==null)return;b.animationPlaying=false;ComponentDef a=b.def.component("Animator");if(a!=null)a.properties.put("finished","true");}
''')
# Animator.param.<name> path support.
rex(g,r'    private String readEntityPath\(String path,Body self,Body other\)\{.*?\}\n    private void writeEntityPath\(String path,String value,Body self,Body other\)\{.*?\}\n',r'''    private String readEntityPath(String path,Body self,Body other){String[]p=path.split("\\.");if(p.length==0)return"";Body target=self;int i=0;if(p[0].equalsIgnoreCase("self")||p[0].equalsIgnoreCase("this")){target=self;i=1;}else if(p[0].equalsIgnoreCase("other")){target=other;i=1;}else if(p.length>=2){Body named=resolveBody(p[0],self,other);if(named!=null){target=named;i=1;}}if(target==null)return"";if(i>=p.length)return"";if(i+2<p.length&&p[i].equalsIgnoreCase("Animator")&&p[i+1].equalsIgnoreCase("param"))return target.animatorParameters.getOrDefault(p[i+2],"0");if(i+1<p.length){ComponentDef c=target.def.component(p[i]);if(c!=null)return c.get(p[i+1],"");}return bodyProperty(target,p[i]);}
    private void writeEntityPath(String path,String value,Body self,Body other){String[]p=path.split("\\.");if(p.length==0)return;Body target=self;int i=0;if(p[0].equalsIgnoreCase("self")||p[0].equalsIgnoreCase("this")){target=self;i=1;}else if(p[0].equalsIgnoreCase("other")){target=other;i=1;}else if(p.length>=2){Body named=resolveBody(p[0],self,other);if(named!=null){target=named;i=1;}}if(target==null||i>=p.length)return;if(i+2<p.length&&p[i].equalsIgnoreCase("Animator")&&p[i+1].equalsIgnoreCase("param")){ComponentDef a=target.def.component("Animator");AnimatorController c=a==null?null:project.getAnimatorControllers().get(a.get("controller",""));if(c!=null)ensureAnimatorParameters(target,c);AnimatorParameter def=c==null?null:c.parameters.get(p[i+2]);String v=value;if(def!=null){try{v=switch(def.type){case BOOL,TRIGGER->Boolean.toString(Boolean.parseBoolean(value));case INT->Integer.toString((int)Math.round(Double.parseDouble(value)));case FLOAT->number(Double.parseDouble(value));};}catch(Exception ex){logger.accept("[Animator] Parámetro inválido "+p[i+2]+" = "+value);return;}}target.animatorParameters.put(p[i+2],v);return;}if(i+1<p.length){ComponentDef c=target.def.component(p[i]);if(c!=null){String prop=p[i+1];if(c.type.equals("Rigidbody2D")&&Set.of("grounded","touchingLeft","touchingRight","touchingTop").contains(prop))return;c.properties.put(prop,value);if(c.type.equals("Health"))normalizeHealth(target);if(c.type.equals("GridMovement"))normalizeGrid(target);if(c.type.equals("Animator")&&prop.equals("state")){target.animationClip="";}if(c.type.equals("ParticleEmitter2D")&&(prop.equals("preset")||prop.equals("playing"))){target.particleBurstDone=false;target.particleAccumulator=0;}return;}}setBodyProperty(target,p[i],value);}
''')
# Hitbox/hurtbox runtime contacts.
insert='''    private Body resolveBody(String ref,Body self,Body other){'''
hit=r'''    private void checkAnimationHitboxes(){List<Body>live=bodies.values().stream().filter(b->!b.destroyed&&b.def.enabled).toList();for(Body attacker:live){List<FrameShape>hits=frameShapes(attacker,FrameShapeRole.HITBOX);if(hits.isEmpty())continue;for(Body target:live){if(target==attacker||attacker.frameHitTargets.contains(target.def.id))continue;List<FrameShape>hurts=frameShapes(target,FrameShapeRole.HURTBOX);if(hurts.isEmpty())continue;boolean overlap=false;for(FrameShape h:hits)for(FrameShape u:hurts)if(intersects(shapeRect(attacker,h),shapeRect(target,u))){overlap=true;break;}if(!overlap)continue;attacker.frameHitTargets.add(target.def.id);fireNamed(attacker,"hitbox",target);fireNamed(target,"hurtbox",attacker);emitWorldEvent("animationHit");ComponentDef damage=activeComponent(attacker,"DamageOnContact");if(damage!=null)applyDamage(target,Math.max(0,damage.number("damage",0)),attacker);}}}
    private List<FrameShape> frameShapes(Body b,FrameShapeRole role){AnimationClip c=project.getAnimationClips().get(b.animationClip);if(c==null||b.animationFrame<0||b.animationFrame>=c.frames.size())return List.of();return c.frames.get(b.animationFrame).shapes.stream().filter(s->s.role==role).toList();}
    private HitRect shapeRect(Body b,FrameShape s){ComponentDef a=activeComponent(b,"Animator");boolean fx=a!=null&&a.bool("flipX",false),fy=a!=null&&a.bool("flipY",false);double x=fx?b.def.width-s.x-s.width:s.x,y=fy?b.def.height-s.y-s.height:s.y;return new HitRect(b.def.x+x,b.def.y+y,s.width,s.height);}
    private static boolean intersects(HitRect a,HitRect b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
    private void fireNamed(Body body,String name,Body other){if(body==null)return;ensureProgram(body);if(body.program!=null&&body.program.validation().valid())body.program.fireEvent(name,new ScriptContext(body,other));}
    private void emitWorldEvent(String name){if(sceneProgram!=null&&sceneProgram.validation().valid())sceneProgram.fireEvent(name,new WorldScriptContext(null));for(TileLayer l:level.tileLayers){ScriptProgram p=layerPrograms.get(l.id);if(p!=null&&p.validation().valid())p.fireEvent(name,new WorldScriptContext(l));}}

    private Body resolveBody(String ref,Body self,Body other){'''
rep(g,insert,hit)
# Camera bounds and animated zoom.
rex(g,r'    private void updateCamera\(double dt\)\{.*?\n    private void cameraShake',r'''    private void updateCamera(double dt){if(level==null)return;Body cameraBody=bodies.values().stream().filter(b->activeComponent(b,"Camera2D")!=null).max(Comparator.comparingDouble(b->activeComponent(b,"Camera2D").number("priority",0))).orElse(null);String target=level.cameraTarget;double zoom=Math.max(.05,level.cameraZoom),offX=level.cameraOffsetX,offY=level.cameraOffsetY,smooth=0,zoomSpeed=0,deadX=0,deadY=0;boolean snap=level.cameraPixelSnap;cameraMinX=cameraMinY=cameraMaxX=cameraMaxY=Double.NaN;if(cameraBody!=null){ComponentDef c=activeComponent(cameraBody,"Camera2D");target=c.get("target",target);if(target.isBlank()&&c.bool("follow",true))target=cameraBody.def.id;zoom=Math.max(.05,c.number("zoom",zoom));zoomSpeed=Math.max(0,c.number("zoomSpeed",0));offX=c.number("offsetX",offX);offY=c.number("offsetY",offY);snap=c.bool("pixelSnap",snap);smooth=Math.max(0,c.number("smoothSpeed",0));deadX=Math.max(0,c.number("deadZoneX",0));deadY=Math.max(0,c.number("deadZoneY",0));cameraMinX=optionalNumber(c,"minX");cameraMinY=optionalNumber(c,"minY");cameraMaxX=optionalNumber(c,"maxX");cameraMaxY=optionalNumber(c,"maxY");if(!cameraInitialized&&c.number("shakeDuration",0)>0)cameraShake(Math.max(0,c.number("shakeIntensity",0)),Math.max(0,c.number("shakeDuration",0)));}Body t=resolveBody(target,null,null);if(t==null)t=bodies.values().stream().filter(this::isPlayerControlled).findFirst().orElse(null);double desiredX=t==null?level.width/2.0:t.def.x+t.def.width/2,desiredY=t==null?level.height/2.0:t.def.y+t.def.height/2;boolean first=!cameraInitialized;if(first){cameraCenterX=desiredX;cameraCenterY=desiredY;cameraZoomRuntime=zoom;cameraInitialized=true;}else{if(deadX>0){double half=deadX/2,delta=desiredX-cameraCenterX;if(Math.abs(delta)<=half)desiredX=cameraCenterX;else desiredX=cameraCenterX+Math.copySign(Math.abs(delta)-half,delta);}if(deadY>0){double half=deadY/2,delta=desiredY-cameraCenterY;if(Math.abs(delta)<=half)desiredY=cameraCenterY;else desiredY=cameraCenterY+Math.copySign(Math.abs(delta)-half,delta);}double factor=smooth<=0||dt<=0?1:1-Math.exp(-smooth*dt);cameraCenterX+=(desiredX-cameraCenterX)*factor;cameraCenterY+=(desiredY-cameraCenterY)*factor;double zf=zoomSpeed<=0||dt<=0?1:1-Math.exp(-zoomSpeed*dt);cameraZoomRuntime+=(zoom-cameraZoomRuntime)*zf;}cameraOffsetXRuntime=offX;cameraOffsetYRuntime=offY;cameraPixelSnapRuntime=snap;if(shakeRemaining>0){shakeRemaining=Math.max(0,shakeRemaining-Math.max(0,dt));double fade=shakeTotal<=0?0:shakeRemaining/shakeTotal,world=Math.max(0,shakeIntensity)*fade/Math.max(1,project.getTileSize());shakeX=(ThreadLocalRandom.current().nextDouble()*2-1)*world;shakeY=(ThreadLocalRandom.current().nextDouble()*2-1)*world;}else shakeX=shakeY=0;}
    private static double optionalNumber(ComponentDef c,String key){try{String v=c.get(key,"");return v==null||v.isBlank()?Double.NaN:Double.parseDouble(v);}catch(Exception e){return Double.NaN;}}
    private void cameraShake''')
rex(g,r'    private Viewport viewport\(\)\{.*?return new Viewport\(tile,ox,oy,contentW,contentH,scale,cameraX,cameraY\);\}',r'''    private Viewport viewport(){double cw=Math.max(1,canvas.getWidth()),ch=Math.max(1,canvas.getHeight()),lw=Math.max(1,project.getLogicalWidth()),lh=Math.max(1,project.getLogicalHeight()),scale;if(project.getScaleMode()==ScaleMode.STRETCH){double sx=cw/lw,sy=ch/lh;scale=Math.min(sx,sy);}else{double raw=Math.min(cw/lw,ch/lh);scale=project.isIntegerScale()&&raw>=1?Math.max(1,Math.floor(raw)):Math.max(.05,raw);}double contentW=lw*scale,contentH=lh*scale,ox=Math.floor((cw-contentW)/2),oy=Math.floor((ch-contentH)/2);if(!cameraInitialized)updateCamera(0);CameraState camera=cameraState();double tile=Math.max(.1,project.getTileSize()*scale*camera.zoom),viewW=lw/(project.getTileSize()*camera.zoom),viewH=lh/(project.getTileSize()*camera.zoom),cameraX=camera.centerX-viewW/2+camera.offsetX,cameraY=camera.centerY-viewH/2+camera.offsetY;double minX=Double.isFinite(cameraMinX)?cameraMinX:0,minY=Double.isFinite(cameraMinY)?cameraMinY:0,maxX=Double.isFinite(cameraMaxX)?cameraMaxX:level.width,maxY=Double.isFinite(cameraMaxY)?cameraMaxY:level.height;if(maxX<=minX){minX=0;maxX=level.width;}if(maxY<=minY){minY=0;maxY=level.height;}if(maxX-minX<=viewW)cameraX=minX+(maxX-minX-viewW)/2;else cameraX=Math.max(minX,Math.min(maxX-viewW,cameraX));if(maxY-minY<=viewH)cameraY=minY+(maxY-minY-viewH)/2;else cameraY=Math.max(minY,Math.min(maxY-viewH,cameraY));if(camera.pixelSnap){double step=1.0/Math.max(1,project.getTileSize());cameraX=Math.rint(cameraX/step)*step;cameraY=Math.rint(cameraY/step)*step;}return new Viewport(tile,ox,oy,contentW,contentH,scale,cameraX,cameraY);}''')
# Body runtime state + hit rect.
rep(g,'private static final class Body {final EntityDef def;double vx,vy,originX,originY,gridNextAt,gridMoveStart,gridMoveEnd,visualFromX,visualFromY,tileDamageAccumulator;int patrolDirection=1;boolean destroyed,destroying,triggerConsumed,grounded,touchingLeft,touchingRight,touchingTop;String scriptSource="";ScriptProgram program;String animationClip="",queuedAnimation="";int animationFrame,animationDirection=1;double frameElapsed,particleAccumulator;boolean animationPlaying,particleBurstDone,particlePlayingLast,particleLimitWarned;String particlePresetKey="",particleMissingRef="";Body(EntityDef def){this.def=def;originX=def.x;originY=def.y;visualFromX=def.x;visualFromY=def.y;}}','private static final class Body {final EntityDef def;double vx,vy,originX,originY,gridNextAt,gridMoveStart,gridMoveEnd,visualFromX,visualFromY,tileDamageAccumulator;int patrolDirection=1;boolean destroyed,destroying,triggerConsumed,grounded,touchingLeft,touchingRight,touchingTop;String scriptSource="";ScriptProgram program;String animationClip="",queuedAnimation="",animatorControllerKey="",lastAnimationDirection="DOWN";final LinkedHashMap<String,String>animatorParameters=new LinkedHashMap<>();final HashSet<String>frameHitTargets=new HashSet<>();int animationFrame,animationDirection=1;double frameElapsed,particleAccumulator;boolean animationPlaying,particleBurstDone,particlePlayingLast,particleLimitWarned;String particlePresetKey="",particleMissingRef="";Body(EntityDef def){this.def=def;originX=def.x;originY=def.y;visualFromX=def.x;visualFromY=def.y;}}')
rep(g,'private record ScheduledAction(double due,long order,Runnable action){}private record Block(Body other,TileDef tile){}','private record HitRect(double x,double y,double w,double h){}private record ScheduledAction(double due,long order,Runnable action){}private record Block(Body other,TileDef tile){}')

# ---------------------------------------------------------------------------
# Text overlays: reusable UISkin resources also skin BUBBLE/NOVEL panels.
# ---------------------------------------------------------------------------
t='src/main/java/com/buttclapdev/twogamerl/runtime/TextOverlayLayer.java'
rep(t,'import com.buttclapdev.twogamerl.model.GameProject.TextStyle;','import com.buttclapdev.twogamerl.model.GameProject.TextStyle;\nimport com.buttclapdev.twogamerl.model.GameProject.UISkinAsset;')
rep(t,'        if(style!=null)return style;','        if(style!=null)return applyUiSkin(style);')
rep(t,'    private Node free(String text,TextStyle s){','    private TextStyle applyUiSkin(TextStyle source){UISkinAsset skin=source.uiSkinKey==null||source.uiSkinKey.isBlank()?null:project.getUiSkins().get(source.uiSkinKey);if(skin==null)return source;TextStyle s=source.copy();if(s.fontKey.isBlank())s.fontKey=skin.fontKey;if(!skin.normalAssetKey.isBlank())s.skinAssetKey=skin.normalAssetKey;s.textColor=skin.textColor;s.backgroundColor=skin.backgroundColor;s.borderColor=skin.borderColor;s.paddingX=skin.paddingX;s.paddingY=skin.paddingY;s.borderWidth=skin.borderWidth;s.radius=skin.radius;return s;}\n\n    private Node free(String text,TextStyle s){')

# ---------------------------------------------------------------------------
# 2GameScript: bounded while loops. This removes the most restrictive loop
# limitation without allowing an unbounded event to freeze the runtime.
# ---------------------------------------------------------------------------
s='src/main/java/com/buttclapdev/twogamerl/script/ScriptProgram.java'
rep(s,'    private record RepeatInstruction(int count,List<Instruction>body) implements Instruction {}','    private record RepeatInstruction(int count,List<Instruction>body) implements Instruction {}\n    private record WhileInstruction(Condition condition,List<Instruction>body,int limit) implements Instruction {}\n    private record WhileStepInstruction(Condition condition,List<Instruction>body,int remaining) implements Instruction {}')
rep(s,'private static void executeQueue(ArrayDeque<Instruction>q,Context c){int guard=0;while(!q.isEmpty()&&guard++<100000){Instruction i=q.removeFirst();if(i instanceof WaitInstruction w){ArrayDeque<Instruction>cont=new ArrayDeque<>(q);c.schedule(w.seconds(),()->executeQueue(cont,c));return;}if(i instanceof IfInstruction f){pushFront(q,f.condition().test(c)?f.yes():f.no());continue;}if(i instanceof RepeatInstruction r){for(int n=0;n<r.count();n++)pushFront(q,r.body());continue;}if(i==StopInstruction.INSTANCE)return;try{i.run(c);}catch(RuntimeException ex){c.log("Script: "+(ex.getMessage()==null?ex.getClass().getSimpleName():ex.getMessage()));}}if(guard>=100000)c.log("Script: se alcanzó el límite de instrucciones de un evento.");}','private static void executeQueue(ArrayDeque<Instruction>q,Context c){int guard=0;while(!q.isEmpty()&&guard++<100000){Instruction i=q.removeFirst();if(i instanceof WaitInstruction w){ArrayDeque<Instruction>cont=new ArrayDeque<>(q);c.schedule(w.seconds(),()->executeQueue(cont,c));return;}if(i instanceof IfInstruction f){pushFront(q,f.condition().test(c)?f.yes():f.no());continue;}if(i instanceof RepeatInstruction r){for(int n=0;n<r.count();n++)pushFront(q,r.body());continue;}if(i instanceof WhileInstruction w){q.addFirst(new WhileStepInstruction(w.condition(),w.body(),w.limit()));continue;}if(i instanceof WhileStepInstruction w){if(!w.condition().test(c))continue;if(w.remaining()<=0){c.log("Script: while alcanzó el límite de 10000 iteraciones.");continue;}q.addFirst(new WhileStepInstruction(w.condition(),w.body(),w.remaining()-1));pushFront(q,w.body());continue;}if(i==StopInstruction.INSTANCE)return;try{i.run(c);}catch(RuntimeException ex){c.log("Script: "+(ex.getMessage()==null?ex.getClass().getSimpleName():ex.getMessage()));}}if(guard>=100000)c.log("Script: se alcanzó el límite de instrucciones de un evento.");}')
rep(s,'if(op.equals("repeat")&&parts.size()==2){int count=integer(parts.get(1),line.number(),0,10000,"repeat");index++;Block body=parseBlock(false);if(!body.closed())program.error(line.number(),"falta \'end\' para cerrar repeat");result.add(new RepeatInstruction(count,List.copyOf(body.instructions())));continue;}Instruction instruction=parseInstruction(line.number(),line.text());','if(op.equals("while")){if(parts.size()<4){program.error(line.number(),"uso: while <ruta> <operador> <valor>");index++;continue;}ArrayList<String>condParts=new ArrayList<>(parts);condParts.set(0,"if");Condition condition=parseCondition(line.number(),condParts);index++;Block body=parseBlock(false);if(!body.closed())program.error(line.number(),"falta \'end\' para cerrar while");if(condition!=null)result.add(new WhileInstruction(condition,List.copyOf(body.instructions()),10000));continue;}if(op.equals("repeat")&&parts.size()==2){int count=integer(parts.get(1),line.number(),0,10000,"repeat");index++;Block body=parseBlock(false);if(!body.closed())program.error(line.number(),"falta \'end\' para cerrar repeat");result.add(new RepeatInstruction(count,List.copyOf(body.instructions())));continue;}Instruction instruction=parseInstruction(line.number(),line.text());')

print('RC phase B runtime/scripting staged')
