from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]

def read(p): return (ROOT/p).read_text(encoding='utf-8')
def write(p,s): (ROOT/p).write_text(s,encoding='utf-8',newline='\n')
def rep(p,old,new):
    s=read(p); n=s.count(old)
    if n!=1: raise RuntimeError(f'{p}: expected 1 match, got {n}: {old[:100]}')
    write(p,s.replace(old,new,1))
def rex(p,pattern,new):
    s=read(p); out,n=re.subn(pattern,new,s,count=1,flags=re.S)
    if n!=1: raise RuntimeError(f'{p}: regex expected 1 match, got {n}: {pattern[:100]}')
    write(p,out)

# ---------------------------------------------------------------------------
# Version/model: complete the resource model required by the first RC.
# ---------------------------------------------------------------------------
pom='pom.xml'
rep(pom,'    <version>2.2.2</version>','    <version>2.3.0-rc1</version>')

model='src/main/java/com/buttclapdev/twogamerl/model/GameProject.java'
rep(model,'    public static final int FORMAT_VERSION = 8;','    public static final int FORMAT_VERSION = 9;')
rep(model,
'''    private final LinkedHashMap<String, ParticlePreset> particlePresets = new LinkedHashMap<>();
    private final List<String> renderLayers = new ArrayList<>();''',
'''    private final LinkedHashMap<String, ParticlePreset> particlePresets = new LinkedHashMap<>();
    private final LinkedHashMap<String, UISkinAsset> uiSkins = new LinkedHashMap<>();
    private final LinkedHashMap<String, AnimationSet> animationSets = new LinkedHashMap<>();
    private final LinkedHashMap<String, StampPattern> stampPatterns = new LinkedHashMap<>();
    private final List<String> renderLayers = new ArrayList<>();''')
rep(model,
'''        c.textStyles.clear();textStyles.forEach((k,v)->c.textStyles.put(k,v.copy()));c.animationClips.clear();animationClips.forEach((k,v)->c.animationClips.put(k,v.copy()));c.animatorControllers.clear();animatorControllers.forEach((k,v)->c.animatorControllers.put(k,v.copy()));c.prefabs.clear();prefabs.forEach((k,v)->c.prefabs.put(k,v.copy()));c.inputActions.clear();inputActions.forEach((k,v)->c.inputActions.put(k,v.copy()));c.palettes.clear();palettes.forEach((k,v)->c.palettes.put(k,v.copy()));c.particlePresets.clear();particlePresets.forEach((k,v)->c.particlePresets.put(k,v.copy()));return c;''',
'''        c.textStyles.clear();textStyles.forEach((k,v)->c.textStyles.put(k,v.copy()));c.animationClips.clear();animationClips.forEach((k,v)->c.animationClips.put(k,v.copy()));c.animatorControllers.clear();animatorControllers.forEach((k,v)->c.animatorControllers.put(k,v.copy()));c.prefabs.clear();prefabs.forEach((k,v)->c.prefabs.put(k,v.copy()));c.inputActions.clear();inputActions.forEach((k,v)->c.inputActions.put(k,v.copy()));c.palettes.clear();palettes.forEach((k,v)->c.palettes.put(k,v.copy()));c.particlePresets.clear();particlePresets.forEach((k,v)->c.particlePresets.put(k,v.copy()));c.uiSkins.clear();uiSkins.forEach((k,v)->c.uiSkins.put(k,v.copy()));c.animationSets.clear();animationSets.forEach((k,v)->c.animationSets.put(k,v.copy()));c.stampPatterns.clear();stampPatterns.forEach((k,v)->c.stampPatterns.put(k,v.copy()));return c;''')
rep(model,
'''    public Map<String,TextStyle> getTextStyles(){return textStyles;} public Map<String,AnimationClip> getAnimationClips(){return animationClips;} public Map<String,AnimatorController> getAnimatorControllers(){return animatorControllers;} public Map<String,PrefabDef> getPrefabs(){return prefabs;} public Map<String,InputAction> getInputActions(){return inputActions;} public Map<String,PaletteAsset> getPalettes(){return palettes;} public Map<String,ParticlePreset> getParticlePresets(){return particlePresets;}''',
'''    public Map<String,TextStyle> getTextStyles(){return textStyles;} public Map<String,AnimationClip> getAnimationClips(){return animationClips;} public Map<String,AnimatorController> getAnimatorControllers(){return animatorControllers;} public Map<String,PrefabDef> getPrefabs(){return prefabs;} public Map<String,InputAction> getInputActions(){return inputActions;} public Map<String,PaletteAsset> getPalettes(){return palettes;} public Map<String,ParticlePreset> getParticlePresets(){return particlePresets;} public Map<String,UISkinAsset> getUiSkins(){return uiSkins;} public Map<String,AnimationSet> getAnimationSets(){return animationSets;} public Map<String,StampPattern> getStampPatterns(){return stampPatterns;}''')
rep(model,
'''    public enum PlacementMode { AUTO, TILEMAP, ENTITY }
    public enum AnimationCategory { ENTITY, UI, VFX, TILE }''',
'''    public enum PlacementMode { AUTO, TILEMAP, ENTITY }
    public enum AnimationCategory { ENTITY, UI, VFX, TILE }
    public enum TileAutotileMode { NONE, FOUR_WAY, EIGHT_WAY }
    public enum FrameShapeRole { HITBOX, HURTBOX }
    public enum AnimatorParameterType { BOOL, INT, FLOAT, TRIGGER }
    public enum BlendTreeType { NONE, ONE_D, TWO_D }
    public enum DirectionMode { TWO, FOUR, EIGHT }''')
rex(model,r'''    public static final class TileDef \{.*?\n    \}\n\n    public static final class Asset \{''',r'''    public static final class TileVariant {public String assetKey="";public double weight=1;public TileVariant(){}public TileVariant(String assetKey,double weight){this.assetKey=assetKey==null?"":assetKey;this.weight=Math.max(0,weight);}public TileVariant copy(){return new TileVariant(assetKey,weight);}}
    public static final class TileDef {
        public final int id; public String name; public Color color; public boolean walkable; public String assetKey; public boolean oneWay; public double friction=1,damage; public String animationClip=""; public final LinkedHashSet<String>tags=new LinkedHashSet<>();
        public TileAutotileMode autotileMode=TileAutotileMode.NONE;public String connectTag="";public final List<TileVariant>variants=new ArrayList<>();public final LinkedHashMap<Integer,String>autotileAssets=new LinkedHashMap<>();
        public TileDef(int id,String name,Color color,boolean walkable,String assetKey){this.id=id;this.name=name;this.color=color;this.walkable=walkable;this.assetKey=assetKey==null?"":assetKey;}
        public boolean solid(){return !walkable;} public TileDef copy(){TileDef c=new TileDef(id,name,color,walkable,assetKey);c.oneWay=oneWay;c.friction=friction;c.damage=damage;c.animationClip=animationClip;c.tags.addAll(tags);c.autotileMode=autotileMode;c.connectTag=connectTag;variants.forEach(v->c.variants.add(v.copy()));c.autotileAssets.putAll(autotileAssets);return c;} @Override public String toString(){return name;}
    }

    public static final class Asset {''')
rep(model,
'''        public final String key; public String sourceName; public byte[] data; public boolean sourceOnly; public String sourceAssetKey=""; public int regionX,regionY,regionWidth,regionHeight; public FilterMode filterMode=FilterMode.PIXEL; public AssetCategory category=AssetCategory.IMAGE; public double pivotX=.5,pivotY=.5; public String sourcePath=""; public long sourceModified; public int sliceTop,sliceBottom,sliceLeft,sliceRight; public final LinkedHashSet<String>tags=new LinkedHashSet<>(); private transient BufferedImage image;''',
'''        public final String key; public String sourceName; public byte[] data; public boolean sourceOnly,favorite; public String sourceAssetKey="",folder=""; public int regionX,regionY,regionWidth,regionHeight; public FilterMode filterMode=FilterMode.PIXEL; public AssetCategory category=AssetCategory.IMAGE; public double pivotX=.5,pivotY=.5; public String sourcePath=""; public long sourceModified; public int sliceTop,sliceBottom,sliceLeft,sliceRight; public final LinkedHashSet<String>tags=new LinkedHashSet<>(); private transient BufferedImage image;''')
rep(model,
'''        public Asset copy(){Asset c=isRegion()?new Asset(key,sourceName,sourceAssetKey,regionX,regionY,regionWidth,regionHeight):new Asset(key,sourceName,data==null?null:data.clone(),sourceOnly);c.sourceOnly=sourceOnly;c.filterMode=filterMode;c.category=category;c.pivotX=pivotX;c.pivotY=pivotY;c.sourcePath=sourcePath;c.sourceModified=sourceModified;c.sliceTop=sliceTop;c.sliceBottom=sliceBottom;c.sliceLeft=sliceLeft;c.sliceRight=sliceRight;c.tags.addAll(tags);return c;} @Override public String toString(){return (sourceOnly&&!isRegion()?"[Hoja] ":isRegion()?"[Región] ":"")+(sourceName==null?key:sourceName);}''',
'''        public Asset copy(){Asset c=isRegion()?new Asset(key,sourceName,sourceAssetKey,regionX,regionY,regionWidth,regionHeight):new Asset(key,sourceName,data==null?null:data.clone(),sourceOnly);c.sourceOnly=sourceOnly;c.favorite=favorite;c.folder=folder;c.filterMode=filterMode;c.category=category;c.pivotX=pivotX;c.pivotY=pivotY;c.sourcePath=sourcePath;c.sourceModified=sourceModified;c.sliceTop=sliceTop;c.sliceBottom=sliceBottom;c.sliceLeft=sliceLeft;c.sliceRight=sliceRight;c.tags.addAll(tags);return c;} @Override public String toString(){return (favorite?"★ ":"")+(sourceOnly&&!isRegion()?"[Hoja] ":isRegion()?"[Región] ":"")+(sourceName==null?key:sourceName);}''')
rep(model,
'''        public final String key; public String name,fontKey="",skinAssetKey=""; public int fontSize=18,speakerFontSize=16;''',
'''        public final String key; public String name,fontKey="",skinAssetKey="",uiSkinKey=""; public int fontSize=18,speakerFontSize=16;''')
rep(model,
'''        public TextStyle(String key,String name){this.key=key;this.name=name;} public TextStyle copy(){TextStyle c=new TextStyle(key,name);c.fontKey=fontKey;c.skinAssetKey=skinAssetKey;c.fontSize=fontSize;''',
'''        public TextStyle(String key,String name){this.key=key;this.name=name;} public TextStyle copy(){TextStyle c=new TextStyle(key,name);c.fontKey=fontKey;c.skinAssetKey=skinAssetKey;c.uiSkinKey=uiSkinKey;c.fontSize=fontSize;''')
rex(model,r'''    public static final class AnimationFrame \{.*?    public static final class AnimatorController \{.*?\}\n''',r'''    public static final class FrameShape {public String name="shape";public FrameShapeRole role=FrameShapeRole.HITBOX;public double x,y,width=.5,height=.5;public FrameShape(){}public FrameShape(String name,FrameShapeRole role,double x,double y,double width,double height){this.name=name==null?"shape":name;this.role=role==null?FrameShapeRole.HITBOX:role;this.x=x;this.y=y;this.width=Math.max(.001,width);this.height=Math.max(.001,height);}public FrameShape copy(){return new FrameShape(name,role,x,y,width,height);}}
    public static final class AnimationFrame {public String assetKey;public double duration=.1;public String event="";public final List<FrameShape>shapes=new ArrayList<>();public AnimationFrame(String assetKey,double duration){this.assetKey=assetKey;this.duration=Math.max(.01,duration);}public AnimationFrame copy(){AnimationFrame c=new AnimationFrame(assetKey,duration);c.event=event;shapes.forEach(s->c.shapes.add(s.copy()));return c;}}
    public static final class AnimationClip {public final String key;public String name;public AnimationCategory category=AnimationCategory.ENTITY;public final List<AnimationFrame>frames=new ArrayList<>();public boolean loop=true,pingPong,randomStart,reverse;public double speed=1,fps;public AnimationClip(String key,String name){this.key=key;this.name=name;}public double frameDuration(int index){if(fps>0)return 1.0/fps;if(index<0||index>=frames.size())return .1;return Math.max(.01,frames.get(index).duration);}public double duration(){if(fps>0)return frames.isEmpty()?0:frames.size()/fps;return frames.stream().mapToDouble(f->Math.max(.01,f.duration)).sum();}public AnimationClip copy(){AnimationClip c=new AnimationClip(key,name);c.category=category;c.loop=loop;c.pingPong=pingPong;c.randomStart=randomStart;c.reverse=reverse;c.speed=speed;c.fps=fps;frames.forEach(f->c.frames.add(f.copy()));return c;}@Override public String toString(){return name;}}
    public static final class AnimatorParameter {public String name;public AnimatorParameterType type=AnimatorParameterType.FLOAT;public String defaultValue="0";public AnimatorParameter(String name,AnimatorParameterType type,String defaultValue){this.name=name;this.type=type==null?AnimatorParameterType.FLOAT:type;this.defaultValue=defaultValue==null?"0":defaultValue;}public AnimatorParameter copy(){return new AnimatorParameter(name,type,defaultValue);}}
    public static final class BlendChild {public String clipKey="";public double x,y;public BlendChild(){}public BlendChild(String clipKey,double x,double y){this.clipKey=clipKey==null?"":clipKey;this.x=x;this.y=y;}public BlendChild copy(){return new BlendChild(clipKey,x,y);}}
    public static final class BlendTree {public BlendTreeType type=BlendTreeType.NONE;public String parameterX="",parameterY="";public final List<BlendChild>children=new ArrayList<>();public BlendTree copy(){BlendTree b=new BlendTree();b.type=type;b.parameterX=parameterX;b.parameterY=parameterY;children.forEach(c->b.children.add(c.copy()));return b;}}
    public static final class AnimatorState {public String name,clipKey;public double speed=1;public final BlendTree blendTree=new BlendTree();public AnimatorState(String name,String clipKey){this.name=name;this.clipKey=clipKey;}public AnimatorState copy(){AnimatorState c=new AnimatorState(name,clipKey);c.speed=speed;c.blendTree.type=blendTree.type;c.blendTree.parameterX=blendTree.parameterX;c.blendTree.parameterY=blendTree.parameterY;blendTree.children.forEach(v->c.blendTree.children.add(v.copy()));return c;}@Override public String toString(){return name;}}
    public static final class AnimatorTransition {public String from,to,path="",operator="==",value="true";public double exitTime=-1;public int priority;public AnimatorTransition(String from,String to){this.from=from;this.to=to;}public AnimatorTransition copy(){AnimatorTransition c=new AnimatorTransition(from,to);c.path=path;c.operator=operator;c.value=value;c.exitTime=exitTime;c.priority=priority;return c;}}
    public static final class AnimatorController {public final String key;public String name,defaultState="";public final LinkedHashMap<String,AnimatorParameter>parameters=new LinkedHashMap<>();public final LinkedHashMap<String,AnimatorState>states=new LinkedHashMap<>();public final List<AnimatorTransition>transitions=new ArrayList<>();public AnimatorController(String key,String name){this.key=key;this.name=name;}public AnimatorController copy(){AnimatorController c=new AnimatorController(key,name);c.defaultState=defaultState;parameters.forEach((k,v)->c.parameters.put(k,v.copy()));states.forEach((k,v)->c.states.put(k,v.copy()));transitions.forEach(t->c.transitions.add(t.copy()));return c;}@Override public String toString(){return name;}}

    public static final class UISkinAsset {public final String key;public String name,normalAssetKey="",hoverAssetKey="",pressedAssetKey="",disabledAssetKey="",fontKey="";public Color textColor=Color.WHITE,disabledTextColor=new Color(170,170,170),backgroundColor=new Color(31,115,170),borderColor=new Color(75,106,132);public double paddingX=12,paddingY=8,borderWidth=1,radius=7;public MenuAnimation animation=MenuAnimation.NONE;public UISkinAsset(String key,String name){this.key=key;this.name=name==null?key:name;}public UISkinAsset copy(){UISkinAsset c=new UISkinAsset(key,name);c.normalAssetKey=normalAssetKey;c.hoverAssetKey=hoverAssetKey;c.pressedAssetKey=pressedAssetKey;c.disabledAssetKey=disabledAssetKey;c.fontKey=fontKey;c.textColor=textColor;c.disabledTextColor=disabledTextColor;c.backgroundColor=backgroundColor;c.borderColor=borderColor;c.paddingX=paddingX;c.paddingY=paddingY;c.borderWidth=borderWidth;c.radius=radius;c.animation=animation;return c;}@Override public String toString(){return name;}}
    public static final class AnimationSet {public final String key;public String name;public DirectionMode directionMode=DirectionMode.FOUR;public boolean useFlipX;public final LinkedHashMap<String,String>clips=new LinkedHashMap<>();public AnimationSet(String key,String name){this.key=key;this.name=name==null?key:name;}public String clip(String state,String direction){String s=state==null?"":state,d=direction==null?"DOWN":direction;String exact=clips.get(s+"|"+d);if(exact!=null&&!exact.isBlank())return exact;return clips.getOrDefault(s+"|DEFAULT","");}public AnimationSet copy(){AnimationSet c=new AnimationSet(key,name);c.directionMode=directionMode;c.useFlipX=useFlipX;c.clips.putAll(clips);return c;}@Override public String toString(){return name;}}
    public static final class StampPattern {public final String key;public String name;public int width,height;private int[]cells;public StampPattern(String key,String name,int width,int height){this.key=key;this.name=name==null?key:name;this.width=Math.max(1,width);this.height=Math.max(1,height);cells=new int[this.width*this.height];Arrays.fill(cells,-1);}public int get(int x,int y){return x<0||y<0||x>=width||y>=height?-1:cells[y*width+x];}public void set(int x,int y,int tile){if(x>=0&&y>=0&&x<width&&y<height)cells[y*width+x]=tile;}public int[]cells(){return cells.clone();}public void replaceCells(int[]v){if(v!=null&&v.length==width*height)cells=v.clone();}public void resize(int w,int h){w=Math.max(1,w);h=Math.max(1,h);int[]n=new int[w*h];Arrays.fill(n,-1);for(int y=0;y<Math.min(height,h);y++)System.arraycopy(cells,y*width,n,y*w,Math.min(width,w));width=w;height=h;cells=n;}public StampPattern copy(){StampPattern s=new StampPattern(key,name,width,height);s.cells=cells.clone();return s;}@Override public String toString(){return name;}}
''')
rep(model,
'''            case"Animator"->{p.put("controller","");p.put("clip","");p.put("state","");p.put("speed","1");p.put("flipX","false");p.put("flipY","false");p.put("frame","0");p.put("finished","false");}''',
'''            case"Animator"->{p.put("controller","");p.put("animationSet","");p.put("clip","");p.put("state","");p.put("direction","DOWN");p.put("speed","1");p.put("flipX","false");p.put("flipY","false");p.put("frame","0");p.put("finished","false");}''')
rep(model,
'''            case"Camera2D"->{p.put("target","");p.put("follow","true");p.put("zoom","1");p.put("offsetX","0");p.put("offsetY","0");p.put("pixelSnap","true");p.put("priority","0");p.put("smoothSpeed","0");p.put("deadZoneX","0");p.put("deadZoneY","0");p.put("shakeIntensity","0");p.put("shakeDuration","0");}''',
'''            case"Camera2D"->{p.put("target","");p.put("follow","true");p.put("zoom","1");p.put("zoomSpeed","0");p.put("offsetX","0");p.put("offsetY","0");p.put("pixelSnap","true");p.put("priority","0");p.put("smoothSpeed","0");p.put("deadZoneX","0");p.put("deadZoneY","0");p.put("minX","");p.put("minY","");p.put("maxX","");p.put("maxY","");p.put("shakeIntensity","0");p.put("shakeDuration","0");}''')
rex(model,r'''    public static final class MenuButton \{.*?\}\n    public static final class MenuScreen''',r'''    public static final class MenuButton {public String text;public int x,y,width,height;public MenuAction action;public String target,assetKey="",hoverAssetKey="",fontKey="",textStyleKey="",uiSkinKey="";public int fontSize=16;public boolean enabled=true;public Color textColor=Color.WHITE,backgroundColor=new Color(31,115,170);public MenuAnimation animation=MenuAnimation.NONE;public MenuHoverEffect hoverEffect=MenuHoverEffect.SCALE;public double animationSpeed=1;public MenuButton(String text,int x,int y,int width,int height,MenuAction action,String target){this.text=text;this.x=x;this.y=y;this.width=width;this.height=height;this.action=action;this.target=target==null?"":target;}public MenuButton copy(){MenuButton c=new MenuButton(text,x,y,width,height,action,target);c.assetKey=assetKey;c.hoverAssetKey=hoverAssetKey;c.fontKey=fontKey;c.textStyleKey=textStyleKey;c.uiSkinKey=uiSkinKey;c.enabled=enabled;c.fontSize=fontSize;c.textColor=textColor;c.backgroundColor=backgroundColor;c.animation=animation;c.hoverEffect=hoverEffect;c.animationSpeed=animationSpeed;return c;}}
    public static final class MenuScreen''')

# ---------------------------------------------------------------------------
# Sidecar persistence keeps the original 2.2 serialization compatible while
# persisting all RC-only data in one explicit resource.
# ---------------------------------------------------------------------------
io='src/main/java/com/buttclapdev/twogamerl/io/ProjectIO.java'
rep(io,'putProperties(zip,"project.properties",root);writeLayerConfig(zip,project);writeTiles(zip,project);writeVisualResources(zip,project);','putProperties(zip,"project.properties",root);writeLayerConfig(zip,project);writeTiles(zip,project);writeVisualResources(zip,project);RcProjectIO.write(zip,project);')
rep(io,'if(project.getTiles().isEmpty())project.getTiles().putAll(GameProject.createDefault().getTiles());if(project.getPrefabs().isEmpty())for(TileDef t:project.getTiles().values())project.getPrefabs().put(slug(t.name),PrefabDef.tile(slug(t.name),t.name,t.id));if(version<2)migrateV1(project);inferLegacyLayers(project,version);return project;','RcProjectIO.read(project,entries);if(project.getTiles().isEmpty())project.getTiles().putAll(GameProject.createDefault().getTiles());if(project.getPrefabs().isEmpty())for(TileDef t:project.getTiles().values())project.getPrefabs().put(slug(t.name),PrefabDef.tile(slug(t.name),t.name,t.id));if(version<2)migrateV1(project);inferLegacyLayers(project,version);return project;')

rcio=r'''package com.buttclapdev.twogamerl.io;

import com.buttclapdev.twogamerl.model.GameProject;
import com.buttclapdev.twogamerl.model.GameProject.*;

import java.awt.Color;
import java.io.*;
import java.util.*;
import java.util.zip.*;

/** RC sidecar persistence. Optional by design so every 2.2.x project remains loadable. */
final class RcProjectIO {
    private static final String ENTRY="rc-2.3.properties";
    private RcProjectIO(){}
    static void write(ZipOutputStream zip,GameProject p)throws IOException{
        Properties x=new Properties();
        int i=0;for(Asset a:p.getAssets().values()){String k="asset."+i+++".";x.setProperty(k+"key",a.key);x.setProperty(k+"folder",safe(a.folder));x.setProperty(k+"favorite",Boolean.toString(a.favorite));}x.setProperty("asset.count",Integer.toString(i));
        i=0;for(TileDef t:p.getTiles().values()){String k="tile."+i+++".";x.setProperty(k+"id",Integer.toString(t.id));x.setProperty(k+"mode",t.autotileMode.name());x.setProperty(k+"connectTag",safe(t.connectTag));x.setProperty(k+"variant.count",Integer.toString(t.variants.size()));for(int v=0;v<t.variants.size();v++){TileVariant tv=t.variants.get(v);x.setProperty(k+"variant."+v+".asset",safe(tv.assetKey));x.setProperty(k+"variant."+v+".weight",Double.toString(tv.weight));}x.setProperty(k+"rule.count",Integer.toString(t.autotileAssets.size()));int r=0;for(var e:t.autotileAssets.entrySet()){x.setProperty(k+"rule."+r+".mask",Integer.toString(e.getKey()));x.setProperty(k+"rule."+r+".asset",safe(e.getValue()));r++;}}x.setProperty("tile.count",Integer.toString(i));
        i=0;for(AnimationClip c:p.getAnimationClips().values()){String k="clip."+i+++".";x.setProperty(k+"key",c.key);x.setProperty(k+"reverse",Boolean.toString(c.reverse));x.setProperty(k+"fps",Double.toString(c.fps));for(int f=0;f<c.frames.size();f++){AnimationFrame fr=c.frames.get(f);x.setProperty(k+"frame."+f+".shape.count",Integer.toString(fr.shapes.size()));for(int s=0;s<fr.shapes.size();s++){FrameShape h=fr.shapes.get(s);String q=k+"frame."+f+".shape."+s+".";x.setProperty(q+"name",safe(h.name));x.setProperty(q+"role",h.role.name());x.setProperty(q+"x",Double.toString(h.x));x.setProperty(q+"y",Double.toString(h.y));x.setProperty(q+"w",Double.toString(h.width));x.setProperty(q+"h",Double.toString(h.height));}}}x.setProperty("clip.count",Integer.toString(i));
        i=0;for(AnimatorController c:p.getAnimatorControllers().values()){String k="controller."+i+++".";x.setProperty(k+"key",c.key);x.setProperty(k+"param.count",Integer.toString(c.parameters.size()));int z=0;for(AnimatorParameter a:c.parameters.values()){String q=k+"param."+z+++".";x.setProperty(q+"name",a.name);x.setProperty(q+"type",a.type.name());x.setProperty(q+"default",safe(a.defaultValue));}x.setProperty(k+"state.count",Integer.toString(c.states.size()));z=0;for(AnimatorState st:c.states.values()){String q=k+"state."+z+++".";x.setProperty(q+"name",st.name);x.setProperty(q+"blend.type",st.blendTree.type.name());x.setProperty(q+"blend.x",safe(st.blendTree.parameterX));x.setProperty(q+"blend.y",safe(st.blendTree.parameterY));x.setProperty(q+"blend.count",Integer.toString(st.blendTree.children.size()));for(int b=0;b<st.blendTree.children.size();b++){BlendChild ch=st.blendTree.children.get(b);String w=q+"blend."+b+".";x.setProperty(w+"clip",safe(ch.clipKey));x.setProperty(w+"x",Double.toString(ch.x));x.setProperty(w+"y",Double.toString(ch.y));}}}x.setProperty("controller.count",Integer.toString(i));
        i=0;for(UISkinAsset s:p.getUiSkins().values()){String k="skin."+i+++".";x.setProperty(k+"key",s.key);x.setProperty(k+"name",safe(s.name));x.setProperty(k+"normal",safe(s.normalAssetKey));x.setProperty(k+"hover",safe(s.hoverAssetKey));x.setProperty(k+"pressed",safe(s.pressedAssetKey));x.setProperty(k+"disabled",safe(s.disabledAssetKey));x.setProperty(k+"font",safe(s.fontKey));x.setProperty(k+"text",Integer.toString(s.textColor.getRGB()));x.setProperty(k+"disabledText",Integer.toString(s.disabledTextColor.getRGB()));x.setProperty(k+"background",Integer.toString(s.backgroundColor.getRGB()));x.setProperty(k+"border",Integer.toString(s.borderColor.getRGB()));x.setProperty(k+"paddingX",Double.toString(s.paddingX));x.setProperty(k+"paddingY",Double.toString(s.paddingY));x.setProperty(k+"borderWidth",Double.toString(s.borderWidth));x.setProperty(k+"radius",Double.toString(s.radius));x.setProperty(k+"animation",s.animation.name());}x.setProperty("skin.count",Integer.toString(i));
        i=0;for(AnimationSet s:p.getAnimationSets().values()){String k="set."+i+++".";x.setProperty(k+"key",s.key);x.setProperty(k+"name",safe(s.name));x.setProperty(k+"mode",s.directionMode.name());x.setProperty(k+"flip",Boolean.toString(s.useFlipX));x.setProperty(k+"clip.count",Integer.toString(s.clips.size()));int z=0;for(var e:s.clips.entrySet()){x.setProperty(k+"clip."+z+".slot",e.getKey());x.setProperty(k+"clip."+z+".value",e.getValue());z++;}}x.setProperty("set.count",Integer.toString(i));
        i=0;for(StampPattern s:p.getStampPatterns().values()){String k="stamp."+i+++".";x.setProperty(k+"key",s.key);x.setProperty(k+"name",safe(s.name));x.setProperty(k+"width",Integer.toString(s.width));x.setProperty(k+"height",Integer.toString(s.height));StringJoiner j=new StringJoiner(",");for(int c:s.cells())j.add(Integer.toString(c));x.setProperty(k+"cells",j.toString());}x.setProperty("stamp.count",Integer.toString(i));
        i=0;for(TextStyle s:p.getTextStyles().values()){String k="text."+i+++".";x.setProperty(k+"key",s.key);x.setProperty(k+"uiSkin",safe(s.uiSkinKey));}x.setProperty("text.count",Integer.toString(i));
        i=0;for(MenuScreen m:p.getMenus().values()){String k="menu."+i+++".";x.setProperty(k+"id",m.id);x.setProperty(k+"button.count",Integer.toString(m.buttons.size()));for(int b=0;b<m.buttons.size();b++){MenuButton btn=m.buttons.get(b);x.setProperty(k+"button."+b+".skin",safe(btn.uiSkinKey));x.setProperty(k+"button."+b+".enabled",Boolean.toString(btn.enabled));}}x.setProperty("menu.count",Integer.toString(i));
        ByteArrayOutputStream out=new ByteArrayOutputStream();x.store(out,"2gameRL 2.3 RC feature sidecar");zip.putNextEntry(new ZipEntry(ENTRY));zip.write(out.toByteArray());zip.closeEntry();
    }
    static void read(GameProject p,Map<String,byte[]>entries)throws IOException{
        byte[] raw=entries.get(ENTRY);if(raw==null)return;Properties x=new Properties();try(InputStream in=new ByteArrayInputStream(raw)){x.load(in);}
        for(int i=0;i<num(x,"asset.count",0);i++){String k="asset."+i+".";Asset a=p.getAssets().get(x.getProperty(k+"key",""));if(a!=null){a.folder=x.getProperty(k+"folder","");a.favorite=bool(x,k+"favorite",false);}}
        for(int i=0;i<num(x,"tile.count",0);i++){String k="tile."+i+".";TileDef t=p.getTiles().get(num(x,k+"id",-1));if(t==null)continue;t.autotileMode=en(TileAutotileMode.class,x.getProperty(k+"mode"),TileAutotileMode.NONE);t.connectTag=x.getProperty(k+"connectTag","");t.variants.clear();for(int v=0;v<num(x,k+"variant.count",0);v++)t.variants.add(new TileVariant(x.getProperty(k+"variant."+v+".asset",""),dec(x,k+"variant."+v+".weight",1)));t.autotileAssets.clear();for(int r=0;r<num(x,k+"rule.count",0);r++)t.autotileAssets.put(num(x,k+"rule."+r+".mask",0),x.getProperty(k+"rule."+r+".asset",""));}
        for(int i=0;i<num(x,"clip.count",0);i++){String k="clip."+i+".";AnimationClip c=p.getAnimationClips().get(x.getProperty(k+"key",""));if(c==null)continue;c.reverse=bool(x,k+"reverse",false);c.fps=Math.max(0,dec(x,k+"fps",0));for(int f=0;f<c.frames.size();f++){AnimationFrame fr=c.frames.get(f);fr.shapes.clear();for(int s=0;s<num(x,k+"frame."+f+".shape.count",0);s++){String q=k+"frame."+f+".shape."+s+".";fr.shapes.add(new FrameShape(x.getProperty(q+"name","shape"),en(FrameShapeRole.class,x.getProperty(q+"role"),FrameShapeRole.HITBOX),dec(x,q+"x",0),dec(x,q+"y",0),dec(x,q+"w",.5),dec(x,q+"h",.5)));}}}
        for(int i=0;i<num(x,"controller.count",0);i++){String k="controller."+i+".";AnimatorController c=p.getAnimatorControllers().get(x.getProperty(k+"key",""));if(c==null)continue;c.parameters.clear();for(int z=0;z<num(x,k+"param.count",0);z++){String q=k+"param."+z+".",name=x.getProperty(q+"name","param"+z);c.parameters.put(name,new AnimatorParameter(name,en(AnimatorParameterType.class,x.getProperty(q+"type"),AnimatorParameterType.FLOAT),x.getProperty(q+"default","0")));}for(int z=0;z<num(x,k+"state.count",0);z++){String q=k+"state."+z+".";AnimatorState st=c.states.get(x.getProperty(q+"name",""));if(st==null)continue;st.blendTree.type=en(BlendTreeType.class,x.getProperty(q+"blend.type"),BlendTreeType.NONE);st.blendTree.parameterX=x.getProperty(q+"blend.x","");st.blendTree.parameterY=x.getProperty(q+"blend.y","");st.blendTree.children.clear();for(int b=0;b<num(x,q+"blend.count",0);b++){String w=q+"blend."+b+".";st.blendTree.children.add(new BlendChild(x.getProperty(w+"clip",""),dec(x,w+"x",0),dec(x,w+"y",0)));}}}
        p.getUiSkins().clear();for(int i=0;i<num(x,"skin.count",0);i++){String k="skin."+i+".",key=x.getProperty(k+"key","skin-"+i);UISkinAsset s=new UISkinAsset(key,x.getProperty(k+"name",key));s.normalAssetKey=x.getProperty(k+"normal","");s.hoverAssetKey=x.getProperty(k+"hover","");s.pressedAssetKey=x.getProperty(k+"pressed","");s.disabledAssetKey=x.getProperty(k+"disabled","");s.fontKey=x.getProperty(k+"font","");s.textColor=color(x,k+"text",Color.WHITE);s.disabledTextColor=color(x,k+"disabledText",new Color(170,170,170));s.backgroundColor=color(x,k+"background",new Color(31,115,170));s.borderColor=color(x,k+"border",new Color(75,106,132));s.paddingX=dec(x,k+"paddingX",12);s.paddingY=dec(x,k+"paddingY",8);s.borderWidth=dec(x,k+"borderWidth",1);s.radius=dec(x,k+"radius",7);s.animation=en(MenuAnimation.class,x.getProperty(k+"animation"),MenuAnimation.NONE);p.getUiSkins().put(key,s);}
        p.getAnimationSets().clear();for(int i=0;i<num(x,"set.count",0);i++){String k="set."+i+".",key=x.getProperty(k+"key","set-"+i);AnimationSet s=new AnimationSet(key,x.getProperty(k+"name",key));s.directionMode=en(DirectionMode.class,x.getProperty(k+"mode"),DirectionMode.FOUR);s.useFlipX=bool(x,k+"flip",false);for(int z=0;z<num(x,k+"clip.count",0);z++)s.clips.put(x.getProperty(k+"clip."+z+".slot",""),x.getProperty(k+"clip."+z+".value",""));p.getAnimationSets().put(key,s);}
        p.getStampPatterns().clear();for(int i=0;i<num(x,"stamp.count",0);i++){String k="stamp."+i+".",key=x.getProperty(k+"key","stamp-"+i);StampPattern s=new StampPattern(key,x.getProperty(k+"name",key),num(x,k+"width",1),num(x,k+"height",1));String[] cells=x.getProperty(k+"cells","").split(",");int[] values=new int[s.width*s.height];Arrays.fill(values,-1);for(int z=0;z<Math.min(values.length,cells.length);z++)try{values[z]=Integer.parseInt(cells[z]);}catch(Exception ignored){}s.replaceCells(values);p.getStampPatterns().put(key,s);}
        for(int i=0;i<num(x,"text.count",0);i++){String k="text."+i+".";TextStyle s=p.getTextStyles().get(x.getProperty(k+"key",""));if(s!=null)s.uiSkinKey=x.getProperty(k+"uiSkin","");}
        for(int i=0;i<num(x,"menu.count",0);i++){String k="menu."+i+".";MenuScreen m=p.getMenus().get(x.getProperty(k+"id",""));if(m==null)continue;for(int b=0;b<Math.min(m.buttons.size(),num(x,k+"button.count",0));b++){m.buttons.get(b).uiSkinKey=x.getProperty(k+"button."+b+".skin","");m.buttons.get(b).enabled=bool(x,k+"button."+b+".enabled",true);}}
    }
    private static String safe(String s){return s==null?"":s;}private static int num(Properties p,String k,int d){try{return Integer.parseInt(p.getProperty(k,Integer.toString(d)));}catch(Exception e){return d;}}private static double dec(Properties p,String k,double d){try{return Double.parseDouble(p.getProperty(k,Double.toString(d)));}catch(Exception e){return d;}}private static boolean bool(Properties p,String k,boolean d){return Boolean.parseBoolean(p.getProperty(k,Boolean.toString(d)));}private static Color color(Properties p,String k,Color d){try{return new Color(Integer.parseInt(p.getProperty(k,Integer.toString(d.getRGB()))),true);}catch(Exception e){return d;}}private static <E extends Enum<E>>E en(Class<E>c,String v,E d){try{return Enum.valueOf(c,v);}catch(Exception e){return d;}}
}
'''
write('src/main/java/com/buttclapdev/twogamerl/io/RcProjectIO.java',rcio)

resolver=r'''package com.buttclapdev.twogamerl.model;

import com.buttclapdev.twogamerl.model.GameProject.*;
import java.util.*;

/** Deterministic visual resolution for weighted variants and 4/8-way autotiles. */
public final class AdvancedTileResolver {
    private AdvancedTileResolver(){}
    public static String assetFor(GameProject project,Level level,TileLayer layer,int x,int y,TileDef tile){
        if(project==null||level==null||layer==null||tile==null)return"";
        if(tile.autotileMode!=TileAutotileMode.NONE&&!tile.autotileAssets.isEmpty()){int mask=mask(project,layer,x,y,tile);String exact=tile.autotileAssets.get(mask);if(exact==null&&tile.autotileMode==TileAutotileMode.EIGHT_WAY)exact=tile.autotileAssets.get(mask&15);if(exact!=null&&!exact.isBlank())return exact;}
        if(!tile.variants.isEmpty()){double total=tile.variants.stream().mapToDouble(v->Math.max(0,v.weight)).sum();if(total>0){long seed=1469598103934665603L;seed=(seed^tile.id)*1099511628211L;seed=(seed^x)*1099511628211L;seed=(seed^y)*1099511628211L;seed=(seed^layer.id.hashCode())*1099511628211L;double pick=(new SplittableRandom(seed).nextDouble())*total;for(TileVariant v:tile.variants){pick-=Math.max(0,v.weight);if(pick<=0&&!v.assetKey.isBlank())return v.assetKey;}}}
        return tile.assetKey==null?"":tile.assetKey;
    }
    public static int mask(GameProject project,TileLayer layer,int x,int y,TileDef tile){int m=0;if(connects(project,layer,x,y-1,tile))m|=1;if(connects(project,layer,x+1,y,tile))m|=2;if(connects(project,layer,x,y+1,tile))m|=4;if(connects(project,layer,x-1,y,tile))m|=8;if(tile.autotileMode==TileAutotileMode.EIGHT_WAY){if(connects(project,layer,x+1,y-1,tile))m|=16;if(connects(project,layer,x+1,y+1,tile))m|=32;if(connects(project,layer,x-1,y+1,tile))m|=64;if(connects(project,layer,x-1,y-1,tile))m|=128;}return m;}
    private static boolean connects(GameProject p,TileLayer l,int x,int y,TileDef t){int id=l.get(x,y);if(id<0)return false;if(id==t.id)return true;TileDef other=p.getTiles().get(id);return other!=null&&!t.connectTag.isBlank()&&other.tags.contains(t.connectTag);}
}
'''
write('src/main/java/com/buttclapdev/twogamerl/model/AdvancedTileResolver.java',resolver)

integrity=r'''package com.buttclapdev.twogamerl.model;

import com.buttclapdev.twogamerl.model.GameProject.*;
import java.util.*;
import java.util.regex.*;

/** Project-wide dependency inspection and safe asset replacement used by RC authoring tools. */
public final class ResourceIntegrity {
    private ResourceIntegrity(){}
    public static List<String>assetUses(GameProject p,String key){ArrayList<String>u=new ArrayList<>();if(p==null||key==null)return u;for(Asset a:p.getAssets().values())if(key.equals(a.sourceAssetKey))u.add("Región "+a.key);for(TileDef t:p.getTiles().values()){if(key.equals(t.assetKey))u.add("Tile "+t.name);for(TileVariant v:t.variants)if(key.equals(v.assetKey))u.add("Variante de tile "+t.name);if(t.autotileAssets.containsValue(key))u.add("Autotile "+t.name);}for(AnimationClip c:p.getAnimationClips().values())for(AnimationFrame f:c.frames)if(key.equals(f.assetKey))u.add("Animación "+c.name);for(Level l:p.getLevels().values()){if(key.equals(l.backgroundAssetKey))u.add("Fondo de escena "+l.name);for(EntityDef e:l.entities)if(key.equals(e.assetKey))u.add("Entidad "+e.name);}for(PrefabDef f:p.getPrefabs().values())if(f.template!=null&&key.equals(f.template.assetKey))u.add("Prefab "+f.name);for(MenuScreen m:p.getMenus().values()){if(key.equals(m.backgroundAssetKey)||key.equals(m.titleAssetKey))u.add("Menú "+m.title);for(MenuButton b:m.buttons)if(key.equals(b.assetKey)||key.equals(b.hoverAssetKey))u.add("Botón "+b.text);}for(TextStyle s:p.getTextStyles().values())if(key.equals(s.skinAssetKey))u.add("TextStyle "+s.name);for(ParticlePreset s:p.getParticlePresets().values())if(key.equals(s.assetKey))u.add("Partículas "+s.name);for(UISkinAsset s:p.getUiSkins().values())if(List.of(s.normalAssetKey,s.hoverAssetKey,s.pressedAssetKey,s.disabledAssetKey).contains(key))u.add("UISkin "+s.name);return u.stream().distinct().toList();}
    public static int replaceAsset(GameProject p,String oldKey,String newKey){if(p==null||oldKey==null||oldKey.equals(newKey))return 0;int[]n={0};for(Asset a:p.getAssets().values())if(oldKey.equals(a.sourceAssetKey)){a.sourceAssetKey=newKey;n[0]++;}for(TileDef t:p.getTiles().values()){if(oldKey.equals(t.assetKey)){t.assetKey=newKey;n[0]++;}for(TileVariant v:t.variants)if(oldKey.equals(v.assetKey)){v.assetKey=newKey;n[0]++;}t.autotileAssets.replaceAll((m,v)->{if(oldKey.equals(v)){n[0]++;return newKey;}return v;});}for(AnimationClip c:p.getAnimationClips().values())for(AnimationFrame f:c.frames)if(oldKey.equals(f.assetKey)){f.assetKey=newKey;n[0]++;}for(Level l:p.getLevels().values()){if(oldKey.equals(l.backgroundAssetKey)){l.backgroundAssetKey=newKey;n[0]++;}l.script=replaceToken(l.script,oldKey,newKey);for(TileLayer z:l.tileLayers)z.script=replaceToken(z.script,oldKey,newKey);for(EntityDef e:l.entities){if(oldKey.equals(e.assetKey)){e.assetKey=newKey;n[0]++;}e.script=replaceToken(e.script,oldKey,newKey);for(ComponentDef c:e.components)c.properties.replaceAll((k,v)->oldKey.equals(v)?newKey:v);}}for(PrefabDef f:p.getPrefabs().values())if(f.template!=null){if(oldKey.equals(f.template.assetKey)){f.template.assetKey=newKey;n[0]++;}f.template.script=replaceToken(f.template.script,oldKey,newKey);for(ComponentDef c:f.template.components)c.properties.replaceAll((k,v)->oldKey.equals(v)?newKey:v);}for(MenuScreen m:p.getMenus().values()){if(oldKey.equals(m.backgroundAssetKey)){m.backgroundAssetKey=newKey;n[0]++;}if(oldKey.equals(m.titleAssetKey)){m.titleAssetKey=newKey;n[0]++;}for(MenuButton b:m.buttons){if(oldKey.equals(b.assetKey)){b.assetKey=newKey;n[0]++;}if(oldKey.equals(b.hoverAssetKey)){b.hoverAssetKey=newKey;n[0]++;}}}for(TextStyle s:p.getTextStyles().values())if(oldKey.equals(s.skinAssetKey)){s.skinAssetKey=newKey;n[0]++;}for(ParticlePreset s:p.getParticlePresets().values())if(oldKey.equals(s.assetKey)){s.assetKey=newKey;n[0]++;}for(UISkinAsset s:p.getUiSkins().values()){if(oldKey.equals(s.normalAssetKey)){s.normalAssetKey=newKey;n[0]++;}if(oldKey.equals(s.hoverAssetKey)){s.hoverAssetKey=newKey;n[0]++;}if(oldKey.equals(s.pressedAssetKey)){s.pressedAssetKey=newKey;n[0]++;}if(oldKey.equals(s.disabledAssetKey)){s.disabledAssetKey=newKey;n[0]++;}}return n[0];}
    public static List<String>brokenAssetReferences(GameProject p){ArrayList<String>b=new ArrayList<>();Set<String>keys=p.getAssets().keySet();for(TileDef t:p.getTiles().values()){check(b,keys,t.assetKey,"Tile "+t.name);for(TileVariant v:t.variants)check(b,keys,v.assetKey,"Variante "+t.name);for(String a:t.autotileAssets.values())check(b,keys,a,"Autotile "+t.name);}for(AnimationClip c:p.getAnimationClips().values())for(AnimationFrame f:c.frames)check(b,keys,f.assetKey,"Clip "+c.name);for(UISkinAsset s:p.getUiSkins().values())for(String a:List.of(s.normalAssetKey,s.hoverAssetKey,s.pressedAssetKey,s.disabledAssetKey))check(b,keys,a,"UISkin "+s.name);for(ParticlePreset s:p.getParticlePresets().values())check(b,keys,s.assetKey,"Partículas "+s.name);return b;}
    private static void check(List<String>o,Set<String>keys,String ref,String where){if(ref!=null&&!ref.isBlank()&&!keys.contains(ref))o.add(where+" → falta "+ref);}private static String replaceToken(String s,String oldKey,String newKey){if(s==null||s.isEmpty())return s;return s.replaceAll("(?<![A-Za-z0-9_.-])"+Pattern.quote(oldKey)+"(?![A-Za-z0-9_.-])",Matcher.quoteReplacement(newKey));}
}
'''
write('src/main/java/com/buttclapdev/twogamerl/model/ResourceIntegrity.java',integrity)

print('RC phase A model/persistence staged')
