package com.buttclapdev.twogamerl;

import com.buttclapdev.twogamerl.io.ProjectIO;
import com.buttclapdev.twogamerl.model.GameProject;
import com.buttclapdev.twogamerl.model.GameProject.*;
import org.junit.jupiter.api.Test;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import static org.junit.jupiter.api.Assertions.*;

class GameProjectTest {
    @Test void defaultProjectStartsNeutralAndKeepsOnePhysicalSampleSheet(){
        GameProject p=GameProject.createDefault();Level level=p.getLevels().get("level-1");assertNotNull(level);assertTrue(level.entities.isEmpty(),"Una escena nueva no debe imponer un jugador ni género de juego.");assertEquals(1,level.tileLayers.size());for(int cell:level.baseLayer().cells())assertEquals(-1,cell,"La cuadrícula debe comenzar vacía.");assertFalse(level.boundaryLeft);assertFalse(level.boundaryRight);assertFalse(level.boundaryTop);assertFalse(level.boundaryBottom);assertEquals(BackgroundMode.COLOR,level.backgroundMode);assertEquals("level-1",p.getMenus().get("main").buttons.getFirst().target);
        Asset placeholder=p.getAssets().get("placeholder-player.png"),sheet=p.getAssets().get("sample-sheet-32.png"),first=p.getAssets().get("sample-00-00"),last=p.getAssets().get("sample-09-09");assertNotNull(placeholder);assertNotNull(placeholder.image());assertNotNull(sheet);assertTrue(sheet.sourceOnly);assertNotNull(sheet.data);assertTrue(first.isRegion());assertTrue(last.isRegion());assertNull(first.data);assertEquals("sample-sheet-32.png",first.sourceAssetKey);assertEquals(32,first.regionWidth);assertEquals(32,first.regionHeight);assertEquals(102,p.getAssets().size());assertEquals(101,p.getDrawableAssetKeys().size());
    }

    @Test void projectRoundTripPreservesScenesLayersFontsMenusScriptsAndRegions() throws Exception {
        GameProject p=GameProject.createDefault();Level level=p.getLevels().get("level-1");level.backgroundAssetKey="sample-00-00";level.backgroundMode=BackgroundMode.COVER;level.boundaryBottom=true;level.script="on event noche\n  scene.backgroundMode = contain\nend\n";level.variables.put("clima","seco");
        EntityDef enemy=new EntityDef("enemy-1","Enemigo",5.25,6.5);enemy.group="Enemigos";enemy.assetKey="sample-02-00";enemy.renderLayer="Personajes";enemy.physicsLayer="Enemy";enemy.components.add(ComponentDef.preset("Patrol"));enemy.components.add(ComponentDef.preset("Health"));enemy.variables.put("score","7");enemy.script="on start\n  Health.current = 80\nend\n";level.entities.add(enemy);
        TileLayer foreground=new TileLayer("foreground","Frente",level.width,level.height,4);foreground.set(3,3,1);foreground.visible=true;foreground.locked=true;foreground.collision=false;foreground.physicsLayer="World";foreground.renderLayer="Frente";foreground.script="on event ocultar\n  layer.enabled = false\nend\n";foreground.variables.put("estado","activo");level.tileLayers.add(foreground);p.setCollision("Player","Enemy",false);
        p.getFonts().put("custom.ttf",new FontAsset("custom.ttf","Custom.ttf",new byte[]{1,2,3,4}));MenuScreen menu=p.getMenus().get("main");menu.backgroundAssetKey="sample-00-00";menu.titleAssetKey="sample-01-00";menu.titleFontKey="custom.ttf";menu.titleAnimation=MenuAnimation.PULSE;menu.titleAnimationSpeed=1.75;MenuButton play=menu.buttons.getFirst();play.assetKey="sample-02-00";play.hoverAssetKey="sample-03-00";play.fontKey="custom.ttf";play.animation=MenuAnimation.FLOAT;play.hoverEffect=MenuHoverEffect.GLOW;
        Path file=Files.createTempFile("2gamerl-roundtrip-",".2grl");try{ProjectIO.save(p,file);GameProject loaded=ProjectIO.load(file);assertEquals(102,loaded.getAssets().size());assertArrayEquals(new byte[]{1,2,3,4},loaded.getFonts().get("custom.ttf").data);assertFalse(loaded.canCollide("Player","Enemy"));Level ll=loaded.getLevels().get("level-1");assertEquals("sample-00-00",ll.backgroundAssetKey);assertEquals(BackgroundMode.COVER,ll.backgroundMode);assertTrue(ll.boundaryBottom);assertTrue(ll.script.contains("scene.backgroundMode"));assertEquals("seco",ll.variables.get("clima"));assertEquals(2,ll.tileLayers.size());TileLayer lf=ll.tileLayers.stream().filter(l->l.id.equals("foreground")).findFirst().orElseThrow();assertEquals(1,lf.get(3,3));assertTrue(lf.locked);assertFalse(lf.collision);assertEquals("Frente",lf.renderLayer);assertTrue(lf.script.contains("layer.enabled"));assertEquals("activo",lf.variables.get("estado"));EntityDef le=ll.entity("enemy-1");assertNotNull(le);assertTrue(le.script.contains("Health.current"));assertEquals("custom.ttf",loaded.getMenus().get("main").titleFontKey);assertEquals("custom.ttf",loaded.getMenus().get("main").buttons.getFirst().fontKey);}finally{Files.deleteIfExists(file);}}

    @Test void collisionMatrixIsSymmetricAndFiltersOnlyWhenRequested(){GameProject p=GameProject.createDefault();assertTrue(p.canCollide("Player","Enemy"));p.setCollision("Player","Enemy",false);assertFalse(p.canCollide("Player","Enemy"));assertFalse(p.canCollide("Enemy","Player"));p.setCollision("Enemy","Player",true);assertTrue(p.canCollide("Player","Enemy"));}

    @Test void legacyV1ProjectMigratesSpawnToPlayerEntity() throws Exception {Path file=Files.createTempFile("2gamerl-v1-",".2grl");try(ZipOutputStream zip=new ZipOutputStream(Files.newOutputStream(file))){Properties root=new Properties();root.setProperty("formatVersion","1");root.setProperty("title","Legacy");root.setProperty("startLevel","old");root.setProperty("startMenu","");root.setProperty("tileSize","32");put(zip,"project.properties",root);Properties tiles=new Properties();tiles.setProperty("count","1");tiles.setProperty("tile.0.id","0");tiles.setProperty("tile.0.name","Suelo");tiles.setProperty("tile.0.rgb",Integer.toString(java.awt.Color.GRAY.getRGB()));tiles.setProperty("tile.0.walkable","true");tiles.setProperty("tile.0.asset","");put(zip,"tiles.properties",tiles);Properties level=new Properties();level.setProperty("id","old");level.setProperty("name","Viejo");level.setProperty("width","4");level.setProperty("height","4");level.setProperty("spawnX","2");level.setProperty("spawnY","1");level.setProperty("cells","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0");put(zip,"levels/old.properties",level);}try{GameProject loaded=ProjectIO.load(file);EntityDef player=loaded.getLevels().get("old").entity("player");assertNotNull(player);assertEquals(2.0,player.x);assertEquals(1.0,player.y);assertEquals("Player",player.physicsLayer);assertTrue(loaded.getAssets().containsKey("placeholder-player.png"));}finally{Files.deleteIfExists(file);}}
    private static void put(ZipOutputStream zip,String name,Properties properties)throws Exception{zip.putNextEntry(new ZipEntry(name));ByteArrayOutputStream bytes=new ByteArrayOutputStream();properties.store(new OutputStreamWriter(bytes,StandardCharsets.UTF_8),"");zip.write(bytes.toByteArray());zip.closeEntry();}
}
